package computerdatabase.Module.Leave.Report

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

object EmployeeLeaveApproverListingReport {

  val uri1 = "https://maps.googleapis.com/maps/api/js"
  val uri3 = "https://fonts.googleapis.com/css"

  def loadLeaveApproverListing = {
    exec(http("Load Search Criteria page")
      .get("/CustomReport/ReportViewerDisplay/EmployeeLeaveApproverListingReport")
      .check(regex("""<input name="__RequestVerificationToken" type="hidden" value="(.+?)" />""").find.saveAs("__RequestVerificationTokenLogout"))
      .check(bodyString.saveAs("BodyCriteria"))
    )
      .exec(http("request_55")
        .get("/Content/ExecutiveDashboard/ExecutiveDashboardBundle?v=K3bp7bOUCg7jvMi3yCOp8VvRDHaxkZJNkgNJYDsPeIA1")
      )
      .exec(http("request_56")
        .get("/Content/ExecutiveDashboardBundle?v=yudLVP8cmmFF7pYfIl5_OmdH-W3uaCGxdSLyC-jbYQo1")
      )
      .exec(http("request_57")
        .get("/Content/css/root?v=fQqb8rdb3SX3t_q5clLhrjqLMPJRz5XyrffvnRHeaqY1")
      )
      .exec(http("request_58")
        .get(uri3 + "?family=Open+Sans:300,400,600,700")
      )
      .exec(http("request_59")
        .get(uri3 + "?family=Roboto:400,300,500,700")
      )
      .exec(http("request_60")
        .get("/DXR.axd?r=0_2312,1_50,1_53,1_51,0_2317,1_40,1_17,0_2214,1_16,0_2219,0_2221,0_2225,1_18,1_4,0_2279,6_3,0_2283,0_2186,0_2190,0_2257,18_3,18_11,18_7,0_2261,0_2313,1_34,24_359,24_364,24_360,9_19,9_15,9_12,0_2338,9_1,0_2342,9_4,1_7-WYXkk")
      )
      .exec(http("request_61")
        .get("/bundles/jquery?v=w1vknpWt6KqlZcHeJQvaK6VbvvXt1Go8HcGH_DqKzzo1")
      )
      .pause(155.milliseconds)
      .exec(http("request_62")
        .get("/Content/fonts/icomoon.ttf?5vru0d")
      )
      .exec(http("request_63")
        .get("/Scripts/ExecutiveDashboardBundle?v=DMMQIR-OxHUTpie3SbH9hPNfqqge6hNdl_5G39s54KA1")
      )
      .exec(http("request_64")
        .get("/Scripts/ExecutiveDashboardBundle/SideMenu?v=wmt4mX4cYH0d844GQc8r_NWCLWWdnZ_egKD54y34J2U1")
      )
      .exec(http("request_65")
        .get("/bundles/bootstrap?v=2Fz3B0iizV2NnnamQFrx-NbYJNTFeBJ2GM05SilbtQU1")
      )
      .pause(665.milliseconds)
      .exec(http("request_66")
        .get("/Content/Images/unifiedhcms_logo.png?V=01")
      )
      .exec(http("request_67")
        .get("/DXR.axd?r=1_58-lUXkk")
      )
      .exec(http("request_68")
        .get("/signalr/hubs")
      )
      .exec(http("request_69")
        .get("/profile_picture.ashx?EmployeeID=7317")
      )
      .exec(http("request_70")
        .get("/Scripts/MasterDevExBundle?v=yx5tJIYhtWXcJGGiFMJ_bRJ0-eldYrvLrqRE_KNFrnI1")
      )
      .pause(575.milliseconds)
      .exec(http("request_71")
        .get("/DXR.axd?r=0_2314-4WXkk")
      )
      .exec(http("request_72")
        .get("/DXR.axd?r=0_2316-4WXkk")
      )
      .exec(http("request_73")
        .get("/DXR.axd?r=0_2216-4WXkk")
      )
      .pause(145.milliseconds)
      .exec(http("request_74")
        .get(uri1 + "?key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A")
      )
      .exec(http("request_75")
        .get("/Scripts/RootBundle?v=Z5MJwH8Xi0bCONWdJcmOtX_Ca81BpX4JptdIbZb919g1")
      )
      .pause(908.milliseconds)
      .exec(http("request_76")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_77")
        .get("/DXR.axd?r=0_2303-4WXkk")
      )
  }

  def searchFilter = {
    exec(http("request_78")
      .post("/CustomReport/CheckBoxListDisplay")
      .formParam("objectLabel", "EmployeeStatus")
      .formParam("objectSelectedIds[]", "A")
      .formParam("objectSelectedIds[]", "L")
      .formParam("objectSelectedIds[]", "I"))
      .pause(457.milliseconds)
      .exec(http("request_79")
        .get("/Notifications/GetNotificationCounts")
      )
      .exec(http("request_80")
        .get("/Notifications/GetNotificationUserId")
      )
      .exec(http("request_81")
        .get("/signalr/negotiate?clientProtocol=2.1&userid=KM00393&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1620181904551")
      )
      .pause(552.milliseconds)
      .exec(http("request_82")
        .get("/signalr/start?transport=webSockets&clientProtocol=2.1&userid=KM00393&connectionToken=78cx3ipjTH48syC5%2FyQumgomLJTuRK0noSFnQYIOdWj36MTyrreO0WpadjolEOMZz7lZ0ptVtn5WuX5UPSndd8TOAnweT0VrXuXzHDh4aqGvwiAKkroY%2FCdlCwJlZhuFa9E3zVvhbwuyF7DRJ4IQuUt58Oavupu7obSzK9165SQ%3D&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1620181904552")
      )
      .pause(2)
      .exec(http("request_83")
        .get(uri1 + "/AuthenticationService.Authenticate?1shttps%3A%2F%2Forisoftst.orisoftsaas.com%2FCustomReport%2FReportViewerDisplay%2FEmployeeLeaveApproverListingReport&4sAIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A&callback=_xdc_._niynu5&key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A&token=3791")
      )
    .exec(http("request_85")
      .post("/Criteria/RenderOrganizationUnitsPartial")

      .formParam("organizationLevel", "1")
      .formParam("criteriaObject[Type]", "OrganizationUnits")
      .formParam("criteriaObject[Name]", "Organization")
      .formParam("criteriaObject[Label]", "Organization")
      .formParam("criteriaObject[DefaultValue]", "")
      .formParam("criteriaObject[DefaultDate]", "")
      .formParam("criteriaObject[DefaultDateRangeFrom]", "")
      .formParam("criteriaObject[DefaultDateRangeTo]", "")
      .formParam("criteriaObject[Value]", "")
      .formParam("criteriaObject[GroupId]", "2")
      .formParam("criteriaObject[IsRequired]", "false")
      .formParam("criteriaObject[Group][Id]", "2")
      .formParam("criteriaObject[Group][Title]", "Optional Selection")
      .formParam("criteriaObject[DropDownListProperties][TextField]", "LOCATION_LABEL")
      .formParam("criteriaObject[DropDownListProperties][ValueField]", "LOCATION_LEVEL")
      .formParam("criteriaObject[DropDownListProperties][FilterField]", "")
      .formParam("criteriaObject[DropDownListProperties][DatasourceName]", "OrganizationLevels")
      .formParam("criteriaObject[DropDownListProperties][DisplayFormatString]", "")
      .formParam("criteriaObject[DropDownListProperties][SourceFrom]", "0")
      .formParam("criteriaObject[DropDownListProperties][DefaultIndex]", "")
      .formParam("criteriaObject[DropDownListProperties][SelectedIndexChangedJsCallBack]", "")
      .formParam("criteriaObject[DropDownListProperties][ColumnsList]", "")
      .formParam("criteriaObject[DropDownListProperties][IsMultiSelection]", "true")
      .formParam("criteriaObject[DropDownListProperties][DefaultValues]", "")
      .formParam("criteriaObject[DropDownListProperties][LoadOnDemand]", "false")
      .formParam("criteriaObject[DropDownListProperties][SelectAllMode]", "false")
      .formParam("criteriaObject[DropDownListProperties][DefaultSelectAll]", "false")
      .formParam("criteriaObject[DropDownListProperties][CascadeControl]", "")
      .formParam("criteriaObject[DropDownListProperties][DatasourceParameters]", "")
      .formParam("criteriaObject[DropDownListProperties][IsWrapText]", "true")
      .formParam("criteriaObject[CascadeDropDownListProperties]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][TextField]", "LOCATION_NAME")
      .formParam("criteriaObject[ChildDropDownListProperties][ValueField]", "LOCATION_CODE")
      .formParam("criteriaObject[ChildDropDownListProperties][FilterField]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][DatasourceName]", "AllEntityLocations")
      .formParam("criteriaObject[ChildDropDownListProperties][DisplayFormatString]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][SourceFrom]", "0")
      .formParam("criteriaObject[ChildDropDownListProperties][DefaultIndex]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][SelectedIndexChangedJsCallBack]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][0][Name]", "LOCATION_CODE")
      .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][0][Label]", "Code")
      .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][0][Width]", "120")
      .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][0][ColumnDisplayFormatString]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][1][Name]", "LOCATION_NAME")
      .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][1][Label]", "Description")
      .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][1][Width]", "350")
      .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][1][ColumnDisplayFormatString]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][IsMultiSelection]", "true")
      .formParam("criteriaObject[ChildDropDownListProperties][DefaultValues]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][LoadOnDemand]", "false")
      .formParam("criteriaObject[ChildDropDownListProperties][SelectAllMode]", "false")
      .formParam("criteriaObject[ChildDropDownListProperties][DefaultSelectAll]", "false")
      .formParam("criteriaObject[ChildDropDownListProperties][CascadeControl]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][DatasourceParameters]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][IsWrapText]", "false")
      .formParam("criteriaObject[CheckListProperties]", "")
      .formParam("criteriaObject[DefaultIndex]", "")
      .formParam("criteriaObject[IsAddLabel]", "false")
      .formParam("criteriaObject[IsChecked]", "false")
      .formParam("criteriaObject[Caption]", "")
      .formParam("criteriaObject[CheckedChangedJsCallBack]", "")
      .formParam("criteriaObject[MaxLength]", "0")
      .formParam("criteriaObject[DisplayFormatString]", "")
      .formParam("criteriaObject[NullText]", "")
      .formParam("criteriaObject[ShowIncrementButtons]", "false")
      .formParam("criteriaObject[Page]", "0")
      .formParam("criteriaObject[CascadeControl]", "")
      .formParam("criteriaObject[ValueFieldDelimiter]", "")
      .formParam("criteriaObject[DownloadBy]", "")
      .formParam("criteriaObject[InitJsCallBack]", "")
      .formParam("criteriaObject[MultiValueDelimiter]", "")
      .formParam("criteriaObject[DefaultValueTo]", ""))
      .pause(2)
      .exec(http("request_86")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_87")
        .post("/CustomReport/OrganizationUnitsDisplay")

        .formParam("objectLabel", "Organization")
        .formParam("objectSelectedIds[0][Number]", "1")
        .formParam("objectSelectedIds[0][Name]", "Company")
        .formParam("objectSelectedIds[0][UnitsId][]", "PPP"))
  }

  def clickSearch = {
    exec(http("Click Search")
      .post("/CustomReport/ReportViewerWithHeaderPartial")
      .formParam("layout[CustomSearchParameters][0][Name]", "EmployeeStatus")
      .formParam("layout[CustomSearchParameters][0][Value]", "A,L,I")
      .formParam("layout[CustomSearchParameters][1][Name]", "Year")
      .formParam("layout[CustomSearchParameters][1][Value]", "2021")
      .formParam("layout[CustomSearchParameters][2][Name]", "Location")
      .formParam("layout[CustomSearchParameters][2][Value]", "")
      .formParam("layout[CustomSearchParameters][3][Name]", "LevelRanges")
      .formParam("layout[CustomSearchParameters][3][Value]", "PPP|||||||||")
      .formParam("layout[CustomSearchParameters][4][Name]", "Category")
      .formParam("layout[CustomSearchParameters][4][Value]", "")
      .formParam("layout[CustomSearchParameters][5][Name]", "Position")
      .formParam("layout[CustomSearchParameters][5][Value]", "")
      .formParam("layout[CustomSearchParameters][6][Name]", "Grade")
      .formParam("layout[CustomSearchParameters][6][Value]", "")
      .formParam("layout[CustomSearchParameters][7][Name]", "Employee")
      .formParam("layout[CustomSearchParameters][7][Value]", "")
      .formParam("layout[CustomSearchParameters][8][Name]", "HireDateFrom")
      .formParam("layout[CustomSearchParameters][8][Value]", "")
      .formParam("layout[CustomSearchParameters][9][Name]", "HireDateTo")
      .formParam("layout[CustomSearchParameters][9][Value]", "")
      .formParam("layout[CustomSearchParameters][10][Name]", "TerminationDateFrom")
      .formParam("layout[CustomSearchParameters][10][Value]", "")
      .formParam("layout[CustomSearchParameters][11][Name]", "TerminationDateTo")
      .formParam("layout[CustomSearchParameters][11][Value]", "")
      .formParam("layout[CustomSearchParameters][12][Name]", "LeaveGroup")
      .formParam("layout[CustomSearchParameters][12][Value]", "")
      .formParam("layout[CustomSearchParameters][13][Name]", "LeaveType")
      .formParam("layout[CustomSearchParameters][13][Value]", "")
      .formParam("layout[GroupFooterSummaryTextField]", "Employee No.")
      .formParam("layout[NumberOfVisibleColumns]", "0")
      .formParam("layout[NumberOfGroupedColumns]", "0")
      .formParam("layout[ColumnProperties][0][Visible]", "true")
      .formParam("layout[ColumnProperties][0][Width]", "122")
      .formParam("layout[ColumnProperties][0][VisibleIndex]", "0")
      .formParam("layout[ColumnProperties][0][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][0][FieldName]", "Employee No.")
      .formParam("layout[ColumnProperties][0][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][0][FieldCaption]", "Employee No.")
      .formParam("layout[ColumnProperties][0][FieldType]", "")
      .formParam("layout[ColumnProperties][1][Visible]", "true")
      .formParam("layout[ColumnProperties][1][Width]", "249")
      .formParam("layout[ColumnProperties][1][VisibleIndex]", "1")
      .formParam("layout[ColumnProperties][1][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][1][FieldName]", "Employee Name")
      .formParam("layout[ColumnProperties][1][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][1][FieldCaption]", "Employee Name")
      .formParam("layout[ColumnProperties][1][FieldType]", "")
      .formParam("layout[ColumnProperties][2][Visible]", "true")
      .formParam("layout[ColumnProperties][2][Width]", "193")
      .formParam("layout[ColumnProperties][2][VisibleIndex]", "2")
      .formParam("layout[ColumnProperties][2][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][2][FieldName]", "Position")
      .formParam("layout[ColumnProperties][2][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][2][FieldCaption]", "Position")
      .formParam("layout[ColumnProperties][2][FieldType]", "")
      .formParam("layout[ColumnProperties][3][Visible]", "true")
      .formParam("layout[ColumnProperties][3][Width]", "187")
      .formParam("layout[ColumnProperties][3][VisibleIndex]", "3")
      .formParam("layout[ColumnProperties][3][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][3][FieldName]", "Grade")
      .formParam("layout[ColumnProperties][3][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][3][FieldCaption]", "Grade")
      .formParam("layout[ColumnProperties][3][FieldType]", "")
      .formParam("layout[ColumnProperties][4][Visible]", "true")
      .formParam("layout[ColumnProperties][4][Width]", "211")
      .formParam("layout[ColumnProperties][4][VisibleIndex]", "4")
      .formParam("layout[ColumnProperties][4][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][4][FieldName]", "Category")
      .formParam("layout[ColumnProperties][4][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][4][FieldCaption]", "Category")
      .formParam("layout[ColumnProperties][4][FieldType]", "")
      .formParam("layout[ColumnProperties][5][Visible]", "true")
      .formParam("layout[ColumnProperties][5][Width]", "115")
      .formParam("layout[ColumnProperties][5][VisibleIndex]", "5")
      .formParam("layout[ColumnProperties][5][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][5][FieldName]", "Hire Date")
      .formParam("layout[ColumnProperties][5][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][5][FieldCaption]", "Hire Date")
      .formParam("layout[ColumnProperties][5][FieldType]", "")
      .formParam("layout[ColumnProperties][6][Visible]", "true")
      .formParam("layout[ColumnProperties][6][Width]", "100")
      .formParam("layout[ColumnProperties][6][VisibleIndex]", "6")
      .formParam("layout[ColumnProperties][6][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][6][FieldName]", "Termination Date")
      .formParam("layout[ColumnProperties][6][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][6][FieldCaption]", "Termination Date")
      .formParam("layout[ColumnProperties][6][FieldType]", "")
      .formParam("layout[ColumnProperties][7][Visible]", "true")
      .formParam("layout[ColumnProperties][7][Width]", "256")
      .formParam("layout[ColumnProperties][7][VisibleIndex]", "7")
      .formParam("layout[ColumnProperties][7][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][7][FieldName]", "Company")
      .formParam("layout[ColumnProperties][7][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][7][FieldCaption]", "Company")
      .formParam("layout[ColumnProperties][7][FieldType]", "")
      .formParam("layout[ColumnProperties][8][Visible]", "true")
      .formParam("layout[ColumnProperties][8][Width]", "239")
      .formParam("layout[ColumnProperties][8][VisibleIndex]", "8")
      .formParam("layout[ColumnProperties][8][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][8][FieldName]", "Branch")
      .formParam("layout[ColumnProperties][8][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][8][FieldCaption]", "Branch")
      .formParam("layout[ColumnProperties][8][FieldType]", "")
      .formParam("layout[ColumnProperties][9][Visible]", "true")
      .formParam("layout[ColumnProperties][9][Width]", "230")
      .formParam("layout[ColumnProperties][9][VisibleIndex]", "9")
      .formParam("layout[ColumnProperties][9][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][9][FieldName]", "Division")
      .formParam("layout[ColumnProperties][9][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][9][FieldCaption]", "Division")
      .formParam("layout[ColumnProperties][9][FieldType]", "")
      .formParam("layout[ColumnProperties][10][Visible]", "true")
      .formParam("layout[ColumnProperties][10][Width]", "236")
      .formParam("layout[ColumnProperties][10][VisibleIndex]", "10")
      .formParam("layout[ColumnProperties][10][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][10][FieldName]", "Department")
      .formParam("layout[ColumnProperties][10][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][10][FieldCaption]", "Department")
      .formParam("layout[ColumnProperties][10][FieldType]", "")
      .formParam("layout[ColumnProperties][11][Visible]", "true")
      .formParam("layout[ColumnProperties][11][Width]", "237")
      .formParam("layout[ColumnProperties][11][VisibleIndex]", "11")
      .formParam("layout[ColumnProperties][11][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][11][FieldName]", "Section")
      .formParam("layout[ColumnProperties][11][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][11][FieldCaption]", "Section")
      .formParam("layout[ColumnProperties][11][FieldType]", "")
      .formParam("layout[ColumnProperties][12][Visible]", "true")
      .formParam("layout[ColumnProperties][12][Width]", "246")
      .formParam("layout[ColumnProperties][12][VisibleIndex]", "12")
      .formParam("layout[ColumnProperties][12][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][12][FieldName]", "Units")
      .formParam("layout[ColumnProperties][12][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][12][FieldCaption]", "Units")
      .formParam("layout[ColumnProperties][12][FieldType]", "")
      .formParam("layout[ColumnProperties][13][Visible]", "true")
      .formParam("layout[ColumnProperties][13][Width]", "124")
      .formParam("layout[ColumnProperties][13][VisibleIndex]", "13")
      .formParam("layout[ColumnProperties][13][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][13][FieldName]", "Leave")
      .formParam("layout[ColumnProperties][13][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][13][FieldCaption]", "Leave")
      .formParam("layout[ColumnProperties][13][FieldType]", "")
      .formParam("layout[ColumnProperties][14][Visible]", "true")
      .formParam("layout[ColumnProperties][14][Width]", "276")
      .formParam("layout[ColumnProperties][14][VisibleIndex]", "14")
      .formParam("layout[ColumnProperties][14][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][14][FieldName]", "Description")
      .formParam("layout[ColumnProperties][14][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][14][FieldCaption]", "Description")
      .formParam("layout[ColumnProperties][14][FieldType]", "")
      .formParam("layout[ColumnProperties][15][Visible]", "true")
      .formParam("layout[ColumnProperties][15][Width]", "100")
      .formParam("layout[ColumnProperties][15][VisibleIndex]", "15")
      .formParam("layout[ColumnProperties][15][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][15][FieldName]", "Total Alloted")
      .formParam("layout[ColumnProperties][15][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][15][FieldCaption]", "Total Alloted")
      .formParam("layout[ColumnProperties][15][FieldType]", "")
      .formParam("layout[ColumnProperties][16][Visible]", "true")
      .formParam("layout[ColumnProperties][16][Width]", "127")
      .formParam("layout[ColumnProperties][16][VisibleIndex]", "16")
      .formParam("layout[ColumnProperties][16][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][16][FieldName]", "Escalation Level")
      .formParam("layout[ColumnProperties][16][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][16][FieldCaption]", "Escalation Level")
      .formParam("layout[ColumnProperties][16][FieldType]", "")
      .formParam("layout[ColumnProperties][17][Visible]", "true")
      .formParam("layout[ColumnProperties][17][Width]", "157")
      .formParam("layout[ColumnProperties][17][VisibleIndex]", "17")
      .formParam("layout[ColumnProperties][17][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][17][FieldName]", "Superior 1 No.")
      .formParam("layout[ColumnProperties][17][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][17][FieldCaption]", "Superior 1 No.")
      .formParam("layout[ColumnProperties][17][FieldType]", "")
      .formParam("layout[ColumnProperties][18][Visible]", "true")
      .formParam("layout[ColumnProperties][18][Width]", "236")
      .formParam("layout[ColumnProperties][18][VisibleIndex]", "18")
      .formParam("layout[ColumnProperties][18][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][18][FieldName]", "Superior 1 Name")
      .formParam("layout[ColumnProperties][18][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][18][FieldCaption]", "Superior 1 Name")
      .formParam("layout[ColumnProperties][18][FieldType]", "")
      .formParam("layout[ColumnProperties][19][Visible]", "true")
      .formParam("layout[ColumnProperties][19][Width]", "216")
      .formParam("layout[ColumnProperties][19][VisibleIndex]", "19")
      .formParam("layout[ColumnProperties][19][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][19][FieldName]", "Superior 1 Position")
      .formParam("layout[ColumnProperties][19][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][19][FieldCaption]", "Superior 1 Position")
      .formParam("layout[ColumnProperties][19][FieldType]", "")
      .formParam("layout[ColumnProperties][20][Visible]", "true")
      .formParam("layout[ColumnProperties][20][Width]", "159")
      .formParam("layout[ColumnProperties][20][VisibleIndex]", "20")
      .formParam("layout[ColumnProperties][20][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][20][FieldName]", "Superior 2 No.")
      .formParam("layout[ColumnProperties][20][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][20][FieldCaption]", "Superior 2 No.")
      .formParam("layout[ColumnProperties][20][FieldType]", "")
      .formParam("layout[ColumnProperties][21][Visible]", "true")
      .formParam("layout[ColumnProperties][21][Width]", "230")
      .formParam("layout[ColumnProperties][21][VisibleIndex]", "21")
      .formParam("layout[ColumnProperties][21][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][21][FieldName]", "Superior 2 Name")
      .formParam("layout[ColumnProperties][21][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][21][FieldCaption]", "Superior 2 Name")
      .formParam("layout[ColumnProperties][21][FieldType]", "")
      .formParam("layout[ColumnProperties][22][Visible]", "true")
      .formParam("layout[ColumnProperties][22][Width]", "226")
      .formParam("layout[ColumnProperties][22][VisibleIndex]", "22")
      .formParam("layout[ColumnProperties][22][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][22][FieldName]", "Superior 2 Position")
      .formParam("layout[ColumnProperties][22][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][22][FieldCaption]", "Superior 2 Position")
      .formParam("layout[ColumnProperties][22][FieldType]", "")
      .formParam("layout[ColumnProperties][23][Visible]", "true")
      .formParam("layout[ColumnProperties][23][Width]", "132")
      .formParam("layout[ColumnProperties][23][VisibleIndex]", "23")
      .formParam("layout[ColumnProperties][23][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][23][FieldName]", "Superior 3 No.")
      .formParam("layout[ColumnProperties][23][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][23][FieldCaption]", "Superior 3 No.")
      .formParam("layout[ColumnProperties][23][FieldType]", "")
      .formParam("layout[ColumnProperties][24][Visible]", "true")
      .formParam("layout[ColumnProperties][24][Width]", "234")
      .formParam("layout[ColumnProperties][24][VisibleIndex]", "24")
      .formParam("layout[ColumnProperties][24][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][24][FieldName]", "Superior 3 Name")
      .formParam("layout[ColumnProperties][24][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][24][FieldCaption]", "Superior 3 Name")
      .formParam("layout[ColumnProperties][24][FieldType]", "")
      .formParam("layout[ColumnProperties][25][Visible]", "true")
      .formParam("layout[ColumnProperties][25][Width]", "212")
      .formParam("layout[ColumnProperties][25][VisibleIndex]", "25")
      .formParam("layout[ColumnProperties][25][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][25][FieldName]", "Superior 3 Position")
      .formParam("layout[ColumnProperties][25][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][25][FieldCaption]", "Superior 3 Position")
      .formParam("layout[ColumnProperties][25][FieldType]", "")
      .formParam("layout[ColumnProperties][26][Visible]", "true")
      .formParam("layout[ColumnProperties][26][Width]", "130")
      .formParam("layout[ColumnProperties][26][VisibleIndex]", "38")
      .formParam("layout[ColumnProperties][26][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][26][FieldName]", "Superior 4 No.")
      .formParam("layout[ColumnProperties][26][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][26][FieldCaption]", "Superior 4 No.")
      .formParam("layout[ColumnProperties][26][FieldType]", "")
      .formParam("layout[ColumnProperties][27][Visible]", "true")
      .formParam("layout[ColumnProperties][27][Width]", "223")
      .formParam("layout[ColumnProperties][27][VisibleIndex]", "39")
      .formParam("layout[ColumnProperties][27][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][27][FieldName]", "Superior 4 Name")
      .formParam("layout[ColumnProperties][27][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][27][FieldCaption]", "Superior 4 Name")
      .formParam("layout[ColumnProperties][27][FieldType]", "")
      .formParam("layout[ColumnProperties][28][Visible]", "true")
      .formParam("layout[ColumnProperties][28][Width]", "199")
      .formParam("layout[ColumnProperties][28][VisibleIndex]", "40")
      .formParam("layout[ColumnProperties][28][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][28][FieldName]", "Superior 4 Position")
      .formParam("layout[ColumnProperties][28][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][28][FieldCaption]", "Superior 4 Position")
      .formParam("layout[ColumnProperties][28][FieldType]", "")
      .formParam("layout[ColumnProperties][29][Visible]", "true")
      .formParam("layout[ColumnProperties][29][Width]", "138")
      .formParam("layout[ColumnProperties][29][VisibleIndex]", "42")
      .formParam("layout[ColumnProperties][29][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][29][FieldName]", "Superior 5 No.")
      .formParam("layout[ColumnProperties][29][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][29][FieldCaption]", "Superior 5 No.")
      .formParam("layout[ColumnProperties][29][FieldType]", "")
      .formParam("layout[ColumnProperties][30][Visible]", "true")
      .formParam("layout[ColumnProperties][30][Width]", "220")
      .formParam("layout[ColumnProperties][30][VisibleIndex]", "43")
      .formParam("layout[ColumnProperties][30][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][30][FieldName]", "Superior 5 Name")
      .formParam("layout[ColumnProperties][30][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][30][FieldCaption]", "Superior 5 Name")
      .formParam("layout[ColumnProperties][30][FieldType]", "")
      .formParam("layout[ColumnProperties][31][Visible]", "true")
      .formParam("layout[ColumnProperties][31][Width]", "198")
      .formParam("layout[ColumnProperties][31][VisibleIndex]", "44")
      .formParam("layout[ColumnProperties][31][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][31][FieldName]", "Superior 5 Position")
      .formParam("layout[ColumnProperties][31][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][31][FieldCaption]", "Superior 5 Position")
      .formParam("layout[ColumnProperties][31][FieldType]", "")
      .formParam("layout[ColumnProperties][32][Visible]", "false")
      .formParam("layout[ColumnProperties][32][Width]", "100")
      .formParam("layout[ColumnProperties][32][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][32][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][32][FieldName]", "customer_code")
      .formParam("layout[ColumnProperties][32][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][32][FieldCaption]", "customer_code")
      .formParam("layout[ColumnProperties][32][FieldType]", "R")
      .formParam("layout[ColumnProperties][33][Visible]", "false")
      .formParam("layout[ColumnProperties][33][Width]", "100")
      .formParam("layout[ColumnProperties][33][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][33][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][33][FieldName]", "location_id")
      .formParam("layout[ColumnProperties][33][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][33][FieldCaption]", "location_id")
      .formParam("layout[ColumnProperties][33][FieldType]", "R")
      .formParam("layout[ColumnProperties][34][Visible]", "false")
      .formParam("layout[ColumnProperties][34][Width]", "100")
      .formParam("layout[ColumnProperties][34][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][34][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][34][FieldName]", "employee_id")
      .formParam("layout[ColumnProperties][34][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][34][FieldCaption]", "employee_id")
      .formParam("layout[ColumnProperties][34][FieldType]", "R")
      .formParam("layout[ColumnProperties][35][Visible]", "false")
      .formParam("layout[ColumnProperties][35][Width]", "100")
      .formParam("layout[ColumnProperties][35][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][35][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][35][FieldName]", "id")
      .formParam("layout[ColumnProperties][35][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][35][FieldCaption]", "id")
      .formParam("layout[ColumnProperties][35][FieldType]", "R")
      .formParam("layout[ColumnProperties][36][Visible]", "false")
      .formParam("layout[ColumnProperties][36][Width]", "100")
      .formParam("layout[ColumnProperties][36][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][36][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][36][FieldName]", "Entity")
      .formParam("layout[ColumnProperties][36][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][36][FieldCaption]", "Entity")
      .formParam("layout[ColumnProperties][36][FieldType]", "R")
      .formParam("layout[ColumnProperties][37][Visible]", "false")
      .formParam("layout[ColumnProperties][37][Width]", "100")
      .formParam("layout[ColumnProperties][37][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][37][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][37][FieldName]", "Leave Year")
      .formParam("layout[ColumnProperties][37][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][37][FieldCaption]", "Leave Year")
      .formParam("layout[ColumnProperties][37][FieldType]", "R")
      .formParam("layout[ColumnProperties][38][Visible]", "false")
      .formParam("layout[ColumnProperties][38][Width]", "100")
      .formParam("layout[ColumnProperties][38][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][38][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][38][FieldName]", "Gender")
      .formParam("layout[ColumnProperties][38][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][38][FieldCaption]", "Gender")
      .formParam("layout[ColumnProperties][38][FieldType]", "R")
      .formParam("layout[ColumnProperties][39][Visible]", "false")
      .formParam("layout[ColumnProperties][39][Width]", "100")
      .formParam("layout[ColumnProperties][39][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][39][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][39][FieldName]", "esacalation_level")
      .formParam("layout[ColumnProperties][39][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][39][FieldCaption]", "esacalation_level")
      .formParam("layout[ColumnProperties][39][FieldType]", "R")
      .formParam("layout[ColumnProperties][40][Visible]", "false")
      .formParam("layout[ColumnProperties][40][Width]", "100")
      .formParam("layout[ColumnProperties][40][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][40][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][40][FieldName]", "superior1_superiorno")
      .formParam("layout[ColumnProperties][40][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][40][FieldCaption]", "superior1_superiorno")
      .formParam("layout[ColumnProperties][40][FieldType]", "R")
      .formParam("layout[ColumnProperties][41][Visible]", "false")
      .formParam("layout[ColumnProperties][41][Width]", "100")
      .formParam("layout[ColumnProperties][41][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][41][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][41][FieldName]", "leave_to")
      .formParam("layout[ColumnProperties][41][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][41][FieldCaption]", "leave_to")
      .formParam("layout[ColumnProperties][41][FieldType]", "R")
      .formParam("layout[ColumnProperties][42][Visible]", "false")
      .formParam("layout[ColumnProperties][42][Width]", "100")
      .formParam("layout[ColumnProperties][42][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][42][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][42][FieldName]", "superior2_superiorno")
      .formParam("layout[ColumnProperties][42][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][42][FieldCaption]", "superior2_superiorno")
      .formParam("layout[ColumnProperties][42][FieldType]", "R")
      .formParam("layout[ColumnProperties][43][Visible]", "false")
      .formParam("layout[ColumnProperties][43][Width]", "100")
      .formParam("layout[ColumnProperties][43][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][43][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][43][FieldName]", "superior3_superiorno")
      .formParam("layout[ColumnProperties][43][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][43][FieldCaption]", "superior3_superiorno")
      .formParam("layout[ColumnProperties][43][FieldType]", "R")
      .formParam("layout[ColumnProperties][44][Visible]", "false")
      .formParam("layout[ColumnProperties][44][Width]", "100")
      .formParam("layout[ColumnProperties][44][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][44][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][44][FieldName]", "superior4_superiorno")
      .formParam("layout[ColumnProperties][44][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][44][FieldCaption]", "superior4_superiorno")
      .formParam("layout[ColumnProperties][44][FieldType]", "R")
      .formParam("layout[ColumnProperties][45][Visible]", "false")
      .formParam("layout[ColumnProperties][45][Width]", "100")
      .formParam("layout[ColumnProperties][45][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][45][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][45][FieldName]", "superior5_superiorno")
      .formParam("layout[ColumnProperties][45][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][45][FieldCaption]", "superior5_superiorno")
      .formParam("layout[ColumnProperties][45][FieldType]", "R")
      .formParam("layout[GridViewCellStyle][FontSize]", "14")
      .formParam("layout[GridViewExportCellStyle][FontSize]", "14")
      .formParam("layout[ShowGroupSummary]", "False")
      .formParam("layout[ShowTotalSummary]", "False")
      .formParam("layout[GroupSummaryTitleFormat]", "{0}:{1}")
      .formParam("layout[GroupHeaderColumnCount]", "0")
      .formParam("layout[RepeatReportHeader]", "False")
      .formParam("layout[ReportHeaderPageBreak]", "")
      .formParam("layout[ColumnGropingLevelCount]", "0")
      .formParam("layout[RepeatColumnHeader]", "False")
      .formParam("layout[HideDetails]", "False")
      .formParam("TemplateId", "135")
      .formParam("ReportId", "108")
      .check(bodyString.saveAs("ReportViewer"))
    )
      .pause(476.milliseconds)
      .exec(http("request_90")
        .get("/DXR.axd?r=24_367-8RXkk")
      )
  }
  def logout = {
    exec(http("Logout")
      .post("/Account/LogOff")

      .formParam("__RequestVerificationToken", "${__RequestVerificationTokenLogout}")
      .formParam("DXScript", "1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_270,1_286,1_289,1_183,17_42,17_3,1_285,1_188,17_8,1_297,1_192,17_10,1_287,1_194,1_193,17_11,1_208,1_216,1_301,1_253,1_234,1_246,1_302,1_221,17_12,1_296,1_295,1_278,17_41,1_189,1_222,1_290,1_288,1_195,1_255,1_262,1_261,1_254,1_251,1_258,1_252,1_260,1_257,1_256,1_247,1_243,1_241,1_250,1_249,1_248,1_245,1_244,1_259,1_240,1_237,1_238,1_239,1_242,17_15,17_17,1_271,1_272,17_19,1_273,1_274,17_20,17_21,1_223,17_14,1_276,17_24,17_28,1_280,17_25,1_293,17_27,1_291,1_294,17_32,1_298,17_36,17_40,1_197,17_1,1_207,1_235,17_16,6_18,6_16,6_15,6_14,6_17,17_39,1_212,1_196,17_0,1_198,17_2,1_199,17_4,1_200,1_201,1_202,1_204,1_218,1_205,17_7,1_211,17_23,1_206,17_9,1_275,1_214,1_215,17_22,1_213,1_217,17_38,1_219,1_232,1_233,1_231,17_5,1_191,1_284,18_36,18_38,18_33,18_42,18_37,18_35,17_31,1_203,1_283,9_54,9_55,24_379,24_389,9_57,9_56,17_44,9_45,9_47,9_46,17_30,9_51,9_48,9_31,17_29,9_50,9_41,9_53,9_52,9_49")
      .formParam("DXCss", "/Content/css/root?v=fQqb8rdb3SX3t_q5clLhrjqLMPJRz5XyrffvnRHeaqY1,0_2312,1_50,1_53,1_51,0_2317,1_40,1_17,0_2214,1_16,0_2219,0_2221,0_2225,1_18,1_4,0_2279,6_3,0_2283,0_2186,0_2190,0_2257,18_3,18_11,18_7,0_2261,0_2313,1_34,24_359,24_364,24_360,9_19,9_15,9_12,0_2338,9_1,0_2342,9_4,1_7,/Content/ExecutiveDashboard/ExecutiveDashboardBundle?v=K3bp7bOUCg7jvMi3yCOp8VvRDHaxkZJNkgNJYDsPeIA1,/Content/ExecutiveDashboardBundle?v=yudLVP8cmmFF7pYfIl5_OmdH-W3uaCGxdSLyC-jbYQo1,/Content/notifications.css,/Content/jquery-ui.css,/Content/PayrollProcess.css")
      .check(status.is(302)))
      .exec(http("request_114")
        .get("/Account/Login")
      )
      .exec(http("request_115")
        .get("/DXR.axd?r=1_58-lUXkk")
      )
      .exec(http("request_116")
        .get("/Content/css?v=w9USDPGryprQSMA62T1giyRXrtqAIG-BphxyQY0Qw_w1")
      )
      .exec(http("request_117")
        .get("/DXR.axd?r=1_17,0_2214,1_50,1_53,1_51,1_16,0_2219,0_2312,0_2317-4WXkk")
      )
      .exec(http("request_118")
        .get("/DXR.axd?r=1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_208,1_216,1_212,1_189,1_222,17_42,1_297,1_215,1_207,1_289,1_205,17_7,1_287,1_211,17_23,1_197,17_1-lUXkk")
      )
      .exec(http("request_119")
        .get("/bundles/jquery?v=w1vknpWt6KqlZcHeJQvaK6VbvvXt1Go8HcGH_DqKzzo1")
      )
      .exec(http("request_120")
        .get("/Content/fonts/icomoon.ttf?5vru0d")
      )
      .pause(133.milliseconds)
      .exec(http("request_121")
        .get("/Content/Images/bg-login.jpg?V=03")
      )
  }
}
