package computerdatabase.Module.Profile

import io.gatling.core.Predef._
import io.gatling.http.Predef._

import scala.concurrent.duration._

object ESSEMPMyProfile {


  val uri1 = "https://maps.googleapis.com/maps/api/js"
  val uri3 = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2"
  val uri4 = "https://fonts.googleapis.com/css"

    def loadApplication = {
      exec(http("Employee Profile Page")
        .get("/profile/emp_profile.aspx")
        .check(bodyString.saveAs("EmpProfile"))
        .check(regex("""<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="(|.+?)" />""").saveAs("viewState"))
      )
        .exec(http("request_54")
          .get("/DXR.axd?r=1_58-lUXkk")
        )
        .exec(http("request_55")
          .get("/DXR.axd?r=0_2312,1_50,1_53,1_51,0_2317-4WXkk")
        )
        .pause(178.milliseconds)
        .exec(http("request_56")
          .get(uri4 + "?family=Open+Sans:300,400,600,700")
        )
        .exec(http("request_57")
          .get(uri4 + "?family=Roboto:400,300,500,700")
        )
        .exec(http("request_58")
          .get("/WebResource.axd?d=G7AEkw1asyYfSFk2Li5D0JhwAppflyxkpGSQDQbA3YX7Us59q1SeSvJlGoBadgH42WWogzokgjSTil628NjzJ-ho-6akTSnjNL_1W4rKMdV6J4E7SFdllL-EXlbUGTEk-wfRgTKBSFluXwws9OgQSz64mOsqxEoa9Z9MfmluHcdALHev8eL9dk6DjmuJdzHl0&t=637182269363078774")
        )
        .exec(http("request_59")
          .get("/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZOYXOnLy43dRx8HCf3vqtm7Uk9Dd5QTT0bKPZkChPJpkGd7et7925jgqVFYijtH4BlZm86YPMFKavMb3jiNdHO_DkODjc9ASxqTpYjlOyMlE0&t=637505973787431984")
        )
        .exec(http("request_60")
          .get("/ScriptResource.axd?d=nv7asgRUU0tRmHNR2D6t1HncJC0uSlzSoOMFzQL9KDgdtj1yUByaaYlMWCLR1tfb0zRr2KS8GU92MXS6P0lOX_vkDPQOiW6UvV384GibJ__q8DVUhGPtg7X0IEAXecIS6jMaZIGfhYY2bHennMwScvTacu4aYi7pwkjCfDx4XDhghn49oiHENcEjRtCYLFUt0&t=fffffffff6474071")
        )
        .exec(http("request_61")
          .get("/ScriptResource.axd?d=x6wALODbMJK5e0eRC_p1LTFBEqAduy6yzdGuAMP1dHrya3_IF2A8CsbaRF-ARwHq6m-SGT1rW_kEfDOVxpLiOwBwjQzZMYd6yIJvZ9ubgIyIzxTTWWPxLOJ6h2brQiXEeYW7vHWkdtbfdWvIHio91FSsDXmcUmI7kjdMETOH_XE1&t=51e37521")
        )
        .exec(http("request_62")
          .get("/ScriptResource.axd?d=P5lTttoqSeZXoYRLQMIScIf12FcrWAiNVtlJxQA9qnTW6iJpMmht7uXNg23QNwOPVke9qF6NTd062q-kq39p4MmkxhZ1ti3ckmNVSJHDik9HIeiTEBJ8AeazBYyjXlRbQWV2Q8-MBT7ldJqGwC6gtX5XcIt2Wd4nEFDQxuD-poI1&t=51e37521")
        )
        .exec(http("request_63")
          .get("/ScriptResource.axd?d=XGoPW3Unw0ILT0eb9sSUayB1PCvz0eeMXm23ajXUnLKSVWvpEIM7qNdgqQtwIk3oGSO-umSPRJr1BQNhALudg4-gDqI9ltlNkOQMrPf4fNHBEAhja6GHf4He4_YSEbkQ4L1Bsn1aV_AF11ks4fQlTNxlg6tYk_UGpXjfNcFSD6D49VS2gjNTnElk4fHlLsM90&t=51e37521")
        )
        .exec(http("request_64")
          .get("/ScriptResource.axd?d=uvA9ANM76Fbpm1FfUlagnYp2obqkhmwI_C-NoQ89dB6TwrO7THFVAk1nHl1QRi68J_pozjXYUJHgZb6l02O3dvVqjaOzdIW44mTvv4FyAQ5MvnVeKZmB7OtG9BNkATLGOGWXvK2djBpsGpZ_x3Mi2KdwGSD0SZeW5VvD940G1Y8Cml0nm6ok2UFWSXa6k4SQ0&t=51e37521")
        )
        .exec(http("request_65")
          .post("/verify_access.ashx")
        )
        .exec(http("request_66")
          .get("/profile/emp_profile.aspx?_TSM_CombinedScripts_=True&v=ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1&_TSM_Bundles_=&cdn=False")
        )
        .exec(http("request_67")
          .get("/profile_picture.ashx?Value=_2&EmployeeID=9126")
        )
        .exec(http("request_68")
          .get("/DXR.axd?r=1_303,1_184,1_297,1_210,1_220,1_187,1_181,1_289,1_287-lUXkk")
        )
        .exec(http("request_69")
          .get("/DXR.axd?r=1_58-lUXkk")
        )
        .exec(http("request_70")
          .get("/Content/ESS/fonts/icomoon.ttf?5vru0d")
        )
        .exec(http("request_71")
          .get("/Notifications/GetNotificationCounts")
        )
        .exec(http("request_72")
          .get("/Account/VerifyAccess")
        )
        .exec(http("request_73")
          .get("/Notifications/ViewNotifications?type=Qxp99rnLgiJq6Y0s/UmfwyGvkE28g0zAjpzjr+xsjx9iw5JnoAiGOsatokAvs6nHOFupCP0i9sXaLerIxX2nlE2mof+Eosh+V68WQGjD9Y2Y+qGAAEa3odjiA58wSS1A5HT16LATXnopKKvtevZBQDh6cIit43FDMaTRdqQ74LI=")
        )
        .pause(113.milliseconds)
        .exec(http("request_74")
          .get("/Account/VerifyAccess")
        )
        .exec(http("request_75")
          .get("/Notifications/GetNotificationsList?row=8")
        )
        .exec(http("request_76")
          .get(uri3 + "?v=4.7.0")
        )
        .pause(112)
        .exec(http("request_77")
          .get("/DXR.axd?r=0_2312,1_50,1_53,1_51,0_2317-4WXkk")
        )
        .exec(http("request_78")
          .get(uri4 + "?family=Open+Sans:300,400,600,700")
        )
        .exec(http("request_79")
          .get(uri4 + "?family=Roboto:400,300,500,700")
        )
    }

    def submitDetail = {
      exec(http("Submit Detail Profile Page")
        .post("/profile/emp_profile.aspx")

        .formParam("__EVENTTARGET", "")
        .formParam("__EVENTARGUMENT", "")
        .formParam("_TSM_HiddenField_", "${viewStateTable}")
        .formParam("__VIEWSTATE", "")
        .formParam("__VIEWSTATEGENERATOR", "47C6F76C")
        .formParam("ctl00$ctl00$ctl00$selCultureName", "")
        .formParam("ctl00$ctl00$ctl00$selCountry", "1")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$btnEdit", "Edit")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfAttachID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfFileName", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfFileType", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfAttachSrc", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmployeeID", "9126")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSubordinateEmployeeNo", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmployeeNo", "KM00562")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMode", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfPersonalInfoID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmploymentInfoID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMonitorID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfPersonalAgentID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmploymentAgentID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfDataSet", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfGroupInfoID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAgentID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSpouseIDs", "[0],[1]")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfQualificationIDs", "[0]")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfExperienceIDs", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkillIDs", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfStatutoryMYIDs", "[0],[1],[2],[3]")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfViewOnly", "false")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hdnFamilyInfoStatutory", "Yes")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfArea", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfState", "KUL")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMailCountry", "MY")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfPersonalDetailsViewOnly", "false")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFamilyViewOnly", "false")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFamilyControlVisibilitytext", "none")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFamilyLabelVisibilitytext", "block")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfJobParticularsViewOnly", "false")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfQualificationViewOnly", "false")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfQualificationControlVisibilitytext", "none")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfQualificationLabelVisibilitytext", "block")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkillsViewOnly", "false")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkillsControlVisibilitytext", "none")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkillsLabelVisibilitytext", "block")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfExperiencesViewOnly", "false")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfExperiencesControlVisibilitytext", "none")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfExperiencesLabelVisibilitytext", "block")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLabelVisibilitytext", "block")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfControlVisibilitytext", "none")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfDisabledtext", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNewEmployeeName", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNewAgency1NationalID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNewAgency2NationalID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNewAgency3NationalID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvFirstNameEx_ClientState", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvGenderEx_ClientState", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvBirthDateEx_ClientState", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvMaritalStatusEx_ClientState", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtRemarks", "")
        .formParam("hfSpouse_0", "46495")
        .formParam("txtSpouseItemID_0", "46495")
        .formParam("hfSpouseAge_0", "26")
        .formParam("hfSpouseActionType_0", "E")
        .formParam("hfSpouseItemId_0", "46495")
        .formParam("hfSpouseMonitorId_0", "")
        .formParam("hfSpouseAgentId_0", "")
        .formParam("hfSpouseWFItemId_0", "46495")
        .formParam("hfSpouse_1", "37982")
        .formParam("txtSpouseItemID_1", "37982")
        .formParam("hfSpouseAge_1", "63")
        .formParam("hfSpouseActionType_1", "E")
        .formParam("hfSpouseItemId_1", "37982")
        .formParam("hfSpouseMonitorId_1", "")
        .formParam("hfSpouseAgentId_1", "")
        .formParam("hfSpouseWFItemId_1", "37982")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtFamilyWorkflowRemarks", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfIncomeTaxUseOldIC", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfProvidentFundUseOldIC", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSocialSecurityUseOldIC", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtEmploymentWorkflowRemarks", "")
        .formParam("hfQualification_0", "5467")
        .formParam("txtQualificationItemID_0", "5467")
        .formParam("hfDuration_0", "2 Year(s)  11 month(s) ")
        .formParam("hfQualificationActionType_0", "E")
        .formParam("hfQualificationItemId_0", "5467")
        .formParam("hfQualificationMonitorId_0", "")
        .formParam("hfQualificationAgentId_0", "")
        .formParam("hfQualificationWFItemId_0", "5467")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtQualificationWorkflowRemarks", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtSkillWorkflowRemarks", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtExperienceWorkFlowRemarks", "")
        .formParam("hfStatutoryMY_0", "1384")
        .formParam("hfStatutoryMY_1", "13137")
        .formParam("hfStatutoryMY_2", "20990")
        .formParam("hfStatutoryMY_3", "44102")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$popupControlState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("DXScript", "1_303,1_184,1_297,1_210,1_220,1_187,1_181,1_289,1_287")
        .formParam("DXCss", "0_2312,1_50,1_53,1_51,0_2317,../Content/jquery.jscrollpane.css,../Content/ESS/bootstrap.css,../Content/ESS/NewUIStyle.css,../Content/ESS/ResponsiveSite.css,../Content/generic.light.custom.css,../Content/ESS/font-style.css,https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css,../Content/jquery.orgchart.css,../Content/ESS/style.css,../Content/ESS/component.css,../Content/ESS/alert.css,../Content/ESS/custom/jquery-ui-1.10.3.custom.min.css,../Content/jquery.mmenu.css,../Content/notifications.css,/WebResource.axd?d=G7AEkw1asyYfSFk2Li5D0JhwAppflyxkpGSQDQbA3YX7Us59q1SeSvJlGoBadgH42WWogzokgjSTil628NjzJ-ho-6akTSnjNL_1W4rKMdV6J4E7SFdllL-EXlbUGTEk-wfRgTKBSFluXwws9OgQSz64mOsqxEoa9Z9MfmluHcdALHev8eL9dk6DjmuJdzHl0&t=637182269363078774")
        .check(bodyString.saveAs("EmpProfilePage")))
        .exec(http("request_81")
          .get("/WebResource.axd?d=G7AEkw1asyYfSFk2Li5D0JhwAppflyxkpGSQDQbA3YX7Us59q1SeSvJlGoBadgH42WWogzokgjSTil628NjzJ-ho-6akTSnjNL_1W4rKMdV6J4E7SFdllL-EXlbUGTEk-wfRgTKBSFluXwws9OgQSz64mOsqxEoa9Z9MfmluHcdALHev8eL9dk6DjmuJdzHl0&t=637182269363078774")
        )
        .exec(http("request_82")
          .get("/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZOYXOnLy43dRx8HCf3vqtm7Uk9Dd5QTT0bKPZkChPJpkGd7et7925jgqVFYijtH4BlZm86YPMFKavMb3jiNdHO_DkODjc9ASxqTpYjlOyMlE0&t=637505973787431984")
        )
        .exec(http("request_83")
          .get("/ScriptResource.axd?d=nv7asgRUU0tRmHNR2D6t1HncJC0uSlzSoOMFzQL9KDgdtj1yUByaaYlMWCLR1tfb0zRr2KS8GU92MXS6P0lOX_vkDPQOiW6UvV384GibJ__q8DVUhGPtg7X0IEAXecIS6jMaZIGfhYY2bHennMwScvTacu4aYi7pwkjCfDx4XDhghn49oiHENcEjRtCYLFUt0&t=fffffffff6474071")
        )
        .exec(http("request_84")
          .get("/ScriptResource.axd?d=x6wALODbMJK5e0eRC_p1LTFBEqAduy6yzdGuAMP1dHrya3_IF2A8CsbaRF-ARwHq6m-SGT1rW_kEfDOVxpLiOwBwjQzZMYd6yIJvZ9ubgIyIzxTTWWPxLOJ6h2brQiXEeYW7vHWkdtbfdWvIHio91FSsDXmcUmI7kjdMETOH_XE1&t=51e37521")
        )
        .exec(http("request_85")
          .get("/ScriptResource.axd?d=P5lTttoqSeZXoYRLQMIScIf12FcrWAiNVtlJxQA9qnTW6iJpMmht7uXNg23QNwOPVke9qF6NTd062q-kq39p4MmkxhZ1ti3ckmNVSJHDik9HIeiTEBJ8AeazBYyjXlRbQWV2Q8-MBT7ldJqGwC6gtX5XcIt2Wd4nEFDQxuD-poI1&t=51e37521")
        )
        .exec(http("request_86")
          .get("/ScriptResource.axd?d=XGoPW3Unw0ILT0eb9sSUayB1PCvz0eeMXm23ajXUnLKSVWvpEIM7qNdgqQtwIk3oGSO-umSPRJr1BQNhALudg4-gDqI9ltlNkOQMrPf4fNHBEAhja6GHf4He4_YSEbkQ4L1Bsn1aV_AF11ks4fQlTNxlg6tYk_UGpXjfNcFSD6D49VS2gjNTnElk4fHlLsM90&t=51e37521")
        )
        .exec(http("request_87")
          .get("/ScriptResource.axd?d=uvA9ANM76Fbpm1FfUlagnYp2obqkhmwI_C-NoQ89dB6TwrO7THFVAk1nHl1QRi68J_pozjXYUJHgZb6l02O3dvVqjaOzdIW44mTvv4FyAQ5MvnVeKZmB7OtG9BNkATLGOGWXvK2djBpsGpZ_x3Mi2KdwGSD0SZeW5VvD940G1Y8Cml0nm6ok2UFWSXa6k4SQ0&t=51e37521")
        )
        .exec(http("request_88")
          .post("/verify_access.ashx")
        )

        .exec(http("request_89")
          .get("/profile/emp_profile.aspx?_TSM_CombinedScripts_=True&v=ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1&_TSM_Bundles_=&cdn=False")
        )
        .exec(http("request_90")
          .get("/Content/ESS/fonts/icomoon.ttf?5vru0d")
        )
        .exec(http("request_91")
          .get(uri3 + "?v=4.7.0")
        )
        .exec(http("request_92")
          .get("/profile_picture.ashx?Value=_2&EmployeeID=9126")
        )
        .pause(152.milliseconds)
        .exec(http("request_93")
          .get("/DXR.axd?r=1_303,1_184,1_297,1_210,1_220,1_187,1_181,1_289,1_287-lUXkk")
        )
        .exec(http("request_94")
          .get("/DXR.axd?r=1_58-lUXkk")
        )
        .pause(207.milliseconds)
        .exec(http("request_95")
          .get("/Notifications/GetNotificationCounts")
        )
        .exec(http("request_96")
          .get("/Account/VerifyAccess")
        )
        .exec(http("request_97")
          .get("/Notifications/ViewNotifications?type=bhPL3mTIKctMMgk8wGTqOqyDlNB5+FtPlPWcqXApSezjVFgfFYKci10JqgNqgchak7KOZ3PDSYke+X8cLXheTwqD3HS766Day4btpVPHQ0DU6UFj/Jbv8N/XdxYd7gtUWo++0m0xOkeW5Xi2a54EBkyP5qdBTLiIVpaft2I7VWE=")
        )
        .pause(131.milliseconds)
        .exec(http("request_98")
          .get("/Account/VerifyAccess")
        )
        .exec(http("request_99")
          .get("/Notifications/GetNotificationsList?row=8")
        )
        .pause(9)
    }

    def logout = {
      exec(http("Logout Process")
        .post("/profile/emp_profile.aspx")

        .formParam("__EVENTTARGET", "ctl00$ctl00$ctl00$lbLogout")
        .formParam("__EVENTARGUMENT", "")
        .formParam("_TSM_HiddenField_", "${viewState}")
        .formParam("__VIEWSTATE", "")
        .formParam("__VIEWSTATEGENERATOR", "47C6F76C")
        .formParam("ctl00$ctl00$ctl00$selCultureName", "")
        .formParam("ctl00$ctl00$ctl00$selCountry", "1")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfAttachID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfFileName", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfFileType", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfAttachSrc", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmployeeID", "9126")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSubordinateEmployeeNo", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmployeeNo", "KM00562")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMode", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfPersonalInfoID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmploymentInfoID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMonitorID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfPersonalAgentID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmploymentAgentID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfDataSet", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfGroupInfoID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAgentID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSpouseIDs", "[0],[1]")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfQualificationIDs", "[0]")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfExperienceIDs", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkillIDs", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfStatutoryMYIDs", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfViewOnly", "false")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hdnFamilyInfoStatutory", "Yes")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfArea", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfState", "KUL")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMailCountry", "MY")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfPersonalDetailsViewOnly", "false")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFamilyViewOnly", "false")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFamilyControlVisibilitytext", "block")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFamilyLabelVisibilitytext", "none")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfJobParticularsViewOnly", "false")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfQualificationViewOnly", "false")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfQualificationControlVisibilitytext", "block")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfQualificationLabelVisibilitytext", "none")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkillsViewOnly", "false")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkillsControlVisibilitytext", "block")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkillsLabelVisibilitytext", "none")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfExperiencesViewOnly", "false")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfExperiencesControlVisibilitytext", "block")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfExperiencesLabelVisibilitytext", "none")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLabelVisibilitytext", "none")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfControlVisibilitytext", "block")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfDisabledtext", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNewEmployeeName", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNewAgency1NationalID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNewAgency2NationalID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNewAgency3NationalID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtFirstName", "NXX XXX XNI")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvFirstNameEx_ClientState", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtMiddleName", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtLastName", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtLocalName", "NXX XXX XNI")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtNewICNo", "9****68")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtOldICNo", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtPassportNo", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtPassportIssueDate", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtPassportExpiryDate", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selGender", "F")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvGenderEx_ClientState", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtBirthPlace", "KELANTAN")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtBirthDate", "05/06/1990")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvBirthDateEx_ClientState", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selMaritalStatus", "M")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvMaritalStatusEx_ClientState", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selNationality", "MY")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selRace", "MAL")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selReligion", "ISM")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtHeight", "157.00")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtWeight", "45.00")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selBloodGroup", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtDrivingLicense", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtHomeAddress1", "-XX XX XX")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtHomeAddress2", "-XX XX XX")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtHomeAddress3", "-XX XX XX")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtHomePostalCode", "57000")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selHomeArea", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selHomeState", "KUL")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selHomeMailCountry", "MY")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtAddress1", "UXX XX XXMA")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtAddress2", "AXX XX XXTS")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtAddress3", "JXX XX XXAN")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtPostalCode", "57000")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selArea", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selState", "KUL")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selMailCountry", "MY")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtPhone", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtMobile", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtEmail", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtRemarks", "")
        .formParam("hfSpouse_0", "46495")
        .formParam("selSpouseRelationType_0", "SPOU")
        .formParam("txtSpouseName_0", "MXX XXX XEH")
        .formParam("txtSpouseItemID_0", "46495")
        .formParam("txtSpouseBirthDate_0", "01/07/1994")
        .formParam("hfSpouseAge_0", "26")
        .formParam("selSpouseGender_0", "M")
        .formParam("selSpouseNationality_0", "MY")
        .formParam("txtBirthPlace_0", "")
        .formParam("selSpouseMaritalStatus_0", "M")
        .formParam("txtSpouseMarriedDate_0", "14/03/2020")
        .formParam("txtMEDIA_CONTACT1_0", "")
        .formParam("txtNATIONAL_ID1_0", "")
        .formParam("txtPASSPORT_NO_0", "")
        .formParam("txtPASSPORT_EXPIRY_DATE_0", "")
        .formParam("selSpouseHandicapped_0", "0")
        .formParam("txtIncomeTaxNo_0", "")
        .formParam("selSpouseEmployed_0", "1")
        .formParam("selSameEntity_0", "0")
        .formParam("selSpouseEducationLevel_0", "0")
        .formParam("txtTaxRelief_0", "0")
        .formParam("txtSpouseOccupation_0", "")
        .formParam("txtRemarks_0", "")
        .formParam("hfSpouseActionType_0", "E")
        .formParam("hfSpouseItemId_0", "46495")
        .formParam("hfSpouseMonitorId_0", "")
        .formParam("hfSpouseAgentId_0", "")
        .formParam("hfSpouseWFItemId_0", "46495")
        .formParam("hfSpouse_1", "37982")
        .formParam("selSpouseRelationType_1", "PARN")
        .formParam("txtSpouseName_1", "SXX XXX XOH")
        .formParam("txtSpouseItemID_1", "37982")
        .formParam("txtSpouseBirthDate_1", "10/09/1957")
        .formParam("hfSpouseAge_1", "63")
        .formParam("selSpouseGender_1", "F")
        .formParam("selSpouseNationality_1", "MY")
        .formParam("txtBirthPlace_1", "")
        .formParam("selSpouseMaritalStatus_1", "M")
        .formParam("txtSpouseMarriedDate_1", "")
        .formParam("txtMEDIA_CONTACT1_1", "")
        .formParam("txtNATIONAL_ID1_1", "")
        .formParam("txtPASSPORT_NO_1", "")
        .formParam("txtPASSPORT_EXPIRY_DATE_1", "")
        .formParam("selSpouseHandicapped_1", "0")
        .formParam("txtIncomeTaxNo_1", "")
        .formParam("selSpouseEmployed_1", "0")
        .formParam("selSameEntity_1", "0")
        .formParam("selSpouseEducationLevel_1", "")
        .formParam("txtTaxRelief_1", "1")
        .formParam("txtSpouseOccupation_1", "")
        .formParam("txtRemarks_1", "")
        .formParam("hfSpouseActionType_1", "E")
        .formParam("hfSpouseItemId_1", "37982")
        .formParam("hfSpouseMonitorId_1", "")
        .formParam("hfSpouseAgentId_1", "")
        .formParam("hfSpouseWFItemId_1", "37982")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtFamilyWorkflowRemarks", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtOfficePhone", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtOfficeFax", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtOfficeEmail", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtIncomeTaxNo", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtProvidentFundNo", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtSocialSecurityNo", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$SelIncomeTaxUseOldIC", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfIncomeTaxUseOldIC", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selProvidentFundUseOldIC", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfProvidentFundUseOldIC", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selSocialSecurityUseOldIC", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSocialSecurityUseOldIC", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selTaxMaritalStatus", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selTaxBranch", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selTaxArea", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selTaxCategory", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selNormalTaxPaidBy", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selBonusTaxPaidBy", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selTaxHandicapped", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtEmploymentWorkflowRemarks", "")
        .formParam("hfQualification_0", "5467")
        .formParam("selCertificate_0", "DEGR")
        .formParam("txtQualificationItemID_0", "5467")
        .formParam("txtCollege_0", "UNIVERSITI PUTRA MALAYSIA")
        .formParam("txtHighestLevel_0", "Yes")
        .formParam("selClass_0", "NA")
        .formParam("txtScore_0", "0.00")
        .formParam("txtInstitutionCode_0", "NA")
        .formParam("txtFacultyCode_0", "NA")
        .formParam("txtCertificateNo_0", "")
        .formParam("txtFromDate_0", "01/10/2010")
        .formParam("txtToDate_0", "30/09/2013")
        .formParam("hfDuration_0", "2 Year(s)  11 month(s) ")
        .formParam("txtQualificationRemarks_0", "BACHELOR BUSINESS ADMINISTRATION IN HUMAN RESOURCE MANAGEMENT")
        .formParam("hfQualificationActionType_0", "E")
        .formParam("hfQualificationItemId_0", "5467")
        .formParam("hfQualificationMonitorId_0", "")
        .formParam("hfQualificationAgentId_0", "")
        .formParam("hfQualificationWFItemId_0", "5467")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtQualificationWorkflowRemarks", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtSkillWorkflowRemarks", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtExperienceWorkFlowRemarks", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$popupControlState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("DXScript", "1_303,1_184,1_297,1_210,1_220,1_187,1_181,1_289,1_287")
        .formParam("DXCss", "0_2312,1_50,1_53,1_51,0_2317,../Content/jquery.jscrollpane.css,../Content/ESS/bootstrap.css,../Content/ESS/NewUIStyle.css,../Content/ESS/ResponsiveSite.css,../Content/generic.light.custom.css,../Content/ESS/font-style.css,https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css,../Content/jquery.orgchart.css,../Content/ESS/style.css,../Content/ESS/component.css,../Content/ESS/alert.css,../Content/ESS/custom/jquery-ui-1.10.3.custom.min.css,../Content/jquery.mmenu.css,../Content/notifications.css,/WebResource.axd?d=G7AEkw1asyYfSFk2Li5D0JhwAppflyxkpGSQDQbA3YX7Us59q1SeSvJlGoBadgH42WWogzokgjSTil628NjzJ-ho-6akTSnjNL_1W4rKMdV6J4E7SFdllL-EXlbUGTEk-wfRgTKBSFluXwws9OgQSz64mOsqxEoa9Z9MfmluHcdALHev8eL9dk6DjmuJdzHl0&t=637182269363078774")
        .check(status.is(302))
        .check(bodyString.saveAs("Logout")))
        .exec(http("Login - After Logout")
          .get("/Account/Login")
        )
        .exec(http("request_102")
          .get("/DXR.axd?r=1_58-lUXkk")
        )
        .exec(http("request_103")
          .get("/Content/css?v=w9USDPGryprQSMA62T1giyRXrtqAIG-BphxyQY0Qw_w1")
        )
        .exec(http("request_104")
          .get("/DXR.axd?r=1_17,0_2214,1_50,1_53,1_51,1_16,0_2219,0_2312,0_2317-4WXkk")
        )
        .exec(http("request_105")
          .get("/DXR.axd?r=1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_208,1_216,1_212,1_189,1_222,17_42,1_297,1_215,1_207,1_289,1_205,17_7,1_287,1_211,17_23,1_197,17_1-lUXkk")
        )
        .exec(http("request_106")
          .get("/bundles/jquery?v=w1vknpWt6KqlZcHeJQvaK6VbvvXt1Go8HcGH_DqKzzo1")
        )
        .pause(114.milliseconds)
        .exec(http("request_107")
          .get("/Content/Images/bg-login.jpg?V=03")
        )
        .exec(http("request_108")
          .get("/Content/fonts/icomoon.ttf?5vru0d")
        )
    }



}
