package computerdatabase.Module.Profile.Report
import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._

object EmployeeMovementReport {

  val uri1 = "https://maps.googleapis.com/maps/api/js"
  val uri3 = "https://fonts.googleapis.com/css"

  def loadMovementReport = {
    exec(http("Load Movement Report")
      .get("/CustomReport/ReportViewerDisplay/EmployeeMovementReport")
      .check(regex("""<input name="__RequestVerificationToken" type="hidden" value="(.+?)" />""").find.saveAs("__RequestVerificationTokenLogout"))
      .check(bodyString.saveAs("BodyCriteria"))
    )
      .exec(http("request_59")
        .get("/bundles/jquery?v=w1vknpWt6KqlZcHeJQvaK6VbvvXt1Go8HcGH_DqKzzo1")
      )
      .pause(120.milliseconds)
      .exec(http("request_60")
        .get("/Content/fonts/icomoon.ttf?5vru0d")
      )
      .exec(http("request_61")
        .get("/Scripts/ExecutiveDashboardBundle?v=DMMQIR-OxHUTpie3SbH9hPNfqqge6hNdl_5G39s54KA1")
      )
      .exec(http("request_62")
        .get("/Scripts/ExecutiveDashboardBundle/SideMenu?v=wmt4mX4cYH0d844GQc8r_NWCLWWdnZ_egKD54y34J2U1")
      )
      .exec(http("request_63")
        .get("/bundles/bootstrap?v=2Fz3B0iizV2NnnamQFrx-NbYJNTFeBJ2GM05SilbtQU1")
      )
      .exec(http("request_64")
        .get("/Scripts/MasterDevExBundle?v=yx5tJIYhtWXcJGGiFMJ_bRJ0-eldYrvLrqRE_KNFrnI1")
      )
      .exec(http("request_65")
        .get("/signalr/hubs")
      )
      .exec(http("request_66")
        .get("/DXR.axd?r=1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_270,1_286,1_289,1_183,17_42,17_3,1_285,1_188,17_8,1_297,1_192,17_10,1_287,1_194,1_193,17_11,1_208,1_216,1_301,1_253,1_234,1_246,1_302,1_221,17_12,1_296,1_295,1_278,17_41,1_189,1_222,1_290,1_288,1_195,1_255,1_262,1_261,1_254,1_251,1_258,1_252,1_260,1_257,1_256,1_247,1_243,1_241,1_250,1_249,1_248,1_245,1_244,1_259,1_240,1_237,1_238,1_239,1_242,17_15,17_17,1_271,1_272,17_19,1_273,1_274,17_20,17_21,1_223,17_14,1_276,17_24,17_28,1_280,17_25,1_293,17_27,1_291,1_294,17_32,1_298,17_36,17_40,1_197,17_1,1_207,1_235,17_16,6_18,6_16,6_15,6_14,6_17,17_39,1_212,1_196,17_0,1_198,17_2,1_199,17_4,1_200,1_201,1_202,1_204,1_218,1_205,17_7,1_211,17_23,1_206,17_9,1_275,1_214,1_215,17_22,1_213,1_217,17_38,1_219,1_232,1_233,1_231,17_5,1_191,1_284,18_36,18_38,18_33,18_42,18_37,18_35,17_31,1_203,1_283,9_54,9_55,24_379,24_389,9_57,9_56,17_44,9_45,9_47,9_46,17_30,9_51,9_48,9_31,17_29,9_50,9_41,9_53,9_52,9_49-WYXkk&p=b691a7d7")
      )
      .pause(629.milliseconds)
      .exec(http("request_67")
        .get("/Content/Images/unifiedhcms_logo.png?V=01")
      )
      .exec(http("request_68")
        .get("/DXR.axd?r=1_58-lUXkk")
      )
      .exec(http("request_69")
        .get("/profile_picture.ashx?EmployeeID=7317")
      )
      .pause(129.milliseconds)
      .exec(http("request_70")
        .get(uri1 + "?key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A")
      )
      .exec(http("request_71")
        .get("/DXR.axd?r=0_2314-4WXkk")
      )
      .exec(http("request_72")
        .get("/DXR.axd?r=0_2216-4WXkk")
      )
      .exec(http("request_73")
        .get("/Scripts/RootBundle?v=Z5MJwH8Xi0bCONWdJcmOtX_Ca81BpX4JptdIbZb919g1")
      )
      .exec(http("request_74")
        .get("/DXR.axd?r=0_2316-4WXkk")
      )
      .pause(519.milliseconds)
      .exec(http("request_75")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_76")
        .get("/DXR.axd?r=0_2303-4WXkk"))
  }

  def FilterForm = {
    exec(http("request_86")
      .post("/Criteria/RenderOrganizationUnitsPartial")
      .formParam("organizationLevel", "1")
      .formParam("criteriaObject[Type]", "OrganizationUnits")
      .formParam("criteriaObject[Name]", "Organization")
      .formParam("criteriaObject[Label]", "Organization")
      .formParam("criteriaObject[DefaultValue]", "")
      .formParam("criteriaObject[DefaultDate]", "")
      .formParam("criteriaObject[DefaultDateRangeFrom]", "")
      .formParam("criteriaObject[DefaultDateRangeTo]", "")
      .formParam("criteriaObject[Value]", "")
      .formParam("criteriaObject[GroupId]", "2")
      .formParam("criteriaObject[IsRequired]", "false")
      .formParam("criteriaObject[Group][Id]", "2")
      .formParam("criteriaObject[Group][Title]", "Optional Selection")
      .formParam("criteriaObject[DropDownListProperties][TextField]", "LOCATION_LABEL")
      .formParam("criteriaObject[DropDownListProperties][ValueField]", "LOCATION_LEVEL")
      .formParam("criteriaObject[DropDownListProperties][FilterField]", "")
      .formParam("criteriaObject[DropDownListProperties][DatasourceName]", "OrganizationLevels")
      .formParam("criteriaObject[DropDownListProperties][DisplayFormatString]", "")
      .formParam("criteriaObject[DropDownListProperties][SourceFrom]", "0")
      .formParam("criteriaObject[DropDownListProperties][DefaultIndex]", "")
      .formParam("criteriaObject[DropDownListProperties][SelectedIndexChangedJsCallBack]", "")
      .formParam("criteriaObject[DropDownListProperties][ColumnsList]", "")
      .formParam("criteriaObject[DropDownListProperties][IsMultiSelection]", "true")
      .formParam("criteriaObject[DropDownListProperties][DefaultValues]", "")
      .formParam("criteriaObject[DropDownListProperties][LoadOnDemand]", "false")
      .formParam("criteriaObject[DropDownListProperties][SelectAllMode]", "false")
      .formParam("criteriaObject[DropDownListProperties][DefaultSelectAll]", "false")
      .formParam("criteriaObject[DropDownListProperties][CascadeControl]", "")
      .formParam("criteriaObject[DropDownListProperties][DatasourceParameters]", "")
      .formParam("criteriaObject[DropDownListProperties][IsWrapText]", "true")
      .formParam("criteriaObject[CascadeDropDownListProperties]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][TextField]", "LOCATION_NAME")
      .formParam("criteriaObject[ChildDropDownListProperties][ValueField]", "LOCATION_CODE")
      .formParam("criteriaObject[ChildDropDownListProperties][FilterField]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][DatasourceName]", "AllEntityLocations")
      .formParam("criteriaObject[ChildDropDownListProperties][DisplayFormatString]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][SourceFrom]", "0")
      .formParam("criteriaObject[ChildDropDownListProperties][DefaultIndex]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][SelectedIndexChangedJsCallBack]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][0][Name]", "LOCATION_CODE")
      .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][0][Label]", "Code")
      .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][0][Width]", "120")
      .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][0][ColumnDisplayFormatString]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][1][Name]", "LOCATION_NAME")
      .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][1][Label]", "Description")
      .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][1][Width]", "350")
      .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][1][ColumnDisplayFormatString]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][IsMultiSelection]", "true")
      .formParam("criteriaObject[ChildDropDownListProperties][DefaultValues]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][LoadOnDemand]", "false")
      .formParam("criteriaObject[ChildDropDownListProperties][SelectAllMode]", "false")
      .formParam("criteriaObject[ChildDropDownListProperties][DefaultSelectAll]", "false")
      .formParam("criteriaObject[ChildDropDownListProperties][CascadeControl]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][DatasourceParameters]", "")
      .formParam("criteriaObject[ChildDropDownListProperties][IsWrapText]", "false")
      .formParam("criteriaObject[CheckListProperties]", "")
      .formParam("criteriaObject[DefaultIndex]", "")
      .formParam("criteriaObject[IsAddLabel]", "false")
      .formParam("criteriaObject[IsChecked]", "false")
      .formParam("criteriaObject[Caption]", "")
      .formParam("criteriaObject[CheckedChangedJsCallBack]", "")
      .formParam("criteriaObject[MaxLength]", "0")
      .formParam("criteriaObject[DisplayFormatString]", "")
      .formParam("criteriaObject[NullText]", "")
      .formParam("criteriaObject[ShowIncrementButtons]", "false")
      .formParam("criteriaObject[Page]", "0")
      .formParam("criteriaObject[CascadeControl]", "")
      .formParam("criteriaObject[ValueFieldDelimiter]", "")
      .formParam("criteriaObject[DownloadBy]", "")
      .formParam("criteriaObject[InitJsCallBack]", "")
      .formParam("criteriaObject[MultiValueDelimiter]", "")
      .formParam("criteriaObject[DefaultValueTo]", ""))
      .pause(4)
      .exec(http("request_87")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_88")
        .post("/CustomReport/OrganizationUnitsDisplay")

        .formParam("objectLabel", "Organization")
        .formParam("objectSelectedIds[0][Number]", "1")
        .formParam("objectSelectedIds[0][Name]", "Company")
        .formParam("objectSelectedIds[0][UnitsId][]", "PPP"))
      .pause(8)
      .exec(http("request_89")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_90")
        .post("/CustomReport/DateRangeDisplay")

        .formParam("objectLabel", "EffectiveDateRange")
        .formParam("dateFrom", "01/05/2020")
        .formParam("dateTo", "01/05/2020"))
      .pause(4)
      .exec(http("request_91")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_92")
        .post("/CustomReport/DateRangeDisplay")

        .formParam("objectLabel", "EffectiveDateRange")
        .formParam("dateFrom", "01/05/2020")
        .formParam("dateTo", "04/05/2021"))
      .pause(2)
      .exec(http("request_93")
        .post("/Account/VerifyAccess")
      )
  }
  def clickSearch = {
    exec(http("Click Search Button")
      .post("/CustomReport/ReportViewerWithHeaderPartial")
      .formParam("layout[CustomSearchParameters][0][Name]", "EffectiveDateRangeFrom")
      .formParam("layout[CustomSearchParameters][0][Value]", "2020/05/01")
      .formParam("layout[CustomSearchParameters][1][Name]", "EffectiveDateRangeTo")
      .formParam("layout[CustomSearchParameters][1][Value]", "2021/05/04")
      .formParam("layout[CustomSearchParameters][2][Name]", "EmployeeStatusWithoutResignee")
      .formParam("layout[CustomSearchParameters][2][Value]", "A,I")
      .formParam("layout[CustomSearchParameters][3][Name]", "Location")
      .formParam("layout[CustomSearchParameters][3][Value]", "")
      .formParam("layout[CustomSearchParameters][4][Name]", "LevelRanges")
      .formParam("layout[CustomSearchParameters][4][Value]", "PPP|||||||||")
      .formParam("layout[CustomSearchParameters][5][Name]", "Category")
      .formParam("layout[CustomSearchParameters][5][Value]", "")
      .formParam("layout[CustomSearchParameters][6][Name]", "Grade")
      .formParam("layout[CustomSearchParameters][6][Value]", "")
      .formParam("layout[CustomSearchParameters][7][Name]", "Employee")
      .formParam("layout[CustomSearchParameters][7][Value]", "")
      .formParam("layout[CustomSearchParameters][8][Name]", "HireDateFrom")
      .formParam("layout[CustomSearchParameters][8][Value]", "")
      .formParam("layout[CustomSearchParameters][9][Name]", "HireDateTo")
      .formParam("layout[CustomSearchParameters][9][Value]", "")
      .formParam("layout[CustomSearchParameters][10][Name]", "TerminationDateFrom")
      .formParam("layout[CustomSearchParameters][10][Value]", "")
      .formParam("layout[CustomSearchParameters][11][Name]", "TerminationDateTo")
      .formParam("layout[CustomSearchParameters][11][Value]", "")
      .formParam("layout[CustomSearchParameters][12][Name]", "ServiceType")
      .formParam("layout[CustomSearchParameters][12][Value]", "")
      .formParam("layout[GroupFooterSummaryTextField]", "Employee No")
      .formParam("layout[NumberOfVisibleColumns]", "0")
      .formParam("layout[NumberOfGroupedColumns]", "0")
      .formParam("layout[ColumnProperties][0][Visible]", "true")
      .formParam("layout[ColumnProperties][0][Width]", "100")
      .formParam("layout[ColumnProperties][0][VisibleIndex]", "0")
      .formParam("layout[ColumnProperties][0][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][0][FieldName]", "Employee No")
      .formParam("layout[ColumnProperties][0][AllowCellMerge]", "true")
      .formParam("layout[ColumnProperties][0][FieldCaption]", "Employee No")
      .formParam("layout[ColumnProperties][0][FieldType]", "")
      .formParam("layout[ColumnProperties][1][Visible]", "true")
      .formParam("layout[ColumnProperties][1][Width]", "130")
      .formParam("layout[ColumnProperties][1][VisibleIndex]", "1")
      .formParam("layout[ColumnProperties][1][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][1][FieldName]", "Employee Name")
      .formParam("layout[ColumnProperties][1][AllowCellMerge]", "true")
      .formParam("layout[ColumnProperties][1][FieldCaption]", "Employee Name")
      .formParam("layout[ColumnProperties][1][FieldType]", "")
      .formParam("layout[ColumnProperties][2][Visible]", "true")
      .formParam("layout[ColumnProperties][2][Width]", "77")
      .formParam("layout[ColumnProperties][2][VisibleIndex]", "2")
      .formParam("layout[ColumnProperties][2][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][2][FieldName]", "Hire Date")
      .formParam("layout[ColumnProperties][2][AllowCellMerge]", "true")
      .formParam("layout[ColumnProperties][2][FieldCaption]", "Hire Date")
      .formParam("layout[ColumnProperties][2][FieldType]", "")
      .formParam("layout[ColumnProperties][3][Visible]", "true")
      .formParam("layout[ColumnProperties][3][Width]", "78")
      .formParam("layout[ColumnProperties][3][VisibleIndex]", "3")
      .formParam("layout[ColumnProperties][3][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][3][FieldName]", "Action Date")
      .formParam("layout[ColumnProperties][3][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][3][FieldCaption]", "Action Date")
      .formParam("layout[ColumnProperties][3][FieldType]", "")
      .formParam("layout[ColumnProperties][4][Visible]", "true")
      .formParam("layout[ColumnProperties][4][Width]", "92")
      .formParam("layout[ColumnProperties][4][VisibleIndex]", "4")
      .formParam("layout[ColumnProperties][4][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][4][FieldName]", "Effective Date")
      .formParam("layout[ColumnProperties][4][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][4][FieldCaption]", "Effective Date")
      .formParam("layout[ColumnProperties][4][FieldType]", "")
      .formParam("layout[ColumnProperties][5][Visible]", "true")
      .formParam("layout[ColumnProperties][5][Width]", "100")
      .formParam("layout[ColumnProperties][5][VisibleIndex]", "5")
      .formParam("layout[ColumnProperties][5][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][5][FieldName]", "Service Type")
      .formParam("layout[ColumnProperties][5][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][5][FieldCaption]", "Service Type")
      .formParam("layout[ColumnProperties][5][FieldType]", "")
      .formParam("layout[ColumnProperties][6][Visible]", "true")
      .formParam("layout[ColumnProperties][6][Width]", "83")
      .formParam("layout[ColumnProperties][6][VisibleIndex]", "6")
      .formParam("layout[ColumnProperties][6][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][6][FieldName]", "Change On")
      .formParam("layout[ColumnProperties][6][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][6][FieldCaption]", "Change On")
      .formParam("layout[ColumnProperties][6][FieldType]", "")
      .formParam("layout[ColumnProperties][7][Visible]", "true")
      .formParam("layout[ColumnProperties][7][Width]", "97")
      .formParam("layout[ColumnProperties][7][VisibleIndex]", "7")
      .formParam("layout[ColumnProperties][7][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][7][FieldName]", "Before Change")
      .formParam("layout[ColumnProperties][7][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][7][FieldCaption]", "Before Change")
      .formParam("layout[ColumnProperties][7][FieldType]", "")
      .formParam("layout[ColumnProperties][8][Visible]", "true")
      .formParam("layout[ColumnProperties][8][Width]", "101")
      .formParam("layout[ColumnProperties][8][VisibleIndex]", "8")
      .formParam("layout[ColumnProperties][8][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][8][FieldName]", "After Change")
      .formParam("layout[ColumnProperties][8][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][8][FieldCaption]", "After Change")
      .formParam("layout[ColumnProperties][8][FieldType]", "")
      .formParam("layout[ColumnProperties][9][Visible]", "true")
      .formParam("layout[ColumnProperties][9][Width]", "75")
      .formParam("layout[ColumnProperties][9][VisibleIndex]", "9")
      .formParam("layout[ColumnProperties][9][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][9][FieldName]", "Reason")
      .formParam("layout[ColumnProperties][9][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][9][FieldCaption]", "Reason")
      .formParam("layout[ColumnProperties][9][FieldType]", "")
      .formParam("layout[ColumnProperties][10][Visible]", "true")
      .formParam("layout[ColumnProperties][10][Width]", "80")
      .formParam("layout[ColumnProperties][10][VisibleIndex]", "10")
      .formParam("layout[ColumnProperties][10][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][10][FieldName]", "Remarks")
      .formParam("layout[ColumnProperties][10][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][10][FieldCaption]", "Remarks")
      .formParam("layout[ColumnProperties][10][FieldType]", "")
      .formParam("layout[ColumnProperties][11][Visible]", "false")
      .formParam("layout[ColumnProperties][11][Width]", "100")
      .formParam("layout[ColumnProperties][11][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][11][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][11][FieldName]", "Entity")
      .formParam("layout[ColumnProperties][11][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][11][FieldCaption]", "Entity")
      .formParam("layout[ColumnProperties][11][FieldType]", "R")
      .formParam("layout[ColumnProperties][12][Visible]", "false")
      .formParam("layout[ColumnProperties][12][Width]", "100")
      .formParam("layout[ColumnProperties][12][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][12][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][12][FieldName]", "Effective Date From")
      .formParam("layout[ColumnProperties][12][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][12][FieldCaption]", "Effective Date From")
      .formParam("layout[ColumnProperties][12][FieldType]", "R")
      .formParam("layout[ColumnProperties][13][Visible]", "false")
      .formParam("layout[ColumnProperties][13][Width]", "100")
      .formParam("layout[ColumnProperties][13][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][13][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][13][FieldName]", "Organization Level")
      .formParam("layout[ColumnProperties][13][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][13][FieldCaption]", "Organization Level")
      .formParam("layout[ColumnProperties][13][FieldType]", "R")
      .formParam("layout[GridViewCellStyle][FontSize]", "7")
      .formParam("layout[GridViewExportCellStyle][FontSize]", "7")
      .formParam("layout[ShowGroupSummary]", "False")
      .formParam("layout[ShowTotalSummary]", "False")
      .formParam("layout[GroupSummaryTitleFormat]", "{0}:{1}")
      .formParam("layout[GroupHeaderColumnCount]", "0")
      .formParam("layout[RepeatReportHeader]", "False")
      .formParam("layout[ReportHeaderPageBreak]", "")
      .formParam("layout[ColumnGropingLevelCount]", "0")
      .formParam("layout[RepeatColumnHeader]", "False")
      .formParam("layout[HideDetails]", "False")
      .formParam("TemplateId", "46")
      .formParam("ReportId", "36")
      .check(bodyString.saveAs("ReportViewer")))
  }
  def logout = {
    exec(http("Log out")
      .post("/Account/LogOff")
      .formParam("__RequestVerificationToken", "${__RequestVerificationTokenLogout}")
      .formParam("DXScript", "1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_270,1_286,1_289,1_183,17_42,17_3,1_285,1_188,17_8,1_297,1_192,17_10,1_287,1_194,1_193,17_11,1_208,1_216,1_301,1_253,1_234,1_246,1_302,1_221,17_12,1_296,1_295,1_278,17_41,1_189,1_222,1_290,1_288,1_195,1_255,1_262,1_261,1_254,1_251,1_258,1_252,1_260,1_257,1_256,1_247,1_243,1_241,1_250,1_249,1_248,1_245,1_244,1_259,1_240,1_237,1_238,1_239,1_242,17_15,17_17,1_271,1_272,17_19,1_273,1_274,17_20,17_21,1_223,17_14,1_276,17_24,17_28,1_280,17_25,1_293,17_27,1_291,1_294,17_32,1_298,17_36,17_40,1_197,17_1,1_207,1_235,17_16,6_18,6_16,6_15,6_14,6_17,17_39,1_212,1_196,17_0,1_198,17_2,1_199,17_4,1_200,1_201,1_202,1_204,1_218,1_205,17_7,1_211,17_23,1_206,17_9,1_275,1_214,1_215,17_22,1_213,1_217,17_38,1_219,1_232,1_233,1_231,17_5,1_191,1_284,18_36,18_38,18_33,18_42,18_37,18_35,17_31,1_203,1_283,9_54,9_55,24_379,24_389,9_57,9_56,17_44,9_45,9_47,9_46,17_30,9_51,9_48,9_31,17_29,9_50,9_41,9_53,9_52,9_49")
      .formParam("DXCss", "/Content/css/root?v=fQqb8rdb3SX3t_q5clLhrjqLMPJRz5XyrffvnRHeaqY1,0_2312,1_50,1_53,1_51,0_2317,1_40,1_17,0_2214,1_16,0_2219,0_2221,0_2225,1_18,1_4,0_2279,6_3,0_2283,0_2186,0_2190,0_2257,18_3,18_11,18_7,0_2261,0_2313,1_34,24_359,24_364,24_360,9_19,9_15,9_12,0_2338,9_1,0_2342,9_4,1_7,/Content/ExecutiveDashboard/ExecutiveDashboardBundle?v=K3bp7bOUCg7jvMi3yCOp8VvRDHaxkZJNkgNJYDsPeIA1,/Content/ExecutiveDashboardBundle?v=yudLVP8cmmFF7pYfIl5_OmdH-W3uaCGxdSLyC-jbYQo1,/Content/notifications.css,/Content/jquery-ui.css,/Content/PayrollProcess.css")
      .check(status.is(302)))
      .exec(http("request_103")
        .get("/Account/Login")
      )
      .exec(http("request_104")
        .get("/DXR.axd?r=1_58-lUXkk")
      )
      .exec(http("request_105")
        .get("/DXR.axd?r=1_17,0_2214,1_50,1_53,1_51,1_16,0_2219,0_2312,0_2317-4WXkk")
      )
      .exec(http("request_106")
        .get("/Content/css?v=w9USDPGryprQSMA62T1giyRXrtqAIG-BphxyQY0Qw_w1")
      )
      .exec(http("request_107")
        .get("/DXR.axd?r=1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_208,1_216,1_212,1_189,1_222,17_42,1_297,1_215,1_207,1_289,1_205,17_7,1_287,1_211,17_23,1_197,17_1-lUXkk")
      )
      .exec(http("request_108")
        .get("/bundles/jquery?v=w1vknpWt6KqlZcHeJQvaK6VbvvXt1Go8HcGH_DqKzzo1")
      )
      .exec(http("request_109")
        .get("/Content/fonts/icomoon.ttf?5vru0d")
      )
      .pause(108.milliseconds)
      .exec(http("request_110")
        .get("/Content/Images/bg-login.jpg?V=03")
      )
  }
}
