package computerdatabase.Module.Claim.Report
import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

object ClaimEntitlementReport {

  val uri1 = "https://maps.googleapis.com/maps/api/js"
  val uri3 = "https://fonts.googleapis.com/css"

  def loadClaimEntitlementReport = {
    exec(http("Open Claim Entitlement REport")
      .get("/CustomReport/ReportViewerDisplay/ClaimEntitlementReport")
      .check(regex("""<input name="__RequestVerificationToken" type="hidden" value="(.+?)" />""")	.find.saveAs("__RequestVerificationTokenLogout"))
    )
      .pause(252.milliseconds)
      .exec(http("request_61")
        .get("/DXR.axd?r=0_2314-O3Vxm")
      )
      .exec(http("request_62")
        .get("/DXR.axd?r=0_2316-O3Vxm")
      )
      .exec(http("request_63")
        .get("/DXR.axd?r=0_2216-O3Vxm")
      )
      .exec(http("request_64")
        .get(uri1 + "?key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A")
      )
      .exec(http("request_65")
        .get("/Scripts/RootBundle?v=Z5MJwH8Xi0bCONWdJcmOtX_Ca81BpX4JptdIbZb919g1")
      )
      .pause(367.milliseconds)
      .exec(http("request_66")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_67")
        .get("/DXR.axd?r=0_2303-O3Vxm"))
      .exec(http("request_68")
        .post("/CustomReport/CheckBoxListDisplay")

        .formParam("objectLabel", "EmployeeStatus")
        .formParam("objectSelectedIds[]", "A")
        .formParam("objectSelectedIds[]", "L")
        .formParam("objectSelectedIds[]", "I"))
      .exec(http("request_69")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_70")
        .post("/CustomReport/ComboBoxDisplay")

        .formParam("objectLabel", "GroupBy")
        .formParam("comboBoxValue", "1"))
      .pause(169.milliseconds)
      .exec(http("request_71")
        .get("/DXR.axd?r=0_2303-O3Vxm"))
      .exec(http("request_72")
        .get("/Notifications/GetNotificationCounts")
      )
      .exec(http("request_73")
        .get("/Notifications/GetNotificationUserId")
      )
      .exec(http("request_74")
        .get("/signalr/negotiate?clientProtocol=2.1&userid=C001682&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1622709111101")
      )
      .pause(541.milliseconds)
      .exec(http("request_75")
        .get("/signalr/start?transport=webSockets&clientProtocol=2.1&userid=C001682&connectionToken=ABM0RxitLydw2tbCu32QTI2PaWNmreXdxZ7s5Ul4DVOL82hPls8EldmCx4lHA01VdcvVhGqkNF4P2wXZ7C6SNJYj50npn8G4Il3CwrUIcXoi9mDehOYkuhhiOEvmF81QxIjYHgO6CepRjCAVrlx69Nnhwfvs0ki3gmDLq4wy1Io%3D&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1622709111102")
      )
      .pause(2)
      .exec(http("request_76")
        .get(uri1 + "/AuthenticationService.Authenticate?1shttps%3A%2F%2Forisoftst.orisoftsaas.com%2FCustomReport%2FReportViewerDisplay%2FClaimEntitlementReport&4sAIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A&callback=_xdc_._f3kezs&key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A&token=76235")
      )
      .pause(596.milliseconds)
      .exec(http("request_77")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_78")
        .get("/DXR.axd?r=0_2303-O3Vxm"))
  }

  def generateReport = {
    exec(http("Generate Report")
      .post("/CustomReport/ReportViewerWithHeaderPartial")
      .formParam("layout[CustomSearchParameters][0][Name]", "EmployeeStatus")
      .formParam("layout[CustomSearchParameters][0][Value]", "A,L,I")
      .formParam("layout[CustomSearchParameters][1][Name]", "YearRangeFrom")
      .formParam("layout[CustomSearchParameters][1][Value]", "2021")
      .formParam("layout[CustomSearchParameters][2][Name]", "YearRangeTo")
      .formParam("layout[CustomSearchParameters][2][Value]", "2021")
      .formParam("layout[CustomSearchParameters][3][Name]", "GroupBy")
      .formParam("layout[CustomSearchParameters][3][Value]", "1")
      .formParam("layout[CustomSearchParameters][4][Name]", "Location")
      .formParam("layout[CustomSearchParameters][4][Value]", "")
      .formParam("layout[CustomSearchParameters][5][Name]", "LevelRanges")
      .formParam("layout[CustomSearchParameters][5][Value]", "PHAK|||||||||")
      .formParam("layout[CustomSearchParameters][6][Name]", "Category")
      .formParam("layout[CustomSearchParameters][6][Value]", "")
      .formParam("layout[CustomSearchParameters][7][Name]", "Position")
      .formParam("layout[CustomSearchParameters][7][Value]", "")
      .formParam("layout[CustomSearchParameters][8][Name]", "Grade")
      .formParam("layout[CustomSearchParameters][8][Value]", "")
      .formParam("layout[CustomSearchParameters][9][Name]", "Employee")
      .formParam("layout[CustomSearchParameters][9][Value]", "")
      .formParam("layout[CustomSearchParameters][10][Name]", "HireDateFrom")
      .formParam("layout[CustomSearchParameters][10][Value]", "")
      .formParam("layout[CustomSearchParameters][11][Name]", "HireDateTo")
      .formParam("layout[CustomSearchParameters][11][Value]", "")
      .formParam("layout[CustomSearchParameters][12][Name]", "TerminationDateFrom")
      .formParam("layout[CustomSearchParameters][12][Value]", "")
      .formParam("layout[CustomSearchParameters][13][Name]", "TerminationDateTo")
      .formParam("layout[CustomSearchParameters][13][Value]", "")
      .formParam("layout[CustomSearchParameters][14][Name]", "ClaimBudgetGroup")
      .formParam("layout[CustomSearchParameters][14][Value]", "")
      .formParam("layout[CustomSearchParameters][15][Name]", "Claim")
      .formParam("layout[CustomSearchParameters][15][Value]", "")
      .formParam("layout[CustomSearchParameters][16][Name]", "ClaimSubType")
      .formParam("layout[CustomSearchParameters][16][Value]", "")
      .formParam("layout[GroupFooterSummaryTextField]", "employee_no")
      .formParam("layout[NumberOfVisibleColumns]", "0")
      .formParam("layout[NumberOfGroupedColumns]", "0")
      .formParam("layout[ColumnProperties][0][Visible]", "true")
      .formParam("layout[ColumnProperties][0][Width]", "100")
      .formParam("layout[ColumnProperties][0][VisibleIndex]", "0")
      .formParam("layout[ColumnProperties][0][GroupIndex]", "1")
      .formParam("layout[ColumnProperties][0][FieldName]", "Claim Budget Group")
      .formParam("layout[ColumnProperties][0][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][0][FieldCaption]", "Claim Budget Group")
      .formParam("layout[ColumnProperties][0][FieldType]", "")
      .formParam("layout[ColumnProperties][1][Visible]", "true")
      .formParam("layout[ColumnProperties][1][Width]", "100")
      .formParam("layout[ColumnProperties][1][VisibleIndex]", "1")
      .formParam("layout[ColumnProperties][1][GroupIndex]", "0")
      .formParam("layout[ColumnProperties][1][FieldName]", "location_name")
      .formParam("layout[ColumnProperties][1][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][1][FieldCaption]", "location_name")
      .formParam("layout[ColumnProperties][1][FieldType]", "")
      .formParam("layout[ColumnProperties][2][Visible]", "true")
      .formParam("layout[ColumnProperties][2][Width]", "62")
      .formParam("layout[ColumnProperties][2][VisibleIndex]", "2")
      .formParam("layout[ColumnProperties][2][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][2][FieldName]", "employee_no")
      .formParam("layout[ColumnProperties][2][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][2][FieldCaption]", "employee_no")
      .formParam("layout[ColumnProperties][2][FieldType]", "")
      .formParam("layout[ColumnProperties][3][Visible]", "true")
      .formParam("layout[ColumnProperties][3][Width]", "100")
      .formParam("layout[ColumnProperties][3][VisibleIndex]", "3")
      .formParam("layout[ColumnProperties][3][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][3][FieldName]", "employee_name")
      .formParam("layout[ColumnProperties][3][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][3][FieldCaption]", "employee_name")
      .formParam("layout[ColumnProperties][3][FieldType]", "")
      .formParam("layout[ColumnProperties][4][Visible]", "true")
      .formParam("layout[ColumnProperties][4][Width]", "56")
      .formParam("layout[ColumnProperties][4][VisibleIndex]", "4")
      .formParam("layout[ColumnProperties][4][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][4][FieldName]", "gender")
      .formParam("layout[ColumnProperties][4][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][4][FieldCaption]", "gender")
      .formParam("layout[ColumnProperties][4][FieldType]", "")
      .formParam("layout[ColumnProperties][5][Visible]", "true")
      .formParam("layout[ColumnProperties][5][Width]", "100")
      .formParam("layout[ColumnProperties][5][VisibleIndex]", "5")
      .formParam("layout[ColumnProperties][5][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][5][FieldName]", "position")
      .formParam("layout[ColumnProperties][5][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][5][FieldCaption]", "position")
      .formParam("layout[ColumnProperties][5][FieldType]", "")
      .formParam("layout[ColumnProperties][6][Visible]", "true")
      .formParam("layout[ColumnProperties][6][Width]", "79")
      .formParam("layout[ColumnProperties][6][VisibleIndex]", "6")
      .formParam("layout[ColumnProperties][6][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][6][FieldName]", "grade")
      .formParam("layout[ColumnProperties][6][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][6][FieldCaption]", "grade")
      .formParam("layout[ColumnProperties][6][FieldType]", "")
      .formParam("layout[ColumnProperties][7][Visible]", "true")
      .formParam("layout[ColumnProperties][7][Width]", "100")
      .formParam("layout[ColumnProperties][7][VisibleIndex]", "7")
      .formParam("layout[ColumnProperties][7][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][7][FieldName]", "category")
      .formParam("layout[ColumnProperties][7][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][7][FieldCaption]", "category")
      .formParam("layout[ColumnProperties][7][FieldType]", "")
      .formParam("layout[ColumnProperties][8][Visible]", "true")
      .formParam("layout[ColumnProperties][8][Width]", "100")
      .formParam("layout[ColumnProperties][8][VisibleIndex]", "8")
      .formParam("layout[ColumnProperties][8][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][8][FieldName]", "hire_date")
      .formParam("layout[ColumnProperties][8][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][8][FieldCaption]", "hire_date")
      .formParam("layout[ColumnProperties][8][FieldType]", "")
      .formParam("layout[ColumnProperties][9][Visible]", "true")
      .formParam("layout[ColumnProperties][9][Width]", "100")
      .formParam("layout[ColumnProperties][9][VisibleIndex]", "9")
      .formParam("layout[ColumnProperties][9][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][9][FieldName]", "terminate_date")
      .formParam("layout[ColumnProperties][9][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][9][FieldCaption]", "terminate_date")
      .formParam("layout[ColumnProperties][9][FieldType]", "")
      .formParam("layout[ColumnProperties][10][Visible]", "true")
      .formParam("layout[ColumnProperties][10][Width]", "146")
      .formParam("layout[ColumnProperties][10][VisibleIndex]", "10")
      .formParam("layout[ColumnProperties][10][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][10][FieldName]", "level_name1")
      .formParam("layout[ColumnProperties][10][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][10][FieldCaption]", "level_name1")
      .formParam("layout[ColumnProperties][10][FieldType]", "")
      .formParam("layout[ColumnProperties][11][Visible]", "true")
      .formParam("layout[ColumnProperties][11][Width]", "144")
      .formParam("layout[ColumnProperties][11][VisibleIndex]", "11")
      .formParam("layout[ColumnProperties][11][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][11][FieldName]", "level_name2")
      .formParam("layout[ColumnProperties][11][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][11][FieldCaption]", "level_name2")
      .formParam("layout[ColumnProperties][11][FieldType]", "")
      .formParam("layout[ColumnProperties][12][Visible]", "true")
      .formParam("layout[ColumnProperties][12][Width]", "146")
      .formParam("layout[ColumnProperties][12][VisibleIndex]", "12")
      .formParam("layout[ColumnProperties][12][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][12][FieldName]", "level_name3")
      .formParam("layout[ColumnProperties][12][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][12][FieldCaption]", "level_name3")
      .formParam("layout[ColumnProperties][12][FieldType]", "")
      .formParam("layout[ColumnProperties][13][Visible]", "true")
      .formParam("layout[ColumnProperties][13][Width]", "154")
      .formParam("layout[ColumnProperties][13][VisibleIndex]", "13")
      .formParam("layout[ColumnProperties][13][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][13][FieldName]", "level_name4")
      .formParam("layout[ColumnProperties][13][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][13][FieldCaption]", "level_name4")
      .formParam("layout[ColumnProperties][13][FieldType]", "")
      .formParam("layout[ColumnProperties][14][Visible]", "true")
      .formParam("layout[ColumnProperties][14][Width]", "131")
      .formParam("layout[ColumnProperties][14][VisibleIndex]", "14")
      .formParam("layout[ColumnProperties][14][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][14][FieldName]", "level_name5")
      .formParam("layout[ColumnProperties][14][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][14][FieldCaption]", "level_name5")
      .formParam("layout[ColumnProperties][14][FieldType]", "")
      .formParam("layout[ColumnProperties][15][Visible]", "true")
      .formParam("layout[ColumnProperties][15][Width]", "134")
      .formParam("layout[ColumnProperties][15][VisibleIndex]", "15")
      .formParam("layout[ColumnProperties][15][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][15][FieldName]", "level_name6")
      .formParam("layout[ColumnProperties][15][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][15][FieldCaption]", "level_name6")
      .formParam("layout[ColumnProperties][15][FieldType]", "")
      .formParam("layout[ColumnProperties][16][Visible]", "true")
      .formParam("layout[ColumnProperties][16][Width]", "127")
      .formParam("layout[ColumnProperties][16][VisibleIndex]", "16")
      .formParam("layout[ColumnProperties][16][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][16][FieldName]", "level_name7")
      .formParam("layout[ColumnProperties][16][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][16][FieldCaption]", "level_name7")
      .formParam("layout[ColumnProperties][16][FieldType]", "")
      .formParam("layout[ColumnProperties][17][Visible]", "true")
      .formParam("layout[ColumnProperties][17][Width]", "126")
      .formParam("layout[ColumnProperties][17][VisibleIndex]", "17")
      .formParam("layout[ColumnProperties][17][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][17][FieldName]", "level_name8")
      .formParam("layout[ColumnProperties][17][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][17][FieldCaption]", "level_name8")
      .formParam("layout[ColumnProperties][17][FieldType]", "")
      .formParam("layout[ColumnProperties][18][Visible]", "true")
      .formParam("layout[ColumnProperties][18][Width]", "131")
      .formParam("layout[ColumnProperties][18][VisibleIndex]", "18")
      .formParam("layout[ColumnProperties][18][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][18][FieldName]", "level_name9")
      .formParam("layout[ColumnProperties][18][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][18][FieldCaption]", "level_name9")
      .formParam("layout[ColumnProperties][18][FieldType]", "")
      .formParam("layout[ColumnProperties][19][Visible]", "true")
      .formParam("layout[ColumnProperties][19][Width]", "114")
      .formParam("layout[ColumnProperties][19][VisibleIndex]", "19")
      .formParam("layout[ColumnProperties][19][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][19][FieldName]", "level_name10")
      .formParam("layout[ColumnProperties][19][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][19][FieldCaption]", "level_name10")
      .formParam("layout[ColumnProperties][19][FieldType]", "")
      .formParam("layout[ColumnProperties][20][Visible]", "true")
      .formParam("layout[ColumnProperties][20][Width]", "100")
      .formParam("layout[ColumnProperties][20][VisibleIndex]", "20")
      .formParam("layout[ColumnProperties][20][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][20][FieldName]", "claim_description")
      .formParam("layout[ColumnProperties][20][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][20][FieldCaption]", "claim_description")
      .formParam("layout[ColumnProperties][20][FieldType]", "")
      .formParam("layout[ColumnProperties][21][Visible]", "true")
      .formParam("layout[ColumnProperties][21][Width]", "100")
      .formParam("layout[ColumnProperties][21][VisibleIndex]", "21")
      .formParam("layout[ColumnProperties][21][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][21][FieldName]", "Claim_sub_description")
      .formParam("layout[ColumnProperties][21][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][21][FieldCaption]", "Claim_sub_description")
      .formParam("layout[ColumnProperties][21][FieldType]", "")
      .formParam("layout[ColumnProperties][22][Visible]", "true")
      .formParam("layout[ColumnProperties][22][Width]", "100")
      .formParam("layout[ColumnProperties][22][VisibleIndex]", "22")
      .formParam("layout[ColumnProperties][22][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][22][FieldName]", "budget_entitled")
      .formParam("layout[ColumnProperties][22][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][22][FieldCaption]", "budget_entitled")
      .formParam("layout[ColumnProperties][22][FieldType]", "")
      .formParam("layout[ColumnProperties][23][Visible]", "true")
      .formParam("layout[ColumnProperties][23][Width]", "100")
      .formParam("layout[ColumnProperties][23][VisibleIndex]", "23")
      .formParam("layout[ColumnProperties][23][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][23][FieldName]", "yearly_entitled")
      .formParam("layout[ColumnProperties][23][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][23][FieldCaption]", "yearly_entitled")
      .formParam("layout[ColumnProperties][23][FieldType]", "")
      .formParam("layout[ColumnProperties][24][Visible]", "true")
      .formParam("layout[ColumnProperties][24][Width]", "100")
      .formParam("layout[ColumnProperties][24][VisibleIndex]", "24")
      .formParam("layout[ColumnProperties][24][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][24][FieldName]", "monthly_entitled")
      .formParam("layout[ColumnProperties][24][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][24][FieldCaption]", "monthly_entitled")
      .formParam("layout[ColumnProperties][24][FieldType]", "")
      .formParam("layout[ColumnProperties][25][Visible]", "true")
      .formParam("layout[ColumnProperties][25][Width]", "100")
      .formParam("layout[ColumnProperties][25][VisibleIndex]", "25")
      .formParam("layout[ColumnProperties][25][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][25][FieldName]", "weekly_entitled")
      .formParam("layout[ColumnProperties][25][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][25][FieldCaption]", "weekly_entitled")
      .formParam("layout[ColumnProperties][25][FieldType]", "")
      .formParam("layout[ColumnProperties][26][Visible]", "true")
      .formParam("layout[ColumnProperties][26][Width]", "100")
      .formParam("layout[ColumnProperties][26][VisibleIndex]", "26")
      .formParam("layout[ColumnProperties][26][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][26][FieldName]", "daily_entitled")
      .formParam("layout[ColumnProperties][26][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][26][FieldCaption]", "daily_entitled")
      .formParam("layout[ColumnProperties][26][FieldType]", "")
      .formParam("layout[ColumnProperties][27][Visible]", "true")
      .formParam("layout[ColumnProperties][27][Width]", "100")
      .formParam("layout[ColumnProperties][27][VisibleIndex]", "27")
      .formParam("layout[ColumnProperties][27][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][27][FieldName]", "budget_used_amount")
      .formParam("layout[ColumnProperties][27][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][27][FieldCaption]", "budget_used_amount")
      .formParam("layout[ColumnProperties][27][FieldType]", "")
      .formParam("layout[ColumnProperties][28][Visible]", "true")
      .formParam("layout[ColumnProperties][28][Width]", "100")
      .formParam("layout[ColumnProperties][28][VisibleIndex]", "28")
      .formParam("layout[ColumnProperties][28][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][28][FieldName]", "yearly_used_amount")
      .formParam("layout[ColumnProperties][28][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][28][FieldCaption]", "yearly_used_amount")
      .formParam("layout[ColumnProperties][28][FieldType]", "")
      .formParam("layout[ColumnProperties][29][Visible]", "true")
      .formParam("layout[ColumnProperties][29][Width]", "100")
      .formParam("layout[ColumnProperties][29][VisibleIndex]", "29")
      .formParam("layout[ColumnProperties][29][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][29][FieldName]", "monthly_used_amount")
      .formParam("layout[ColumnProperties][29][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][29][FieldCaption]", "monthly_used_amount")
      .formParam("layout[ColumnProperties][29][FieldType]", "")
      .formParam("layout[ColumnProperties][30][Visible]", "true")
      .formParam("layout[ColumnProperties][30][Width]", "100")
      .formParam("layout[ColumnProperties][30][VisibleIndex]", "30")
      .formParam("layout[ColumnProperties][30][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][30][FieldName]", "weekly_used_amount")
      .formParam("layout[ColumnProperties][30][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][30][FieldCaption]", "weekly_used_amount")
      .formParam("layout[ColumnProperties][30][FieldType]", "")
      .formParam("layout[ColumnProperties][31][Visible]", "true")
      .formParam("layout[ColumnProperties][31][Width]", "100")
      .formParam("layout[ColumnProperties][31][VisibleIndex]", "31")
      .formParam("layout[ColumnProperties][31][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][31][FieldName]", "daily_used_amount")
      .formParam("layout[ColumnProperties][31][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][31][FieldCaption]", "daily_used_amount")
      .formParam("layout[ColumnProperties][31][FieldType]", "")
      .formParam("layout[ColumnProperties][32][Visible]", "true")
      .formParam("layout[ColumnProperties][32][Width]", "100")
      .formParam("layout[ColumnProperties][32][VisibleIndex]", "32")
      .formParam("layout[ColumnProperties][32][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][32][FieldName]", "budget_remaining_qty")
      .formParam("layout[ColumnProperties][32][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][32][FieldCaption]", "budget_remaining_qty")
      .formParam("layout[ColumnProperties][32][FieldType]", "")
      .formParam("layout[ColumnProperties][33][Visible]", "true")
      .formParam("layout[ColumnProperties][33][Width]", "100")
      .formParam("layout[ColumnProperties][33][VisibleIndex]", "33")
      .formParam("layout[ColumnProperties][33][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][33][FieldName]", "yearly_remaining_qty")
      .formParam("layout[ColumnProperties][33][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][33][FieldCaption]", "yearly_remaining_qty")
      .formParam("layout[ColumnProperties][33][FieldType]", "")
      .formParam("layout[ColumnProperties][34][Visible]", "true")
      .formParam("layout[ColumnProperties][34][Width]", "100")
      .formParam("layout[ColumnProperties][34][VisibleIndex]", "34")
      .formParam("layout[ColumnProperties][34][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][34][FieldName]", "monthly_remaining_qty")
      .formParam("layout[ColumnProperties][34][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][34][FieldCaption]", "monthly_remaining_qty")
      .formParam("layout[ColumnProperties][34][FieldType]", "")
      .formParam("layout[ColumnProperties][35][Visible]", "true")
      .formParam("layout[ColumnProperties][35][Width]", "100")
      .formParam("layout[ColumnProperties][35][VisibleIndex]", "35")
      .formParam("layout[ColumnProperties][35][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][35][FieldName]", "weekly_remaining_qty")
      .formParam("layout[ColumnProperties][35][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][35][FieldCaption]", "weekly_remaining_qty")
      .formParam("layout[ColumnProperties][35][FieldType]", "")
      .formParam("layout[ColumnProperties][36][Visible]", "true")
      .formParam("layout[ColumnProperties][36][Width]", "100")
      .formParam("layout[ColumnProperties][36][VisibleIndex]", "36")
      .formParam("layout[ColumnProperties][36][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][36][FieldName]", "daily_remaining_qty")
      .formParam("layout[ColumnProperties][36][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][36][FieldCaption]", "daily_remaining_qty")
      .formParam("layout[ColumnProperties][36][FieldType]", "")
      .formParam("layout[ColumnProperties][37][Visible]", "false")
      .formParam("layout[ColumnProperties][37][Width]", "100")
      .formParam("layout[ColumnProperties][37][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][37][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][37][FieldName]", "Entity")
      .formParam("layout[ColumnProperties][37][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][37][FieldCaption]", "Entity")
      .formParam("layout[ColumnProperties][37][FieldType]", "R")
      .formParam("layout[ColumnProperties][38][Visible]", "false")
      .formParam("layout[ColumnProperties][38][Width]", "100")
      .formParam("layout[ColumnProperties][38][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][38][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][38][FieldName]", "Date Range")
      .formParam("layout[ColumnProperties][38][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][38][FieldCaption]", "Date Range")
      .formParam("layout[ColumnProperties][38][FieldType]", "R")
      .formParam("layout[ColumnProperties][39][Visible]", "false")
      .formParam("layout[ColumnProperties][39][Width]", "100")
      .formParam("layout[ColumnProperties][39][VisibleIndex]", "-1")
      .formParam("layout[ColumnProperties][39][GroupIndex]", "-1")
      .formParam("layout[ColumnProperties][39][FieldName]", "Group By")
      .formParam("layout[ColumnProperties][39][AllowCellMerge]", "false")
      .formParam("layout[ColumnProperties][39][FieldCaption]", "Group By")
      .formParam("layout[ColumnProperties][39][FieldType]", "R")
      .formParam("layout[GridViewCellStyle][FontSize]", "9")
      .formParam("layout[GridViewExportCellStyle][FontSize]", "9")
      .formParam("layout[ShowGroupSummary]", "False")
      .formParam("layout[ShowTotalSummary]", "False")
      .formParam("layout[GroupSummaryTitleFormat]", "{0}:{1}")
      .formParam("layout[GroupHeaderColumnCount]", "0")
      .formParam("layout[RepeatReportHeader]", "True")
      .formParam("layout[ReportHeaderPageBreak]", "")
      .formParam("layout[ColumnGroupingProperties][0][ColumnName]", "employee_no")
      .formParam("layout[ColumnGroupingProperties][0][ColumnCaption]", "Employee No.")
      .formParam("layout[ColumnGroupingProperties][0][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][0][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][0][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][1][ColumnName]", "employee_name")
      .formParam("layout[ColumnGroupingProperties][1][ColumnCaption]", "Employee Name")
      .formParam("layout[ColumnGroupingProperties][1][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][1][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][1][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][2][ColumnName]", "gender")
      .formParam("layout[ColumnGroupingProperties][2][ColumnCaption]", "Gender")
      .formParam("layout[ColumnGroupingProperties][2][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][2][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][2][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][3][ColumnName]", "position")
      .formParam("layout[ColumnGroupingProperties][3][ColumnCaption]", "Position")
      .formParam("layout[ColumnGroupingProperties][3][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][3][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][3][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][4][ColumnName]", "grade")
      .formParam("layout[ColumnGroupingProperties][4][ColumnCaption]", "Grade")
      .formParam("layout[ColumnGroupingProperties][4][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][4][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][4][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][5][ColumnName]", "category")
      .formParam("layout[ColumnGroupingProperties][5][ColumnCaption]", "Category")
      .formParam("layout[ColumnGroupingProperties][5][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][5][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][5][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][6][ColumnName]", "hire_date")
      .formParam("layout[ColumnGroupingProperties][6][ColumnCaption]", "Hire Date")
      .formParam("layout[ColumnGroupingProperties][6][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][6][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][6][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][7][ColumnName]", "terminate_date")
      .formParam("layout[ColumnGroupingProperties][7][ColumnCaption]", "Terminate Date")
      .formParam("layout[ColumnGroupingProperties][7][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][7][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][7][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][8][ColumnName]", "claim_description")
      .formParam("layout[ColumnGroupingProperties][8][ColumnCaption]", "Claim Type")
      .formParam("layout[ColumnGroupingProperties][8][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][8][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][8][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][9][ColumnName]", "Claim_sub_description")
      .formParam("layout[ColumnGroupingProperties][9][ColumnCaption]", "Claim Sub Type")
      .formParam("layout[ColumnGroupingProperties][9][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][9][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][9][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][10][ColumnName]", "budget_entitled")
      .formParam("layout[ColumnGroupingProperties][10][ColumnCaption]", "Budget Entitlement")
      .formParam("layout[ColumnGroupingProperties][10][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][10][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][10][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][11][ColumnName]", "yearly_entitled")
      .formParam("layout[ColumnGroupingProperties][11][ColumnCaption]", "Yearly Entitlement")
      .formParam("layout[ColumnGroupingProperties][11][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][11][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][11][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][12][ColumnName]", "monthly_entitled")
      .formParam("layout[ColumnGroupingProperties][12][ColumnCaption]", "Monthly Entitlement")
      .formParam("layout[ColumnGroupingProperties][12][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][12][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][12][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][13][ColumnName]", "weekly_entitled")
      .formParam("layout[ColumnGroupingProperties][13][ColumnCaption]", "Weekly Entitlement")
      .formParam("layout[ColumnGroupingProperties][13][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][13][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][13][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][14][ColumnName]", "daily_entitled")
      .formParam("layout[ColumnGroupingProperties][14][ColumnCaption]", "Daily Entitlement")
      .formParam("layout[ColumnGroupingProperties][14][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][14][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][14][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][15][ColumnName]", "budget_used_amount")
      .formParam("layout[ColumnGroupingProperties][15][ColumnCaption]", "Budget Used")
      .formParam("layout[ColumnGroupingProperties][15][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][15][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][15][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][16][ColumnName]", "yearly_used_amount")
      .formParam("layout[ColumnGroupingProperties][16][ColumnCaption]", "Yearly Used")
      .formParam("layout[ColumnGroupingProperties][16][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][16][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][16][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][17][ColumnName]", "monthly_used_amount")
      .formParam("layout[ColumnGroupingProperties][17][ColumnCaption]", "Monthly Used")
      .formParam("layout[ColumnGroupingProperties][17][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][17][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][17][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][18][ColumnName]", "weekly_used_amount")
      .formParam("layout[ColumnGroupingProperties][18][ColumnCaption]", "Weekly Used")
      .formParam("layout[ColumnGroupingProperties][18][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][18][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][18][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][19][ColumnName]", "daily_used_amount")
      .formParam("layout[ColumnGroupingProperties][19][ColumnCaption]", "Daily Used")
      .formParam("layout[ColumnGroupingProperties][19][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][19][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][19][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][20][ColumnName]", "budget_remaining_qty")
      .formParam("layout[ColumnGroupingProperties][20][ColumnCaption]", "Budget Balance")
      .formParam("layout[ColumnGroupingProperties][20][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][20][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][20][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][21][ColumnName]", "yearly_remaining_qty")
      .formParam("layout[ColumnGroupingProperties][21][ColumnCaption]", "Yearly Balance")
      .formParam("layout[ColumnGroupingProperties][21][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][21][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][21][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][22][ColumnName]", "monthly_remaining_qty")
      .formParam("layout[ColumnGroupingProperties][22][ColumnCaption]", "Monthly Balance")
      .formParam("layout[ColumnGroupingProperties][22][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][22][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][22][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][23][ColumnName]", "weekly_remaining_qty")
      .formParam("layout[ColumnGroupingProperties][23][ColumnCaption]", "Weekly Balance")
      .formParam("layout[ColumnGroupingProperties][23][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][23][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][23][formatString]", "")
      .formParam("layout[ColumnGroupingProperties][24][ColumnName]", "daily_remaining_qty")
      .formParam("layout[ColumnGroupingProperties][24][ColumnCaption]", "Daily Balance")
      .formParam("layout[ColumnGroupingProperties][24][level1Name]", "")
      .formParam("layout[ColumnGroupingProperties][24][level2Name]", "")
      .formParam("layout[ColumnGroupingProperties][24][formatString]", "")
      .formParam("layout[ColumnGropingLevelCount]", "0")
      .formParam("layout[RepeatColumnHeader]", "True")
      .formParam("layout[HideDetails]", "False")
      .formParam("layout[GroupBandProperties][0][GroupColumnName]", "location_name")
      .formParam("layout[GroupBandProperties][0][showDefaultHeader]", "false")
      .formParam("layout[GroupBandProperties][0][showDefaultFooter]", "false")
      .formParam("layout[GroupBandProperties][0][headerColumnCount]", "1")
      .formParam("layout[GroupBandProperties][0][showHeader]", "true")
      .formParam("layout[GroupBandProperties][0][showFooter]", "false")
      .formParam("layout[GroupBandProperties][0][groupHeaderPageBreak]", "BeforeBandExceptFirstEntry")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][0][Sequence]", "1")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][0][Description1]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][0][ColumnPosition1]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][0][Description2]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][0][ColumnPosition2]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][0][Description3]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][0][ColumnPosition3]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][0][Description4]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][0][ColumnPosition4]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][0][Description5]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][0][ColumnPosition5]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][0][SummaryType]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][1][Sequence]", "1")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][1][Description1]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][1][ColumnPosition1]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][1][Description2]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][1][ColumnPosition2]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][1][Description3]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][1][ColumnPosition3]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][1][Description4]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][1][ColumnPosition4]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][1][Description5]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][1][ColumnPosition5]", "")
      .formParam("layout[GroupBandProperties][0][GroupsummaryRowProperties][1][SummaryType]", "")
      .formParam("layout[GroupBandProperties][0][GroupHeaderProperties][0][Index]", "0")
      .formParam("layout[GroupBandProperties][0][GroupHeaderProperties][0][Name]", "Entity")
      .formParam("layout[GroupBandProperties][0][GroupHeaderProperties][0][TypeName]", "")
      .formParam("layout[GroupBandProperties][0][GroupHeaderProperties][0][Type]", "")
      .formParam("layout[GroupBandProperties][0][GroupHeaderProperties][1][Index]", "0")
      .formParam("layout[GroupBandProperties][0][GroupHeaderProperties][1][Name]", "Date Range")
      .formParam("layout[GroupBandProperties][0][GroupHeaderProperties][1][TypeName]", "")
      .formParam("layout[GroupBandProperties][0][GroupHeaderProperties][1][Type]", "")
      .formParam("layout[GroupBandProperties][0][GroupHeaderProperties][2][Index]", "0")
      .formParam("layout[GroupBandProperties][0][GroupHeaderProperties][2][Name]", "Group By")
      .formParam("layout[GroupBandProperties][0][GroupHeaderProperties][2][TypeName]", "")
      .formParam("layout[GroupBandProperties][0][GroupHeaderProperties][2][Type]", "")
      .formParam("layout[GroupBandProperties][1][GroupColumnName]", "Claim Budget Group")
      .formParam("layout[GroupBandProperties][1][showDefaultHeader]", "false")
      .formParam("layout[GroupBandProperties][1][showDefaultFooter]", "false")
      .formParam("layout[GroupBandProperties][1][headerColumnCount]", "1")
      .formParam("layout[GroupBandProperties][1][showHeader]", "true")
      .formParam("layout[GroupBandProperties][1][showFooter]", "false")
      .formParam("layout[GroupBandProperties][1][groupHeaderPageBreak]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][0][Sequence]", "1")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][0][Description1]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][0][ColumnPosition1]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][0][Description2]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][0][ColumnPosition2]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][0][Description3]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][0][ColumnPosition3]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][0][Description4]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][0][ColumnPosition4]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][0][Description5]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][0][ColumnPosition5]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][0][SummaryType]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][1][Sequence]", "1")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][1][Description1]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][1][ColumnPosition1]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][1][Description2]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][1][ColumnPosition2]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][1][Description3]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][1][ColumnPosition3]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][1][Description4]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][1][ColumnPosition4]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][1][Description5]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][1][ColumnPosition5]", "")
      .formParam("layout[GroupBandProperties][1][GroupsummaryRowProperties][1][SummaryType]", "")
      .formParam("layout[GroupBandProperties][1][GroupHeaderProperties][0][Index]", "0")
      .formParam("layout[GroupBandProperties][1][GroupHeaderProperties][0][Name]", "Claim Budget Group")
      .formParam("layout[GroupBandProperties][1][GroupHeaderProperties][0][TypeName]", "")
      .formParam("layout[GroupBandProperties][1][GroupHeaderProperties][0][Type]", "")
      .formParam("TemplateId", "141")
      .formParam("ReportId", "114")
      .check(bodyString.saveAs("reportBody"))
    )
      .pause(464.milliseconds)
      .exec(session => {
        val body = session("reportBody").as[String]
        println(s"Body :$body")
        session
      })
  }

  def logout = {
    exec(http("Log out")
      .post("/Account/LogOff")
      .formParam("__RequestVerificationToken", "${__RequestVerificationTokenLogout}")
      .formParam("DXScript", "1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_270,1_286,1_289,1_183,17_42,17_3,1_285,1_188,17_8,1_297,1_192,17_10,1_287,1_194,1_193,17_11,1_208,1_216,1_301,1_253,1_234,1_246,1_302,1_221,17_12,1_296,1_295,1_278,17_41,1_189,1_222,1_290,1_288,1_195,1_255,1_262,1_261,1_254,1_251,1_258,1_252,1_260,1_257,1_256,1_247,1_243,1_241,1_250,1_249,1_248,1_245,1_244,1_259,1_240,1_237,1_238,1_239,1_242,17_15,17_17,1_271,1_272,17_19,1_273,1_274,17_20,17_21,1_223,17_14,1_276,17_24,17_28,1_280,17_25,1_293,17_27,1_291,1_294,17_32,1_298,17_36,17_40,1_197,17_1,1_207,1_235,17_16,6_18,6_16,6_15,6_14,6_17,17_39,1_212,1_196,17_0,1_198,17_2,1_199,17_4,1_200,1_201,1_202,1_204,1_218,1_205,17_7,1_211,17_23,1_206,17_9,1_275,1_214,1_215,17_22,1_213,1_217,17_38,1_219,1_232,1_233,1_231,17_5,1_191,1_284,18_36,18_38,18_33,18_42,18_37,18_35,17_31,1_203,1_283,9_54,9_55,24_379,24_389,9_57,9_56,17_44,9_45,9_47,9_46,17_30,9_51,9_48,9_31,17_29,9_50,9_41,9_53,9_52,9_49")
      .formParam("DXCss", "/Content/css/root?v=fQqb8rdb3SX3t_q5clLhrjqLMPJRz5XyrffvnRHeaqY1,0_2312,1_50,1_53,1_51,0_2317,1_40,1_17,0_2214,1_16,0_2219,0_2221,0_2225,1_18,1_4,0_2279,6_3,0_2283,0_2186,0_2190,0_2257,18_3,18_11,18_7,0_2261,0_2313,1_34,24_359,24_364,24_360,9_19,9_15,9_12,0_2338,9_1,0_2342,9_4,1_7,/Content/ExecutiveDashboard/ExecutiveDashboardBundle?v=K3bp7bOUCg7jvMi3yCOp8VvRDHaxkZJNkgNJYDsPeIA1,/Content/ExecutiveDashboardBundle?v=yudLVP8cmmFF7pYfIl5_OmdH-W3uaCGxdSLyC-jbYQo1,/Content/notifications.css,/Content/jquery-ui.css,/Content/PayrollProcess.css")
      .check(status.is(302)))
      .exec(http("request_92")
        .get("/Account/Login")
      )
      .exec(http("request_93")
        .get("/bundles/jquery?v=_pxGe3mY2bQf-xjm4AiFp6ZjEyA5oTa8PuEQsuJbzEk1")
      )
      .exec(http("request_94")
        .get("/DXR.axd?r=1_58-N3Vxm")
      )
      .exec(http("request_95")
        .get("/DXR.axd?r=1_17,0_2214,1_50,1_53,1_51,1_16,0_2219,0_2312,0_2317-O3Vxm")
      )
      .exec(http("request_96")
        .get("/Content/css?v=w9USDPGryprQSMA62T1giyRXrtqAIG-BphxyQY0Qw_w1")
      )
      .exec(http("request_97")
        .get("/DXR.axd?r=1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_208,1_216,1_212,1_189,1_222,17_42,1_297,1_215,1_207,1_289,1_205,17_7,1_287,1_211,17_23,1_197,17_1-N3Vxm")
      )
      .exec(http("request_98")
        .get("/Content/fonts/icomoon.ttf?5vru0d")
      )
      .pause(141.milliseconds)
      .exec(http("request_99")
        .get("/Content/Images/bg-login.jpg?V=03")
      )
  }

}
