package computerdatabase.Module.Leave

import io.gatling.core.Predef._
import io.gatling.http.Predef._

import scala.concurrent.duration._

object ESSEMPMyLeaveApplication {

  val uri1 = "https://maps.googleapis.com/maps/api/js"
  val uri3 = "https://fonts.googleapis.com/css"

  def loadApplication = {
    exec(http("Load My Leave Application Page")
      .get("/profile/leave_lst.aspx?Mode=E")
      .check(regex("""<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="(|.+?)" />""").saveAs("viewStateMLA"))

      .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtDateFrom']", "value").saveAs("txtDateFrom"))
      .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtDateTo']", "value").saveAs("txtDateTo"))

      .check(bodyString.saveAs("MLABody"))
    )
      .pause(256.milliseconds)
      .exec(http("request_52")
        .get(uri3 + "?family=Open+Sans:300,400,600,700")
      )
      .exec(http("request_53")
        .get(uri3 + "?family=Roboto:400,300,500,700")
      )
      .exec(http("request_54")
        .get("/ScriptResource.axd?d=XGoPW3Unw0ILT0eb9sSUayB1PCvz0eeMXm23ajXUnLKSVWvpEIM7qNdgqQtwIk3oGSO-umSPRJr1BQNhALudg4-gDqI9ltlNkOQMrPf4fNHBEAhja6GHf4He4_YSEbkQ4L1Bsn1aV_AF11ks4fQlTNxlg6tYk_UGpXjfNcFSD6D49VS2gjNTnElk4fHlLsM90&t=51e37521")
      )
      .exec(http("request_55")
        .get("/ScriptResource.axd?d=uvA9ANM76Fbpm1FfUlagnYp2obqkhmwI_C-NoQ89dB6TwrO7THFVAk1nHl1QRi68J_pozjXYUJHgZb6l02O3dvVqjaOzdIW44mTvv4FyAQ5MvnVeKZmB7OtG9BNkATLGOGWXvK2djBpsGpZ_x3Mi2KdwGSD0SZeW5VvD940G1Y8Cml0nm6ok2UFWSXa6k4SQ0&t=51e37521")
      )
      .exec(http("request_56")
        .get("/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZOYXOnLy43dRx8HCf3vqtm7Uk9Dd5QTT0bKPZkChPJpkGd7et7925jgqVFYijtH4BlZm86YPMFKavMb3jiNdHO_DkODjc9ASxqTpYjlOyMlE0&t=637505973787431984")
      )
      .exec(http("request_57")
        .get("/ScriptResource.axd?d=P5lTttoqSeZXoYRLQMIScIf12FcrWAiNVtlJxQA9qnTW6iJpMmht7uXNg23QNwOPVke9qF6NTd062q-kq39p4MmkxhZ1ti3ckmNVSJHDik9HIeiTEBJ8AeazBYyjXlRbQWV2Q8-MBT7ldJqGwC6gtX5XcIt2Wd4nEFDQxuD-poI1&t=51e37521")
      )
      .exec(http("request_58")
        .get("/ScriptResource.axd?d=x6wALODbMJK5e0eRC_p1LTFBEqAduy6yzdGuAMP1dHrya3_IF2A8CsbaRF-ARwHq6m-SGT1rW_kEfDOVxpLiOwBwjQzZMYd6yIJvZ9ubgIyIzxTTWWPxLOJ6h2brQiXEeYW7vHWkdtbfdWvIHio91FSsDXmcUmI7kjdMETOH_XE1&t=51e37521")
      )
      .pause(129.milliseconds)
      .exec(http("request_59")
        .post("/verify_access.ashx")
      )
      .exec(http("request_60")
        .get("/profile/leave_lst.aspx?_TSM_CombinedScripts_=True&v=ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1&_TSM_Bundles_=&cdn=False")
      )
      .pause(287.milliseconds)
      .exec(http("request_61")
        .get("/Content/ESS/fonts/icomoon.ttf?5vru0d")
      )
      .exec(http("request_62")
        .get("/Notifications/GetNotificationCounts")
      )
      .exec(http("request_63")
        .get("/Account/VerifyAccess")
      )
      .exec(http("request_64")
        .get("/Notifications/ViewNotifications?type=g2ms+igOEMbBASEK5BtZakq8ABz0jXlz/i82TY5qYm4arDUV21V7rRlvk7t79N89NwlGmR0oWHBxgUQtQiOa55f9Jx/dksNurtcqRFM1FGs4GNidF3jptOW5AccIciBp86ka/t4aY+jRbY3j1PMpiaQBa3C0PTqTpjHORJccbLA=")
      )
      .pause(193.milliseconds)
      .exec(http("request_65")
        .get("/Account/VerifyAccess")
      )
      .exec(http("request_66")
        .get("/Notifications/GetNotificationsList?row=8")
      )
      .pause(9)
  }

  def searchMLADate = {
    exec(http("Search MLA Date")
      .post("/profile/leave_lst.aspx?Mode=E")

      .formParam("__EVENTTARGET", "ctl00$ctl00$ctl00$cntPlcHldrContent$btnSearch")
      .formParam("__EVENTARGUMENT", "")
      .formParam("_TSM_HiddenField_", "ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1")
      .formParam("__LASTFOCUS", "")
      .formParam("__VIEWSTATE", "${viewStateMLA}")
      .formParam("__VIEWSTATEGENERATOR", "6F1287B2")
      .formParam("ctl00$ctl00$ctl00$selCultureName", "")
      .formParam("ctl00$ctl00$ctl00$selCountry", "1")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfViewBy", "E")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfStoreAsHr", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtDateFrom", "${txtDateFrom}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtDateTo", "${txtDateTo}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtStatus", "Pending; Approved")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$cbStatus$0", "P")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$cbStatus$1", "A")
      .check(regex("""<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="(|.+?)" />""").saveAs("viewStateMLA2"))
      .check(bodyString.saveAs("MLABody2"))
    )
      .pause(161.milliseconds)
      .exec(http("request_68")
        .get(uri3 + "?family=Open+Sans:300,400,600,700")
      )
      .exec(http("request_69")
        .get(uri3 + "?family=Roboto:400,300,500,700")
      )
      .exec(http("request_70")
        .get("/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZOYXOnLy43dRx8HCf3vqtm7Uk9Dd5QTT0bKPZkChPJpkGd7et7925jgqVFYijtH4BlZm86YPMFKavMb3jiNdHO_DkODjc9ASxqTpYjlOyMlE0&t=637505973787431984")
      )
      .exec(http("request_71")
        .get("/ScriptResource.axd?d=P5lTttoqSeZXoYRLQMIScIf12FcrWAiNVtlJxQA9qnTW6iJpMmht7uXNg23QNwOPVke9qF6NTd062q-kq39p4MmkxhZ1ti3ckmNVSJHDik9HIeiTEBJ8AeazBYyjXlRbQWV2Q8-MBT7ldJqGwC6gtX5XcIt2Wd4nEFDQxuD-poI1&t=51e37521")
      )
      .exec(http("request_72")
        .get("/ScriptResource.axd?d=XGoPW3Unw0ILT0eb9sSUayB1PCvz0eeMXm23ajXUnLKSVWvpEIM7qNdgqQtwIk3oGSO-umSPRJr1BQNhALudg4-gDqI9ltlNkOQMrPf4fNHBEAhja6GHf4He4_YSEbkQ4L1Bsn1aV_AF11ks4fQlTNxlg6tYk_UGpXjfNcFSD6D49VS2gjNTnElk4fHlLsM90&t=51e37521")
      )
      .exec(http("request_73")
        .get("/ScriptResource.axd?d=uvA9ANM76Fbpm1FfUlagnYp2obqkhmwI_C-NoQ89dB6TwrO7THFVAk1nHl1QRi68J_pozjXYUJHgZb6l02O3dvVqjaOzdIW44mTvv4FyAQ5MvnVeKZmB7OtG9BNkATLGOGWXvK2djBpsGpZ_x3Mi2KdwGSD0SZeW5VvD940G1Y8Cml0nm6ok2UFWSXa6k4SQ0&t=51e37521")
      )
      .exec(http("request_74")
        .get("/ScriptResource.axd?d=x6wALODbMJK5e0eRC_p1LTFBEqAduy6yzdGuAMP1dHrya3_IF2A8CsbaRF-ARwHq6m-SGT1rW_kEfDOVxpLiOwBwjQzZMYd6yIJvZ9ubgIyIzxTTWWPxLOJ6h2brQiXEeYW7vHWkdtbfdWvIHio91FSsDXmcUmI7kjdMETOH_XE1&t=51e37521")
      )
      .pause(149.milliseconds)
      .exec(http("request_75")
        .post("/verify_access.ashx")
      )
      .exec(http("request_76")
        .get("/profile/leave_lst.aspx?_TSM_CombinedScripts_=True&v=ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1&_TSM_Bundles_=&cdn=False")
      )
      .exec(http("request_77")
        .get("/Content/ESS/fonts/icomoon.ttf?5vru0d")
      )
      .pause(326.milliseconds)
      .exec(http("request_78")
        .get("/Notifications/GetNotificationCounts")
      )
      .exec(http("request_79")
        .get("/Account/VerifyAccess")
      )
      .exec(http("request_80")
        .get("/Notifications/ViewNotifications?type=qw/EWbWsSRhm4Oh66DDVPTU67QQrwecHai0h6nm9UdyX5mgBV5AiH3Q6E/6BkfCEZ4RQb4y9zE7AqsqnsvGRA4mRCd4aLggCZwkEnO2pjCNhXatZT3oBb/CGG6gX44AOTGi6u+fT2lBg6D5HLCwWWDrq8b/tZUqcif+o5QBvR2U=")
      )
      .pause(205.milliseconds)
      .exec(http("request_81")
        .get("/Account/VerifyAccess")
      )
      .exec(http("request_82")
        .get("/Notifications/GetNotificationsList?row=8")
      )
      .pause(14)
  }

  def displayList = {
    exec(http("Display List of Leave Form")
      .post("/profile/leave_lst.aspx?Mode=E")
      .formParam("__EVENTTARGET", "ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$gvSearch$ctl02$ctl00")
      .formParam("__EVENTARGUMENT", "")
      .formParam("_TSM_HiddenField_", "ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1")
      .formParam("__LASTFOCUS", "")
      .formParam("__VIEWSTATE", "${viewStateMLA2}")
      .formParam("__VIEWSTATEGENERATOR", "6F1287B2")
      .formParam("ctl00$ctl00$ctl00$selCultureName", "")
      .formParam("ctl00$ctl00$ctl00$selCountry", "1")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfViewBy", "E")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfStoreAsHr", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtDateFrom", "${txtDateFrom}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtDateTo", "${txtDateTo}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtStatus", "Pending")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$cbStatus$0", "P")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$gvSearch$ctl07$gpCustomPager$txtPageSize", "50")
      .check(status.is(200))
      .check(header("Location").saveAs("url"))

    )

      .exec(http("Load Request Form Based on Request ID CLicked")
        .get("${url}")
        .check(bodyString.saveAs("MLABody3"))
        .check(regex("""<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="(|.+?)" />""").saveAs("viewStateMLA3"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMode']", "value").saveAs("fmode"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfView']", "value").saveAs("fview"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfInfoID']", "value").saveAs("finfoID"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMonitorID']", "value").saveAs("fmonitorID"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAgentID']", "value").saveAs("fagentID"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBalance']", "value").saveAs("fBalance"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAdvanceBalance']", "value").saveAs("fABalance"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveCode']", "value").saveAs("fLeaveCode"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfDataSet']", "value").saveAs("fDataSet"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLSplitFlag']", "value").saveAs("fSplitFlag"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFinYear']", "value").saveAs("fFinYear"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFinStartDate']", "value").saveAs("fFinSDate"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSickLeaveEnable']", "value").saveAs("fsickEnable"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowApproverEnable']", "value").saveAs("fWApprove"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowFormLeaveRelieverEnable']", "value").saveAs("fWFormLeave"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmploymentID']", "value").saveAs("fEmployID"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLocationID']", "value").saveAs("fLocID"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmpCountryCode']", "value").saveAs("fcountryCode"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveType']", "value").saveAs("fLeaveType"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveUnit']", "value").saveAs("fLeaveUnit"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfHoursPerDay']", "value").saveAs("fhoursPDay"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAttachmentFlag']", "value").saveAs("fattachFlag"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfApplicationStartDate']", "value").saveAs("fAppStartDate"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeavePeriod']", "value").saveAs("fleavePeriod"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfApplicationMethod']", "value").saveAs("fappMethod"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequiredApproverRemarks']", "value").saveAs("fAppRemarks"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReasonFlag']", "value").saveAs("freasonFlag"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNoticePeriod']", "value").saveAs("fNPeriod"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBlockType']", "value").saveAs("fBlockType"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBalanceMethod']", "value").saveAs("fBalanceMeth"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfStartDate']", "value").saveAs("fStartDate"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEndDate']", "value").saveAs("fEndDate"))
        //.check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$cbChkAll']", "value").saveAs("fchkAll"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$cbChkChild0']", "value").saveAs("fChild0"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFrom0']", "value").saveAs("fFrom0"))
        .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTo0']", "value").saveAs("fTo0"))
        //.check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selCnlReason0']", "value").saveAs("fReason0"))

      )
      .exec(http("request_2")
        .get("/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZOYXOnLy43dRx8HCf3vqtm7Uk9Dd5QTT0bKPZkChPJpkGd7et7925jgqVFYijtH4BlZm86YPMFKavMb3jiNdHO_DkODjc9ASxqTpYjlOyMlE0&t=637505973787431984")
      )
      .exec(http("request_3")
        .get("/ScriptResource.axd?d=x6wALODbMJK5e0eRC_p1LTFBEqAduy6yzdGuAMP1dHrya3_IF2A8CsbaRF-ARwHq6m-SGT1rW_kEfDOVxpLiOwBwjQzZMYd6yIJvZ9ubgIyIzxTTWWPxLOJ6h2brQiXEeYW7vHWkdtbfdWvIHio91FSsDXmcUmI7kjdMETOH_XE1&t=51e37521")
      )
      .exec(http("request_4")
        .get("/ScriptResource.axd?d=P5lTttoqSeZXoYRLQMIScIf12FcrWAiNVtlJxQA9qnTW6iJpMmht7uXNg23QNwOPVke9qF6NTd062q-kq39p4MmkxhZ1ti3ckmNVSJHDik9HIeiTEBJ8AeazBYyjXlRbQWV2Q8-MBT7ldJqGwC6gtX5XcIt2Wd4nEFDQxuD-poI1&t=51e37521")
      )
      .exec(http("request_5")
        .get("/ScriptResource.axd?d=XGoPW3Unw0ILT0eb9sSUayB1PCvz0eeMXm23ajXUnLKSVWvpEIM7qNdgqQtwIk3oGSO-umSPRJr1BQNhALudg4-gDqI9ltlNkOQMrPf4fNHBEAhja6GHf4He4_YSEbkQ4L1Bsn1aV_AF11ks4fQlTNxlg6tYk_UGpXjfNcFSD6D49VS2gjNTnElk4fHlLsM90&t=51e37521")
      )
      .exec(http("request_6")
        .get("/ScriptResource.axd?d=uvA9ANM76Fbpm1FfUlagnYp2obqkhmwI_C-NoQ89dB6TwrO7THFVAk1nHl1QRi68J_pozjXYUJHgZb6l02O3dvVqjaOzdIW44mTvv4FyAQ5MvnVeKZmB7OtG9BNkATLGOGWXvK2djBpsGpZ_x3Mi2KdwGSD0SZeW5VvD940G1Y8Cml0nm6ok2UFWSXa6k4SQ0&t=51e37521")
      )
      .exec(http("request_7")
        .get("/DXR.axd?r=0_2312,1_50,1_53,1_51,0_2317-O3Vxm")
      )
      .exec(http("request_8")
        .get("/WebResource.axd?d=G7AEkw1asyYfSFk2Li5D0JhwAppflyxkpGSQDQbA3YX7Us59q1SeSvJlGoBadgH42WWogzokgjSTil628NjzJ-ho-6akTSnjNL_1W4rKMdV6J4E7SFdllL-EXlbUGTEk-wfRgTKBSFluXwws9OgQSz64mOsqxEoa9Z9MfmluHcdALHev8eL9dk6DjmuJdzHl0&t=637529727625595181")
      )
      .exec(http("request_9")
        .get("/ScriptResource.axd?d=nv7asgRUU0tRmHNR2D6t1HncJC0uSlzSoOMFzQL9KDgdtj1yUByaaYlMWCLR1tfb0zRr2KS8GU92MXS6P0lOX_vkDPQOiW6UvV384GibJ__q8DVUhGPtg7X0IEAXecIS6jMaZIGfhYY2bHennMwScvTacu4aYi7pwkjCfDx4XDhghn49oiHENcEjRtCYLFUt0&t=fffffffff6474071")
      )
      .exec(http("request_10")
        .get(uri3 + "?family=Open+Sans:300,400,600,700")
      )
      .exec(http("request_11")
        .get(uri3 + "?family=Roboto:400,300,500,700")
      )
      .exec(http("request_12")
        .get("/request/leave_form.aspx?_TSM_CombinedScripts_=True&v=ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1&_TSM_Bundles_=&cdn=False")
      )
      .exec(http("request_13")
        .get("/DXR.axd?r=1_303,1_184,1_297,1_210,1_220,1_187,1_181,1_289,1_287-N3Vxm")
      )
      .exec(http("request_14")
        .post("/verify_access.ashx")
      )
      .exec(http("request_15")
        .get("/DXR.axd?r=1_58-N3Vxm")
      )
      .exec(http("request_16")
        .get("/Content/ESS/fonts/icomoon.ttf?5vru0d")
      )
      .pause(765.milliseconds)
      .exec(http("request_17")
        .get("/Notifications/GetNotificationCounts")
      )
      .exec(http("request_18")
        .get("/Notifications/ViewNotifications?type=ZnYPbQkKAqv4rzZJMqZkUToC/G8hjkpKkxZ7uKNLe3KT1TP3eVCRy5+vpLRCOpmMGaS6F4KCaJh2jX5Shzkc1MjZ5/E8FlEdT9gHYmAK5enPy8xtTZaBQMA1WJM7Gx3q6pbp9n3j3Nro82kZDliiJsyr9daB06uFxuKItR1wyHo=")
      )
      .exec(http("request_19")
        .post("/request/get_leave_reason.ashx")

        .formParam("LeaveType", "A")
        .formParam("EmployeeID", "")
        .formParam("EmploymentID", "9126")
        .formParam("EmployeeNo", "")
        .formParam("StartDate", "undefined 00:00")
        .formParam("EndDate", "undefined 00:00")
        .formParam("LocationID", "9"))
      .pause(288.milliseconds)
      .exec(http("request_20")
        .get("/Notifications/GetNotificationsList?row=8")
      )
      .pause(7)
  }

  def submitWithdraw = {
    exec(http("Withdraw the Leave Form")
      .post("${url}")

      .formParam("__EVENTTARGET", "ctl00$ctl00$ctl00$cntPlcHldrContent$btnWithdraw")
      .formParam("__EVENTARGUMENT", "")
      .formParam("_TSM_HiddenField_", "ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1")
      .formParam("__VIEWSTATE", "${viewStateMLA3}")
      .formParam("__VIEWSTATEGENERATOR", "DD360C3C")
      .formParam("ctl00$ctl00$ctl00$selCultureName", "")
      .formParam("ctl00$ctl00$ctl00$selCountry", "1")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfAttachID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfFileName", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfFileType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfAttachSrc", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMode", "${fmode}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfView", "${fview}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfInfoID", "${finfoID}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMonitorID", "${fmonitorID}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAgentID", "${fagentID}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNewAttach", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfOldAttach", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBalance", "${fBalance}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAdvanceBalance", "${fABalance}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTotalApplied", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkipExceed", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveCode", "${fLeaveCode}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReason", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfDataSet", "${fDataSet}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfActualLeaveDate", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTotalAttached", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLSplitFlag", "${fSPlitFlag}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLDateSplit", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLLeaveCode", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferAgentID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferMonitorID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferWFStatus", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferRedirectURL", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfCancelAction", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFinYear", "${fFinYear}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFinStartDate", "${fFinSDate}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkipConfAllow", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplacementDate", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplLeavePeriodFlag", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplCreditLeaveType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplReplacedQty", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAdvanceFlag", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSickLeaveEnable", "${fsickEnable}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowApproverEnable", "${fWApprove}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowApproverPopup", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowFormLeaveRelieverEnable", "${fWFormLeave}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequestorID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequestorNo", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmploymentID", "${fEmployID}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLocationID", "${fLocID}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmpCountryCode", "${fcountryCode}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmpBirthDate", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvRequestorEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveType", "${fLeaveType}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveUnit", "${fLeaveUnit}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfHoursPerDay", "${fhoursPDay}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAttachmentFlag", "${fattachFlag}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfApplicationStartDate", "${fAppStartDate}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeavePeriod", "${fleavePeriod}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfApplicationMethod", "${fappMethod}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequiredApproverRemarks", "${fAppRemarks}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReasonFlag", "${freasonFlag}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNoticePeriod", "${fNPeriod}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBlockType", "${fBlockType}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEventType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEventEntitlementUnit", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfValidatePeriodType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveCancelType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeavePolicyMsg", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmergencyQty", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmergencyFlag", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmergencyControlFlag", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBalanceMethod", "${fBalanceMeth}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvLeaveTypeEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvPeriodEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$cusvPeriodEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplaceVisible", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelation", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelationNoticePeriod", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelationEventEntitlementUnit", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelationValidityPeriodType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfStartDate", "${fStartDate}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvStartDateEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEndDate", "${fEndDate}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvEndDateEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$cusvReasonEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReliever", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelieverNo", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWFApprover", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWFApproverNo", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTSProjectCode", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFrom0", "${fFrom0}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTo0", "${fTo0}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$popupControlState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
      .formParam("DXScript", "1_303,1_184,1_297,1_210,1_220,1_187,1_181,1_289,1_287")
      .formParam("DXCss", "0_2312,1_50,1_53,1_51,0_2317,../Content/jquery.jscrollpane.css,../Content/ESS/bootstrap.css,../Content/ESS/NewUIStyle.css,../Content/ESS/ResponsiveSite.css,../Content/generic.light.custom.css,../Content/ESS/font-style.css,https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css,../Content/jquery.orgchart.css,../Content/ESS/style.css,../Content/ESS/component.css,../Content/ESS/alert.css,../Content/ESS/custom/jquery-ui-1.10.3.custom.min.css,../Content/jquery.mmenu.css,../Content/notifications.css,https://orisoftst.orisoftsaas.com/Content/ESS/jquery.ui.timepicker.css,/WebResource.axd?d=G7AEkw1asyYfSFk2Li5D0JhwAppflyxkpGSQDQbA3YX7Us59q1SeSvJlGoBadgH42WWogzokgjSTil628NjzJ-ho-6akTSnjNL_1W4rKMdV6J4E7SFdllL-EXlbUGTEk-wfRgTKBSFluXwws9OgQSz64mOsqxEoa9Z9MfmluHcdALHev8eL9dk6DjmuJdzHl0&t=637529727625595181"))
      .exec(http("request_22")
        .get("/DXR.axd?r=0_2312,1_50,1_53,1_51,0_2317-O3Vxm")
      )
      .exec(http("request_23")
        .get("/WebResource.axd?d=G7AEkw1asyYfSFk2Li5D0JhwAppflyxkpGSQDQbA3YX7Us59q1SeSvJlGoBadgH42WWogzokgjSTil628NjzJ-ho-6akTSnjNL_1W4rKMdV6J4E7SFdllL-EXlbUGTEk-wfRgTKBSFluXwws9OgQSz64mOsqxEoa9Z9MfmluHcdALHev8eL9dk6DjmuJdzHl0&t=637529727625595181")
      )
      .exec(http("request_24")
        .get("/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZOYXOnLy43dRx8HCf3vqtm7Uk9Dd5QTT0bKPZkChPJpkGd7et7925jgqVFYijtH4BlZm86YPMFKavMb3jiNdHO_DkODjc9ASxqTpYjlOyMlE0&t=637505973787431984")
      )
      .exec(http("request_25")
        .get("/ScriptResource.axd?d=nv7asgRUU0tRmHNR2D6t1HncJC0uSlzSoOMFzQL9KDgdtj1yUByaaYlMWCLR1tfb0zRr2KS8GU92MXS6P0lOX_vkDPQOiW6UvV384GibJ__q8DVUhGPtg7X0IEAXecIS6jMaZIGfhYY2bHennMwScvTacu4aYi7pwkjCfDx4XDhghn49oiHENcEjRtCYLFUt0&t=fffffffff6474071")
      )
      .exec(http("request_26")
        .get("/ScriptResource.axd?d=x6wALODbMJK5e0eRC_p1LTFBEqAduy6yzdGuAMP1dHrya3_IF2A8CsbaRF-ARwHq6m-SGT1rW_kEfDOVxpLiOwBwjQzZMYd6yIJvZ9ubgIyIzxTTWWPxLOJ6h2brQiXEeYW7vHWkdtbfdWvIHio91FSsDXmcUmI7kjdMETOH_XE1&t=51e37521")
      )
      .exec(http("request_27")
        .get("/ScriptResource.axd?d=P5lTttoqSeZXoYRLQMIScIf12FcrWAiNVtlJxQA9qnTW6iJpMmht7uXNg23QNwOPVke9qF6NTd062q-kq39p4MmkxhZ1ti3ckmNVSJHDik9HIeiTEBJ8AeazBYyjXlRbQWV2Q8-MBT7ldJqGwC6gtX5XcIt2Wd4nEFDQxuD-poI1&t=51e37521")
      )
      .exec(http("request_28")
        .get("/request/leave_form.aspx?_TSM_CombinedScripts_=True&v=ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1&_TSM_Bundles_=&cdn=False")
      )
      .exec(http("request_29")
        .get("/ScriptResource.axd?d=XGoPW3Unw0ILT0eb9sSUayB1PCvz0eeMXm23ajXUnLKSVWvpEIM7qNdgqQtwIk3oGSO-umSPRJr1BQNhALudg4-gDqI9ltlNkOQMrPf4fNHBEAhja6GHf4He4_YSEbkQ4L1Bsn1aV_AF11ks4fQlTNxlg6tYk_UGpXjfNcFSD6D49VS2gjNTnElk4fHlLsM90&t=51e37521")
      )
      .exec(http("request_30")
        .get("/ScriptResource.axd?d=uvA9ANM76Fbpm1FfUlagnYp2obqkhmwI_C-NoQ89dB6TwrO7THFVAk1nHl1QRi68J_pozjXYUJHgZb6l02O3dvVqjaOzdIW44mTvv4FyAQ5MvnVeKZmB7OtG9BNkATLGOGWXvK2djBpsGpZ_x3Mi2KdwGSD0SZeW5VvD940G1Y8Cml0nm6ok2UFWSXa6k4SQ0&t=51e37521")
      )
      .exec(http("request_31")
        .get("/DXR.axd?r=1_303,1_184,1_297,1_210,1_220,1_187,1_181,1_289,1_287-N3Vxm")
      )
      .exec(http("request_32")
        .get("/DXR.axd?r=1_58-N3Vxm")
      )
      .exec(http("request_33")
        .get(uri3 + "?family=Open+Sans:300,400,600,700")
      )
      .exec(http("request_34")
        .get(uri3 + "?family=Roboto:400,300,500,700")
      )
      .pause(113.milliseconds)
      .exec(http("request_35")
        .post("/verify_access.ashx")
      )
      .pause(185.milliseconds)
      .exec(http("request_36")
        .get("/Content/ESS/fonts/icomoon.ttf?5vru0d")
      )
      .pause(476.milliseconds)
      .exec(http("request_37")
        .get("/Notifications/GetNotificationCounts")
      )
      .exec(http("request_38")
        .get("/Notifications/ViewNotifications?type=AKJtTxCXxu2jxln0s54CuwM7FZIOT8MkFs0g0cWxak9MG1CcZl7K+37lVlaVIGNvne7DqC8R4FvGukZUsEm6g2daVUKM1zZ3N7q9S7QXuoV5e02GuUTXzKzhPM6+rGcVwCRf+LApSpo4XOO2bK9mrrZKs5sxUBSJJqbkKuWbjkI=")
      )
      .pause(455.milliseconds)
      .exec(http("request_39")
        .get("/Notifications/GetNotificationsList?row=8")
      )
      .exec(http("request_40")
        .post("/request/get_leave_reason.ashx")

        .formParam("LeaveType", "A")
        .formParam("EmployeeID", "")
        .formParam("EmploymentID", "9126")
        .formParam("EmployeeNo", "")
        .formParam("StartDate", "undefined 00:00")
        .formParam("EndDate", "undefined 00:00")
        .formParam("LocationID", "9"))
      .pause(3)
      .exec(http("Load Request Form List in My Workflow")
        .get("/works/request_lst.aspx")
        .check(regex("""<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="(|.+?)" />""").saveAs("viewStateMLA4"))
      )
      .exec(http("request_42")
        .get("/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZOYXOnLy43dRx8HCf3vqtm7Uk9Dd5QTT0bKPZkChPJpkGd7et7925jgqVFYijtH4BlZm86YPMFKavMb3jiNdHO_DkODjc9ASxqTpYjlOyMlE0&t=637505973787431984")
      )
      .exec(http("request_43")
        .get("/ScriptResource.axd?d=x6wALODbMJK5e0eRC_p1LTFBEqAduy6yzdGuAMP1dHrya3_IF2A8CsbaRF-ARwHq6m-SGT1rW_kEfDOVxpLiOwBwjQzZMYd6yIJvZ9ubgIyIzxTTWWPxLOJ6h2brQiXEeYW7vHWkdtbfdWvIHio91FSsDXmcUmI7kjdMETOH_XE1&t=51e37521")
      )
      .exec(http("request_44")
        .get("/ScriptResource.axd?d=P5lTttoqSeZXoYRLQMIScIf12FcrWAiNVtlJxQA9qnTW6iJpMmht7uXNg23QNwOPVke9qF6NTd062q-kq39p4MmkxhZ1ti3ckmNVSJHDik9HIeiTEBJ8AeazBYyjXlRbQWV2Q8-MBT7ldJqGwC6gtX5XcIt2Wd4nEFDQxuD-poI1&t=51e37521")
      )
      .exec(http("request_45")
        .get("/ScriptResource.axd?d=XGoPW3Unw0ILT0eb9sSUayB1PCvz0eeMXm23ajXUnLKSVWvpEIM7qNdgqQtwIk3oGSO-umSPRJr1BQNhALudg4-gDqI9ltlNkOQMrPf4fNHBEAhja6GHf4He4_YSEbkQ4L1Bsn1aV_AF11ks4fQlTNxlg6tYk_UGpXjfNcFSD6D49VS2gjNTnElk4fHlLsM90&t=51e37521")
      )
      .exec(http("request_46")
        .get("/ScriptResource.axd?d=uvA9ANM76Fbpm1FfUlagnYp2obqkhmwI_C-NoQ89dB6TwrO7THFVAk1nHl1QRi68J_pozjXYUJHgZb6l02O3dvVqjaOzdIW44mTvv4FyAQ5MvnVeKZmB7OtG9BNkATLGOGWXvK2djBpsGpZ_x3Mi2KdwGSD0SZeW5VvD940G1Y8Cml0nm6ok2UFWSXa6k4SQ0&t=51e37521")
      )
      .exec(http("request_47")
        .get("/works/request_lst.aspx?_TSM_CombinedScripts_=True&v=ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1&_TSM_Bundles_=&cdn=False")
      )
      .exec(http("request_48")
        .get(uri3 + "?family=Open+Sans:300,400,600,700")
      )
      .exec(http("request_49")
        .get(uri3 + "?family=Roboto:400,300,500,700")
      )
      .pause(112.milliseconds)
      .exec(http("request_50")
        .post("/verify_access.ashx")
      )
      .pause(181.milliseconds)
      .exec(http("request_51")
        .get("/Content/ESS/fonts/icomoon.ttf?5vru0d")
      )
      .pause(221.milliseconds)
      .exec(http("request_52")
        .get("/Notifications/GetNotificationCounts")
      )
      .exec(http("request_53")
        .get("/Notifications/ViewNotifications?type=VAA3fl+AkLT1YmkhAm9GUX+t1Q8rQDt/uAQPsiQ5ANlA/2TDu8G4jO+yz+ndOh9lyQpmPrD0Pmb5uH0kjp4F6rlKWcC75PprjIHbC/Nsty1hLSW71xO1jcg8VcOAqtkURfkyhvhRRYb4ySX/pZiwta5++Z+enJSFvz4kYKpK3iw=")
      )
      .pause(234.milliseconds)
      .exec(http("request_54")
        .get("/Notifications/GetNotificationsList?row=8")
      )
      .pause(9)
  }

  def logout = {
    exec(http("Submit Logout")
      .post("/profile/leave_lst.aspx?Mode=E")

      .formParam("__EVENTTARGET", "ctl00$ctl00$ctl00$lbLogout")
      .formParam("__EVENTARGUMENT", "")
      .formParam("_TSM_HiddenField_", "ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1")
      .formParam("__LASTFOCUS", "")
      .formParam("__VIEWSTATE", "${viewStateMLA}")
      .formParam("__VIEWSTATEGENERATOR", "6F1287B2")
      .formParam("ctl00$ctl00$ctl00$selCultureName", "")
      .formParam("ctl00$ctl00$ctl00$selCountry", "1")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfViewBy", "E")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfStoreAsHr", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtDateFrom", "${txtDateFrom}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtDateTo", "${txtDateTo}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtStatus", "Pending; Approved")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$cbStatus$0", "P")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$cbStatus$1", "A")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$gvSearch$ctl07$gpCustomPager$txtPageSize", "50")
      .check(status.is(302)))


      .exec(http("Load Login Page Part 2")
        .get("/Account/Login")
      )
      .exec(http("request_85")
        .get("/DXR.axd?r=1_17,0_2214,1_50,1_53,1_51,1_16,0_2219,0_2312,0_2317-4WXkk")
      )
      .exec(http("request_86")
        .get("/Content/css?v=w9USDPGryprQSMA62T1giyRXrtqAIG-BphxyQY0Qw_w1")
      )
      .exec(http("request_87")
        .get("/DXR.axd?r=1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_208,1_216,1_212,1_189,1_222,17_42,1_297,1_215,1_207,1_289,1_205,17_7,1_287,1_211,17_23,1_197,17_1-lUXkk")
      )
      .exec(http("request_88")
        .get("/DXR.axd?r=1_58-lUXkk")
      )
      .exec(http("request_89")
        .get("/bundles/jquery?v=w1vknpWt6KqlZcHeJQvaK6VbvvXt1Go8HcGH_DqKzzo1")
      )
      .pause(331.milliseconds)
      .exec(http("request_90")
        .get("/Content/Images/bg-login.jpg?V=03")
      )
      .exec(http("request_91")
        .get("/Content/fonts/icomoon.ttf?5vru0d")
      )
  }

}
