package computerdatabase.Module.Leave

import io.gatling.core.Predef._
import io.gatling.http.Predef._

import scala.concurrent.duration._
import scala.util.matching.Regex

object ESSEMPApplyLeave {

  val uri1 = "https://maps.googleapis.com/maps/api/js"
  val uri3 = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2"
  val uri4 = "https://fonts.googleapis.com/css"

  def loadLeaveForm = {

    exec(http("Load Leave Form")
      .get("/request/leave_form.aspx?View=O")
      .check(regex("""<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="(.+?)" />""").saveAs("viewState"))
      .check(css("input[name='ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBalance']", "value").saveAs("leaveBalance"))
      .check(status.is(200))
      .check(bodyString.saveAs("Body")))

      .exec(http("request_66")
        .get("/DXR.axd?r=0_2312,1_50,1_53,1_51,0_2317-fcfgm"))
      .exec(http("request_67")
        .get(uri4 + "?family=Open+Sans:300,400,600,700")
      )
      .exec(http("request_68")
        .get(uri4 + "?family=Roboto:400,300,500,700")
      )
      .exec(http("request_69")
        .get("/WebResource.axd?d=G7AEkw1asyYfSFk2Li5D0JhwAppflyxkpGSQDQbA3YX7Us59q1SeSvJlGoBadgH42WWogzokgjSTil628NjzJ-ho-6akTSnjNL_1W4rKMdV6J4E7SFdllL-EXlbUGTEk-wfRgTKBSFluXwws9OgQSz64mOsqxEoa9Z9MfmluHcdALHev8eL9dk6DjmuJdzHl0&t=637486420730234278")
      )
      .exec(http("request_70")
        .get("/DXR.axd?r=1_58-Ubfgm"))
      .exec(http("request_71")
        .get("/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZOYXOnLy43dRx8HCf3vqtm7Uk9Dd5QTT0bKPZkChPJpkGd7et7925jgqVFYijtH4BlZm86YPMFKavMb3jiNdHO_DkODjc9ASxqTpYjlOyMlE0&t=637454356754849868")
      )
      .exec(http("request_72")
        .get("/ScriptResource.axd?d=nv7asgRUU0tRmHNR2D6t1HncJC0uSlzSoOMFzQL9KDgdtj1yUByaaYlMWCLR1tfb0zRr2KS8GU92MXS6P0lOX_vkDPQOiW6UvV384GibJ__q8DVUhGPtg7X0IEAXecIS6jMaZIGfhYY2bHennMwScvTacu4aYi7pwkjCfDx4XDhghn49oiHENcEjRtCYLFUt0&t=ffffffffe191061b")
      )
      .exec(http("request_73")
        .get("/ScriptResource.axd?d=P5lTttoqSeZXoYRLQMIScIf12FcrWAiNVtlJxQA9qnTW6iJpMmht7uXNg23QNwOPVke9qF6NTd062q-kq39p4MmkxhZ1ti3ckmNVSJHDik9HIeiTEBJ8AeazBYyjXlRbQWV2Q8-MBT7ldJqGwC6gtX5XcIt2Wd4nEFDQxuD-poI1&t=51e37521")
      )
      .exec(http("request_74")
        .get("/ScriptResource.axd?d=x6wALODbMJK5e0eRC_p1LTFBEqAduy6yzdGuAMP1dHrya3_IF2A8CsbaRF-ARwHq6m-SGT1rW_kEfDOVxpLiOwBwjQzZMYd6yIJvZ9ubgIyIzxTTWWPxLOJ6h2brQiXEeYW7vHWkdtbfdWvIHio91FSsDXmcUmI7kjdMETOH_XE1&t=51e37521")
      )
      .exec(http("request_75")
        .get("/ScriptResource.axd?d=uvA9ANM76Fbpm1FfUlagnYp2obqkhmwI_C-NoQ89dB6TwrO7THFVAk1nHl1QRi68J_pozjXYUJHgZb6l02O3dvVqjaOzdIW44mTvv4FyAQ5MvnVeKZmB7OtG9BNkATLGOGWXvK2djBpsGpZ_x3Mi2KdwGSD0SZeW5VvD940G1Y8Cml0nm6ok2UFWSXa6k4SQ0&t=51e37521")
      )
      .exec(http("request_76")
        .get("/ScriptResource.axd?d=XGoPW3Unw0ILT0eb9sSUayB1PCvz0eeMXm23ajXUnLKSVWvpEIM7qNdgqQtwIk3oGSO-umSPRJr1BQNhALudg4-gDqI9ltlNkOQMrPf4fNHBEAhja6GHf4He4_YSEbkQ4L1Bsn1aV_AF11ks4fQlTNxlg6tYk_UGpXjfNcFSD6D49VS2gjNTnElk4fHlLsM90&t=51e37521")
      )
      .pause(435.milliseconds)
      .exec(http("request_77")
        .post("/verify_access.ashx")
      )
      .exec(http("request_78")
        .get("/DXR.axd?r=1_303,1_184,1_297,1_210,1_220,1_187,1_181,1_289,1_287-Ubfgm"))
      .exec(http("request_79")
        .get("/request/leave_form.aspx?_TSM_CombinedScripts_=True&v=ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1&_TSM_Bundles_=&cdn=False")
      )
      .pause(128.milliseconds)
      .exec(http("request_80")
        .get("/Content/ESS/fonts/icomoon.ttf?5vru0d")
      )
      .pause(219.milliseconds)
      .exec(http("request_81")
        .get("/Notifications/GetNotificationCounts")
      )
      .exec(http("request_82")
        .get("/Account/VerifyAccess")
      )
      .exec(http("request_83")
        .get("/Notifications/ViewNotifications?type=Ujq+gs/NTYOesoLftp53/jAQK5KZlqQ1cHagjmipWg+WouT18caGLBID4wZwJsoNDtlXF16+Aur61lDc7fbZu44cQabemvIWUfBgqNTQYnQZKm1YDcbSv5O3ers5nO0vxQYisheOeASwTIGbJ632mVqziFwK1zOessnfPi8xZcg=")
      )
  }

  def saveLeaveDraft = {
    exec(http("Save Draft")
      .post("/request/leave_form.aspx?View=O")
      .formParam("__EVENTTARGET", "ctl00$ctl00$ctl00$cntPlcHldrContent$btnSaveDraft")
      .formParam("__EVENTARGUMENT", "")
      .formParam("_TSM_HiddenField_", "ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1")
      .formParam("__VIEWSTATE", "${viewState}")
      .formParam("__VIEWSTATEGENERATOR", "DD360C3C")
      .formParam("ctl00$ctl00$ctl00$selCultureName", "")
      .formParam("ctl00$ctl00$ctl00$selCountry", "1")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfAttachID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfFileName", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfFileType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfAttachSrc", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMode", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfView", "O")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfInfoID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMonitorID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAgentID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNewAttach", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfOldAttach", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBalance", "${leaveBalance}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAdvanceBalance", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTotalApplied", "1.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkipExceed", "no")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveCode", "KMANL")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReason", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfDataSet", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfActualLeaveDate", "05/05/2021 00:00:00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTotalAttached", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLSplitFlag", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLDateSplit", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLLeaveCode", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferAgentID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferMonitorID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferWFStatus", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferRedirectURL", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfCancelAction", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFinYear", "2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFinStartDate", "01/01/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkipConfAllow", "no")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplacementDate", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplLeavePeriodFlag", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplCreditLeaveType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplReplacedQty", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAdvanceFlag", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSickLeaveEnable", "true")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowApproverEnable", "false")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowApproverPopup", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowFormLeaveRelieverEnable", "true")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequestorID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequestorNo", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmploymentID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLocationID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmpCountryCode", "MY")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmpBirthDate", "22/12/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvRequestorEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selLeaveType", "KMANL")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveType", "A")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveUnit", "N")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfHoursPerDay", "0.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAttachmentFlag", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfApplicationStartDate", "G")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeavePeriod", "7")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfApplicationMethod", "B")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequiredApproverRemarks", "N")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReasonFlag", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNoticePeriod", "0.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBlockType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEventType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEventEntitlementUnit", "0.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfValidatePeriodType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveCancelType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeavePolicyMsg", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmergencyQty", "1.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmergencyFlag", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmergencyControlFlag", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBalanceMethod", "Y")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvLeaveTypeEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selPeriod", "F")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvPeriodEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$cusvPeriodEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplaceVisible", "false")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelation", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelationNoticePeriod", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelationEventEntitlementUnit", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelationValidityPeriodType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtStartDate", "20/05/2022")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfStartDate", "20/05/2022")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvStartDateEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtEndDate", "20/05/2022")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEndDate", "20/05/2022")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvEndDateEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selReason", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$cusvReasonEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReliever", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelieverNo", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtReliever", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWFApprover", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWFApproverNo", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTSProjectCode", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtWFApprover", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtRmks", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$popupControlState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
      .formParam("DXScript", "1_303,1_184,1_297,1_210,1_220,1_187,1_181,1_289,1_287")
      .formParam("DXCss", "0_2312,1_50,1_53,1_51,0_2317,../Content/jquery.jscrollpane.css,../Content/ESS/bootstrap.css,../Content/ESS/NewUIStyle.css,../Content/ESS/ResponsiveSite.css,../Content/generic.light.custom.css,../Content/ESS/font-style.css,https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css,../Content/jquery.orgchart.css,../Content/ESS/style.css,../Content/ESS/component.css,../Content/ESS/alert.css,../Content/ESS/custom/jquery-ui-1.10.3.custom.min.css,../Content/jquery.mmenu.css,../Content/notifications.css,http://unifyhrstc.orisoftsaas.com/Content/ESS/jquery.ui.timepicker.css,/WebResource.axd?d=G7AEkw1asyYfSFk2Li5D0JhwAppflyxkpGSQDQbA3YX7Us59q1SeSvJlGoBadgH42WWogzokgjSTil628NjzJ-ho-6akTSnjNL_1W4rKMdV6J4E7SFdllL-EXlbUGTEk-wfRgTKBSFluXwws9OgQSz64mOsqxEoa9Z9MfmluHcdALHev8eL9dk6DjmuJdzHl0&t=637486420730234278")
      .check(regex("""<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="(.+?)" />""").saveAs("viewStateLogout"))
    )
      .exec(http("request_95")
        .get("/DXR.axd?r=0_2312,1_50,1_53,1_51,0_2317-fcfgm"))
      .exec(http("request_96")
        .get(uri4 + "?family=Open+Sans:300,400,600,700")
      )
      .exec(http("request_97")
        .get(uri4 + "?family=Roboto:400,300,500,700")
      )
      .exec(http("request_98")
        .get("/WebResource.axd?d=G7AEkw1asyYfSFk2Li5D0JhwAppflyxkpGSQDQbA3YX7Us59q1SeSvJlGoBadgH42WWogzokgjSTil628NjzJ-ho-6akTSnjNL_1W4rKMdV6J4E7SFdllL-EXlbUGTEk-wfRgTKBSFluXwws9OgQSz64mOsqxEoa9Z9MfmluHcdALHev8eL9dk6DjmuJdzHl0&t=637486420730234278")
      )
      .exec(http("request_99")
        .get("/DXR.axd?r=1_303,1_184,1_297,1_210,1_220,1_187,1_181,1_289,1_287-Ubfgm"))
      .exec(http("request_100")
        .get("/DXR.axd?r=1_58-Ubfgm"))
      .exec(http("request_101")
        .get("/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZOYXOnLy43dRx8HCf3vqtm7Uk9Dd5QTT0bKPZkChPJpkGd7et7925jgqVFYijtH4BlZm86YPMFKavMb3jiNdHO_DkODjc9ASxqTpYjlOyMlE0&t=637454356754849868")
      )
      .exec(http("request_102")
        .get("/ScriptResource.axd?d=nv7asgRUU0tRmHNR2D6t1HncJC0uSlzSoOMFzQL9KDgdtj1yUByaaYlMWCLR1tfb0zRr2KS8GU92MXS6P0lOX_vkDPQOiW6UvV384GibJ__q8DVUhGPtg7X0IEAXecIS6jMaZIGfhYY2bHennMwScvTacu4aYi7pwkjCfDx4XDhghn49oiHENcEjRtCYLFUt0&t=ffffffffe191061b")
      )
      .exec(http("request_103")
        .get("/ScriptResource.axd?d=x6wALODbMJK5e0eRC_p1LTFBEqAduy6yzdGuAMP1dHrya3_IF2A8CsbaRF-ARwHq6m-SGT1rW_kEfDOVxpLiOwBwjQzZMYd6yIJvZ9ubgIyIzxTTWWPxLOJ6h2brQiXEeYW7vHWkdtbfdWvIHio91FSsDXmcUmI7kjdMETOH_XE1&t=51e37521")
      )
      .exec(http("request_104")
        .get("/ScriptResource.axd?d=P5lTttoqSeZXoYRLQMIScIf12FcrWAiNVtlJxQA9qnTW6iJpMmht7uXNg23QNwOPVke9qF6NTd062q-kq39p4MmkxhZ1ti3ckmNVSJHDik9HIeiTEBJ8AeazBYyjXlRbQWV2Q8-MBT7ldJqGwC6gtX5XcIt2Wd4nEFDQxuD-poI1&t=51e37521")
      )
      .exec(http("request_105")
        .get("/ScriptResource.axd?d=uvA9ANM76Fbpm1FfUlagnYp2obqkhmwI_C-NoQ89dB6TwrO7THFVAk1nHl1QRi68J_pozjXYUJHgZb6l02O3dvVqjaOzdIW44mTvv4FyAQ5MvnVeKZmB7OtG9BNkATLGOGWXvK2djBpsGpZ_x3Mi2KdwGSD0SZeW5VvD940G1Y8Cml0nm6ok2UFWSXa6k4SQ0&t=51e37521")
      )
      .exec(http("request_106")
        .get("/ScriptResource.axd?d=XGoPW3Unw0ILT0eb9sSUayB1PCvz0eeMXm23ajXUnLKSVWvpEIM7qNdgqQtwIk3oGSO-umSPRJr1BQNhALudg4-gDqI9ltlNkOQMrPf4fNHBEAhja6GHf4He4_YSEbkQ4L1Bsn1aV_AF11ks4fQlTNxlg6tYk_UGpXjfNcFSD6D49VS2gjNTnElk4fHlLsM90&t=51e37521")
      )
      .pause(458.milliseconds)
      .exec(http("request_107")
        .post("/verify_access.ashx")
      )
      .exec(http("request_108")
        .get("/request/leave_form.aspx?_TSM_CombinedScripts_=True&v=ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1&_TSM_Bundles_=&cdn=False")
      )
      .exec(http("request_109")
        .get("/Content/ESS/fonts/icomoon.ttf?5vru0d")
      )
      .pause(313.milliseconds)
      .exec(http("request_110")
        .get("/Notifications/GetNotificationCounts")
      )
      .exec(http("request_111")
        .get("/Account/VerifyAccess")
      )
      .exec(http("request_112")
        .get("/Notifications/ViewNotifications?type=Eag2PWHtlVcPn+JXY74NgmiYJGhBhy7Ow44zObd6aziSkpBWbPap/Xx23n03eQFxybBobMzc4gMHz/Ia3Kqcvz0a1DWb/vwYLXDG+xDP8lBeZ3I2MnJF/FIiqR1xXS2p+je7wq88aQ4x2DriXjLqzQ04DJONmYzMnVJOZwjLrDA=")
      )
      .exec(http("request_113")
        .post("/request/get_leave_days.ashx")
        .formParam("StoreAsHr", "N")
        .formParam("EmployeeID", "943")
        .formParam("EmployeeNo", "11013")
        .formParam("ReferID", "")
        .formParam("LeaveCode", "AL")
        .formParam("LeaveType", "F")
        .formParam("StartDate", "04/05/2021 00:00")
        .formParam("EndDate", "05/05/2021 00:00"))
      .exec(http("request_114")
        .get("/Account/VerifyAccess")
      )
      .exec(http("request_115")
        .get("/Notifications/GetNotificationsList?row=8")
      )
      .exec(http("request_116")
        .get(uri3 + "?v=4.7.0")
      )
      .exec(http("request_117")
        .post("/request/get_leave_reason.ashx")
        .formParam("LeaveType", "A")
        .formParam("EmployeeID", "")
        .formParam("EmploymentID", "")
        .formParam("EmployeeNo", "")
        .formParam("LeaveCode", "AL")
        .formParam("StartDate", "04/05/2021 00:00")
        .formParam("EndDate", "05/05/2021 00:00")
        .formParam("LocationID", ""))
      .pause(7)
      .exec(http("request_118")
        .get("/DXR.axd?r=0_2312,1_50,1_53,1_51,0_2317-fcfgm"))
      .exec(http("request_119")
        .get("/request/leave_form.aspx?View=O")
      )
      .exec(http("request_120")
        .get(uri4 + "?family=Open+Sans:300,400,600,700")
      )
      .exec(http("request_121")
        .get(uri4 + "?family=Roboto:400,300,500,700")
      )
      .exec(http("request_122")
        .get("/WebResource.axd?d=G7AEkw1asyYfSFk2Li5D0JhwAppflyxkpGSQDQbA3YX7Us59q1SeSvJlGoBadgH42WWogzokgjSTil628NjzJ-ho-6akTSnjNL_1W4rKMdV6J4E7SFdllL-EXlbUGTEk-wfRgTKBSFluXwws9OgQSz64mOsqxEoa9Z9MfmluHcdALHev8eL9dk6DjmuJdzHl0&t=637486420730234278")
      )
      .exec(http("request_123")
        .get("/DXR.axd?r=1_303,1_184,1_297,1_210,1_220,1_187,1_181,1_289,1_287-Ubfgm"))
      .exec(http("request_124")
        .get("/DXR.axd?r=1_58-Ubfgm"))
      .exec(http("request_125")
        .get("/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZOYXOnLy43dRx8HCf3vqtm7Uk9Dd5QTT0bKPZkChPJpkGd7et7925jgqVFYijtH4BlZm86YPMFKavMb3jiNdHO_DkODjc9ASxqTpYjlOyMlE0&t=637454356754849868")
      )
      .exec(http("request_126")
        .get("/ScriptResource.axd?d=nv7asgRUU0tRmHNR2D6t1HncJC0uSlzSoOMFzQL9KDgdtj1yUByaaYlMWCLR1tfb0zRr2KS8GU92MXS6P0lOX_vkDPQOiW6UvV384GibJ__q8DVUhGPtg7X0IEAXecIS6jMaZIGfhYY2bHennMwScvTacu4aYi7pwkjCfDx4XDhghn49oiHENcEjRtCYLFUt0&t=ffffffffe191061b")
      )
      .exec(http("request_127")
        .get("/ScriptResource.axd?d=x6wALODbMJK5e0eRC_p1LTFBEqAduy6yzdGuAMP1dHrya3_IF2A8CsbaRF-ARwHq6m-SGT1rW_kEfDOVxpLiOwBwjQzZMYd6yIJvZ9ubgIyIzxTTWWPxLOJ6h2brQiXEeYW7vHWkdtbfdWvIHio91FSsDXmcUmI7kjdMETOH_XE1&t=51e37521")
      )
      .exec(http("request_128")
        .get("/ScriptResource.axd?d=P5lTttoqSeZXoYRLQMIScIf12FcrWAiNVtlJxQA9qnTW6iJpMmht7uXNg23QNwOPVke9qF6NTd062q-kq39p4MmkxhZ1ti3ckmNVSJHDik9HIeiTEBJ8AeazBYyjXlRbQWV2Q8-MBT7ldJqGwC6gtX5XcIt2Wd4nEFDQxuD-poI1&t=51e37521")
      )
      .exec(http("request_129")
        .get("/ScriptResource.axd?d=XGoPW3Unw0ILT0eb9sSUayB1PCvz0eeMXm23ajXUnLKSVWvpEIM7qNdgqQtwIk3oGSO-umSPRJr1BQNhALudg4-gDqI9ltlNkOQMrPf4fNHBEAhja6GHf4He4_YSEbkQ4L1Bsn1aV_AF11ks4fQlTNxlg6tYk_UGpXjfNcFSD6D49VS2gjNTnElk4fHlLsM90&t=51e37521")
      )
      .exec(http("request_130")
        .get("/ScriptResource.axd?d=uvA9ANM76Fbpm1FfUlagnYp2obqkhmwI_C-NoQ89dB6TwrO7THFVAk1nHl1QRi68J_pozjXYUJHgZb6l02O3dvVqjaOzdIW44mTvv4FyAQ5MvnVeKZmB7OtG9BNkATLGOGWXvK2djBpsGpZ_x3Mi2KdwGSD0SZeW5VvD940G1Y8Cml0nm6ok2UFWSXa6k4SQ0&t=51e37521")
      )
      .pause(402.milliseconds)
      .exec(http("request_131")
        .post("/verify_access.ashx")
      )
      .exec(http("request_132")
        .get("/request/leave_form.aspx?_TSM_CombinedScripts_=True&v=ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1&_TSM_Bundles_=&cdn=False")
      )
      .exec(http("request_133")
        .get("/Content/ESS/fonts/icomoon.ttf?5vru0d")
      )
      .exec(http("request_134")
        .get(uri3 + "?v=4.7.0")
      )
      .pause(348.milliseconds)
      .exec(http("request_135")
        .get("/Notifications/GetNotificationCounts")
      )
      .exec(http("request_136")
        .get("/Account/VerifyAccess")
      )
      .exec(http("request_137")
        .get("/Notifications/ViewNotifications?type=OHPsZa/9KDX7hfOP93OHJL5yXzQN+aowUBXt1DjZd4VeisxnMTa65TitMBjdh6js6izOPMNYGmaukof+pZGLS92gEQvdya74avJjqAveKhTow24t8kNbzQhq6hV2okCimv7sTmTne0cAkF5b/xNHVTilStq3zL4fM98DDm8tkjk=")
      )
      .exec(http("request_138")
        .post("/request/get_leave_days.ashx")
        .formParam("StoreAsHr", "N")
        .formParam("EmployeeID", "943")
        .formParam("EmployeeNo", "11013")
        .formParam("ReferID", "")
        .formParam("LeaveCode", "AL")
        .formParam("LeaveType", "F")
        .formParam("StartDate", "04/05/2021 00:00")
        .formParam("EndDate", "04/05/2021 00:00"))
      .exec(http("request_139")
        .get("/Account/VerifyAccess")
      )
      .exec(http("request_140")
        .get("/Notifications/GetNotificationsList?row=8")
      )
      .exec(http("request_141")
        .post("/request/get_leave_reason.ashx")
        .formParam("LeaveType", "A")
        .formParam("EmployeeID", "")
        .formParam("EmploymentID", "")
        .formParam("EmployeeNo", "")
        .formParam("LeaveCode", "AL")
        .formParam("StartDate", "04/05/2021 00:00")
        .formParam("EndDate", "04/05/2021 00:00")
        .formParam("LocationID", ""))
      .pause(4)
  }

  def leaveLogout = {

    exec(http("Logout")
      .post("/request/leave_form.aspx?View=O")
      .formParam("__EVENTTARGET", "ctl00$ctl00$ctl00$lbLogout")
      .formParam("__EVENTARGUMENT", "")
      .formParam("_TSM_HiddenField_", "ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1")
      .formParam("__VIEWSTATE","${viewState}")//viewStateLogout
      .formParam("__VIEWSTATEGENERATOR", "DD360C3C")
      .formParam("ctl00$ctl00$ctl00$selCultureName", "")
      .formParam("ctl00$ctl00$ctl00$selCountry", "1")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfAttachID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfFileName", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfFileType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfAttachSrc", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMode", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfView", "O")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfInfoID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMonitorID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAgentID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNewAttach", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfOldAttach", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBalance", "21.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAdvanceBalance", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTotalApplied", "1.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkipExceed", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveCode", "KMANL")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReason", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfDataSet", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfActualLeaveDate", "04/05/2021 00:00:00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTotalAttached", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLSplitFlag", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLDateSplit", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLLeaveCode", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferAgentID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferMonitorID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferWFStatus", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferRedirectURL", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfCancelAction", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFinYear", "2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFinStartDate", "01/01/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkipConfAllow", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplacementDate", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplLeavePeriodFlag", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplCreditLeaveType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplReplacedQty", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAdvanceFlag", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSickLeaveEnable", "true")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowApproverEnable", "false")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowApproverPopup", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowFormLeaveRelieverEnable", "true")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequestorID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequestorNo", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmploymentID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLocationID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmpCountryCode", "MY")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmpBirthDate", "22/12/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvRequestorEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selLeaveType", "AL")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveType", "A")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveUnit", "N")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfHoursPerDay", "8.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAttachmentFlag", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfApplicationStartDate", "J")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeavePeriod", "7")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfApplicationMethod", "B")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequiredApproverRemarks", "N")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReasonFlag", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNoticePeriod", "0.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBlockType", "N")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEventType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEventEntitlementUnit", "0.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfValidatePeriodType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveCancelType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeavePolicyMsg", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmergencyQty", "1.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmergencyFlag", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmergencyControlFlag", "1")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBalanceMethod", "R")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvLeaveTypeEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selPeriod", "F")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvPeriodEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$cusvPeriodEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplaceVisible", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelation", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelationNoticePeriod", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelationEventEntitlementUnit", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelationValidityPeriodType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtStartDate", "04/05/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfStartDate", "04/05/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvStartDateEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtEndDate", "04/05/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEndDate", "04/05/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvEndDateEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selReason", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$cusvReasonEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReliever", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelieverNo", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtReliever", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWFApprover", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWFApproverNo", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTSProjectCode", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtWFApprover", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtRmks", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$popupControlState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
      .formParam("DXScript", "1_303,1_184,1_297,1_210,1_220,1_187,1_181,1_289,1_287")
      .formParam("DXCss", "0_2312,1_50,1_53,1_51,0_2317,../Content/jquery.jscrollpane.css,../Content/ESS/bootstrap.css,../Content/ESS/NewUIStyle.css,../Content/ESS/ResponsiveSite.css,../Content/generic.light.custom.css,../Content/ESS/font-style.css,https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css,../Content/jquery.orgchart.css,../Content/ESS/style.css,../Content/ESS/component.css,../Content/ESS/alert.css,../Content/ESS/custom/jquery-ui-1.10.3.custom.min.css,../Content/jquery.mmenu.css,../Content/notifications.css,http://unifyhrstc.orisoftsaas.com/Content/ESS/jquery.ui.timepicker.css,/WebResource.axd?d=G7AEkw1asyYfSFk2Li5D0JhwAppflyxkpGSQDQbA3YX7Us59q1SeSvJlGoBadgH42WWogzokgjSTil628NjzJ-ho-6akTSnjNL_1W4rKMdV6J4E7SFdllL-EXlbUGTEk-wfRgTKBSFluXwws9OgQSz64mOsqxEoa9Z9MfmluHcdALHev8eL9dk6DjmuJdzHl0&t=637486420730234278")
      .check(status.is(302)))
      .exec(http("request_143")
        .get("/Account/Login")
      )
      .exec(http("request_144")
        .get("/DXR.axd?r=1_58-Ubfgm"))
      .exec(http("request_145")
        .get("/DXR.axd?r=1_17,0_2214,1_50,1_53,1_51,1_16,0_2219,0_2312,0_2317-fcfgm"))
      .exec(http("request_146")
        .get("/Content/css?v=w9USDPGryprQSMA62T1giyRXrtqAIG-BphxyQY0Qw_w1"))
      .exec(http("request_147")
        .get("/DXR.axd?r=1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_208,1_216,1_212,1_189,1_222,17_42,1_297,1_215,1_207,1_289,1_205,17_7,1_287,1_211,17_23,1_197,17_1-Ubfgm"))
      .exec(http("request_148")
        .get("/bundles/jquery?v=w1vknpWt6KqlZcHeJQvaK6VbvvXt1Go8HcGH_DqKzzo1")
      )
      .pause(122.milliseconds)
      .exec(http("request_149")
        .get("/Content/Images/bg-login.jpg?V=03"))
      .exec(http("request_150")
        .get("/Content/fonts/icomoon.ttf?5vru0d")
      )
  }

  def getSavedDraft = {

    exec(http("Open Draft Popup")
      .get("/request/leave_search.aspx?IsDraft=yes&View=O")
      .check(bodyString.saveAs("bodySearch"))
    )
      .exec(http("request_80")
        .get("/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZOYXOnLy43dRx8HCf3vqtm7Uk9Dd5QTT0bKPZkChPJpkGd7et7925jgqVFYijtH4BlZm86YPMFKavMb3jiNdHO_DkODjc9ASxqTpYjlOyMlE0&t=637454356754849868")
      )
      .exec(http("request_81")
        .get("/ScriptResource.axd?d=P5lTttoqSeZXoYRLQMIScIf12FcrWAiNVtlJxQA9qnTW6iJpMmht7uXNg23QNwOPVke9qF6NTd062q-kq39p4MmkxhZ1ti3ckmNVSJHDik9HIeiTEBJ8AeazBYyjXlRbQWV2Q8-MBT7ldJqGwC6gtX5XcIt2Wd4nEFDQxuD-poI1&t=51e37521")
      )
      .exec(http("request_82")
        .get("/ScriptResource.axd?d=x6wALODbMJK5e0eRC_p1LTFBEqAduy6yzdGuAMP1dHrya3_IF2A8CsbaRF-ARwHq6m-SGT1rW_kEfDOVxpLiOwBwjQzZMYd6yIJvZ9ubgIyIzxTTWWPxLOJ6h2brQiXEeYW7vHWkdtbfdWvIHio91FSsDXmcUmI7kjdMETOH_XE1&t=51e37521")
      )
      .exec(http("request_83")
        .get("/ScriptResource.axd?d=XGoPW3Unw0ILT0eb9sSUayB1PCvz0eeMXm23ajXUnLKSVWvpEIM7qNdgqQtwIk3oGSO-umSPRJr1BQNhALudg4-gDqI9ltlNkOQMrPf4fNHBEAhja6GHf4He4_YSEbkQ4L1Bsn1aV_AF11ks4fQlTNxlg6tYk_UGpXjfNcFSD6D49VS2gjNTnElk4fHlLsM90&t=51e37521")
      )
      .exec(http("request_84")
        .get("/ScriptResource.axd?d=uvA9ANM76Fbpm1FfUlagnYp2obqkhmwI_C-NoQ89dB6TwrO7THFVAk1nHl1QRi68J_pozjXYUJHgZb6l02O3dvVqjaOzdIW44mTvv4FyAQ5MvnVeKZmB7OtG9BNkATLGOGWXvK2djBpsGpZ_x3Mi2KdwGSD0SZeW5VvD940G1Y8Cml0nm6ok2UFWSXa6k4SQ0&t=51e37521")
      )
      .exec(session => {

      val body = session("bodySearch").as[String]
      val value = new Regex("href=\"javascript:parent.onOpenInfo(.+?)\"")
      val empNoValue = (value.findAllIn(body)).mkString(",").split(",")
      val toRemove = ")\"".toSet
      val infoId = empNoValue(1)
      val agentId = empNoValue(2).filterNot(toRemove)
      println(s"Value : $infoId")
      println(s"Value : $agentId")

      session.set("agentId",agentId).set("infoId",infoId)
    })
    .exec(http("request_85")
      .get("/request/leave_search.aspx?_TSM_CombinedScripts_=True&v=ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1&_TSM_Bundles_=&cdn=False")
    )
      .pause(1)
      .exec(http("request_86")
        .post("/request/leave_form.aspx?View=O")
        .formParam("__EVENTTARGET", "ctl00$ctl00$ctl00$cntPlcHldrContent$btnDraft")
        .formParam("__EVENTARGUMENT", "")
        .formParam("_TSM_HiddenField_", "ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1")
        .formParam("__VIEWSTATE", "${viewState}")
        .formParam("__VIEWSTATEGENERATOR", "DD360C3C")
        .formParam("ctl00$ctl00$ctl00$selCultureName", "")
        .formParam("ctl00$ctl00$ctl00$selCountry", "1")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfAttachID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfFileName", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfFileType", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfAttachSrc", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMode", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfView", "O")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfInfoID", "${infoId}")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMonitorID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAgentID", "${agentId}")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNewAttach", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfOldAttach", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBalance", "13.50")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAdvanceBalance", "0")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTotalApplied", "1.00")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkipExceed", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveCode", "AL")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReason", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfDataSet", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfActualLeaveDate", "05/05/2021 00:00:00")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTotalAttached", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLSplitFlag", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLDateSplit", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLLeaveCode", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferAgentID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferMonitorID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferWFStatus", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferRedirectURL", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfCancelAction", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFinYear", "2021")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFinStartDate", "01/01/2021")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkipConfAllow", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplacementDate", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplLeavePeriodFlag", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplCreditLeaveType", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplReplacedQty", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAdvanceFlag", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSickLeaveEnable", "true")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowApproverEnable", "false")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowApproverPopup", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowFormLeaveRelieverEnable", "true")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequestorID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequestorNo", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmploymentID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLocationID", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmpCountryCode", "MY")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmpBirthDate", "22/12/2021")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvRequestorEx_ClientState", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selLeaveType", "AL")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveType", "A")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveUnit", "N")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfHoursPerDay", "0.00")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAttachmentFlag", "0")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfApplicationStartDate", "G")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeavePeriod", "7")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfApplicationMethod", "B")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequiredApproverRemarks", "N")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReasonFlag", "0")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNoticePeriod", "0.00")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBlockType", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEventType", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEventEntitlementUnit", "0.00")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfValidatePeriodType", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveCancelType", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeavePolicyMsg", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmergencyQty", "1.00")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmergencyFlag", "0")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmergencyControlFlag", "0")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBalanceMethod", "Y")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvLeaveTypeEx_ClientState", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selPeriod", "F")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvPeriodEx_ClientState", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$cusvPeriodEx_ClientState", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplaceVisible", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelation", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelationNoticePeriod", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelationEventEntitlementUnit", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelationValidityPeriodType", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtStartDate", "05/05/2021")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfStartDate", "05/05/2021")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvStartDateEx_ClientState", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtEndDate", "05/05/2021")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEndDate", "05/05/2021")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvEndDateEx_ClientState", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selReason", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$cusvReasonEx_ClientState", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReliever", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelieverNo", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtReliever", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWFApprover", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWFApproverNo", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTSProjectCode", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtWFApprover", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtRmks", "")
        .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$popupControlState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("DXScript", "1_303,1_184,1_297,1_210,1_220,1_187,1_181,1_289,1_287")
        .formParam("DXCss", "0_2312,1_50,1_53,1_51,0_2317,../Content/jquery.jscrollpane.css,../Content/ESS/bootstrap.css,../Content/ESS/NewUIStyle.css,../Content/ESS/ResponsiveSite.css,../Content/generic.light.custom.css,../Content/ESS/font-style.css,https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css,../Content/jquery.orgchart.css,../Content/ESS/style.css,../Content/ESS/component.css,../Content/ESS/alert.css,../Content/ESS/custom/jquery-ui-1.10.3.custom.min.css,../Content/jquery.mmenu.css,../Content/notifications.css,http://unifyhrstc.orisoftsaas.com/Content/ESS/jquery.ui.timepicker.css,/WebResource.axd?d=G7AEkw1asyYfSFk2Li5D0JhwAppflyxkpGSQDQbA3YX7Us59q1SeSvJlGoBadgH42WWogzokgjSTil628NjzJ-ho-6akTSnjNL_1W4rKMdV6J4E7SFdllL-EXlbUGTEk-wfRgTKBSFluXwws9OgQSz64mOsqxEoa9Z9MfmluHcdALHev8eL9dk6DjmuJdzHl0&t=637486420730234278")
        .check(bodyString.saveAs("draftBody"))
        .check(regex("""<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="(.+?)" />""").saveAs("viewStateDraft"))
      )
  }

  def deleteSavedDraft = {
    exec(http("request_109")
      .post("/request/leave_form.aspx?View=O")
      .formParam("__EVENTTARGET", "ctl00$ctl00$ctl00$cntPlcHldrContent$btnDeleteDraft")
      .formParam("__EVENTARGUMENT", "")
      .formParam("_TSM_HiddenField_", "ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1")
      .formParam("__VIEWSTATE", "${viewStateDraft}")
      .formParam("__VIEWSTATEGENERATOR", "DD360C3C")
      .formParam("ctl00$ctl00$ctl00$selCultureName", "")
      .formParam("ctl00$ctl00$ctl00$selCountry", "1")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfAttachID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfFileName", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfFileType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfAttachSrc", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMode", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfView", "O")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfInfoID", "${infoId}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMonitorID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAgentID", "${agentId}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNewAttach", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfOldAttach", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBalance", "13.50")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAdvanceBalance", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTotalApplied", "1.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkipExceed", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveCode", "AL")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReason", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfDataSet", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfActualLeaveDate", "05/05/2021 00:00:00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTotalAttached", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLSplitFlag", "N")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLDateSplit", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLLeaveCode", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferAgentID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferMonitorID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferWFStatus", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferRedirectURL", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfCancelAction", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFinYear", "2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFinStartDate", "01/01/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkipConfAllow", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplacementDate", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplLeavePeriodFlag", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplCreditLeaveType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplReplacedQty", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAdvanceFlag", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSickLeaveEnable", "true")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowApproverEnable", "false")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowApproverPopup", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowFormLeaveRelieverEnable", "true")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequestorID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequestorNo", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmploymentID", "943")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLocationID", "6")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmpCountryCode", "MY")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmpBirthDate", "22/12/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvRequestorEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selLeaveType", "AL")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveType", "A")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveUnit", "N")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfHoursPerDay", "0.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAttachmentFlag", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfApplicationStartDate", "G")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeavePeriod", "7")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfApplicationMethod", "B")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequiredApproverRemarks", "N")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReasonFlag", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNoticePeriod", "0.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBlockType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEventType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEventEntitlementUnit", "0.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfValidatePeriodType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveCancelType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeavePolicyMsg", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmergencyQty", "1.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmergencyFlag", "1")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmergencyControlFlag", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBalanceMethod", "Y")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvLeaveTypeEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selPeriod", "F")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvPeriodEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$cusvPeriodEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplaceVisible", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelation", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelationNoticePeriod", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelationEventEntitlementUnit", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelationValidityPeriodType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtStartDate", "04/05/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfStartDate", "04/05/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvStartDateEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtEndDate", "05/05/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEndDate", "05/05/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvEndDateEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selReason", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$cusvReasonEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReliever", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelieverNo", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtReliever", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWFApprover", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWFApproverNo", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTSProjectCode", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtWFApprover", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtRmks", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$popupControlState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
      .formParam("DXScript", "1_303,1_184,1_297,1_210,1_220,1_187,1_181,1_289,1_287")
      .formParam("DXCss", "0_2312,1_50,1_53,1_51,0_2317,../Content/jquery.jscrollpane.css,../Content/ESS/bootstrap.css,../Content/ESS/NewUIStyle.css,../Content/ESS/ResponsiveSite.css,../Content/generic.light.custom.css,../Content/ESS/font-style.css,https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css,../Content/jquery.orgchart.css,../Content/ESS/style.css,../Content/ESS/component.css,../Content/ESS/alert.css,../Content/ESS/custom/jquery-ui-1.10.3.custom.min.css,../Content/jquery.mmenu.css,../Content/notifications.css,http://unifyhrstc.orisoftsaas.com/Content/ESS/jquery.ui.timepicker.css,/WebResource.axd?d=G7AEkw1asyYfSFk2Li5D0JhwAppflyxkpGSQDQbA3YX7Us59q1SeSvJlGoBadgH42WWogzokgjSTil628NjzJ-ho-6akTSnjNL_1W4rKMdV6J4E7SFdllL-EXlbUGTEk-wfRgTKBSFluXwws9OgQSz64mOsqxEoa9Z9MfmluHcdALHev8eL9dk6DjmuJdzHl0&t=637486420730234278")
      .check(regex("""<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="(.+?)" />""").saveAs("viewStateLogout"))
    )
  }

  def submitLeave = {
    exec(http("Submit Leave")
      .post("/request/leave_form.aspx?View=O")
      .formParam("__EVENTTARGET", "ctl00$ctl00$ctl00$cntPlcHldrContent$btnSubmit")
      .formParam("__EVENTARGUMENT", "")
      .formParam("_TSM_HiddenField_", "ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1")
      .formParam("__VIEWSTATE", "${viewState}")
      .formParam("__VIEWSTATEGENERATOR", "DD360C3C")
      .formParam("ctl00$ctl00$ctl00$selCultureName", "")
      .formParam("ctl00$ctl00$ctl00$selCountry", "1")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfAttachID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfFileName", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfFileType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$hfAttachSrc", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMode", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfView", "O")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfInfoID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfMonitorID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAgentID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNewAttach", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfOldAttach", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBalance", "${leaveBalance}")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAdvanceBalance", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTotalApplied", "2.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkipExceed", "no")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveCode", "AL")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReason", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfDataSet", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfActualLeaveDate", "10/07/2021 00:00:00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTotalAttached", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLSplitFlag", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLDateSplit", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLLeaveCode", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferAgentID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferMonitorID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferWFStatus", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfUPLReferRedirectURL", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfCancelAction", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFinYear", "2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfFinStartDate", "01/01/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSkipConfAllow", "no")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplacementDate", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplLeavePeriodFlag", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplCreditLeaveType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplReplacedQty", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAdvanceFlag", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfSickLeaveEnable", "true")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowApproverEnable", "false")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowApproverPopup", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWorkflowFormLeaveRelieverEnable", "true")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequestorID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequestorNo", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmploymentID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLocationID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmpCountryCode", "MY")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmpBirthDate", "22/12/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvRequestorEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selLeaveType", "AL")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveType", "A")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveUnit", "N")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfHoursPerDay", "8.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfAttachmentFlag", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfApplicationStartDate", "G")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeavePeriod", "7")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfApplicationMethod", "B")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRequiredApproverRemarks", "N")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReasonFlag", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfNoticePeriod", "0.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBlockType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEventType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEventEntitlementUnit", "0.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfValidatePeriodType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeaveCancelType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfLeavePolicyMsg", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmergencyQty", "1.00")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmergencyFlag", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEmergencyControlFlag", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfBalanceMethod", "Y")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvLeaveTypeEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selPeriod", "F")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvPeriodEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$cusvPeriodEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReplaceVisible", "false")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelation", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelationNoticePeriod", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelationEventEntitlementUnit", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelationValidityPeriodType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtStartDate", "12/07/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfStartDate", "12/07/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvStartDateEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtEndDate", "13/07/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfEndDate", "13/07/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$rfvEndDateEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$selReason", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$cusvReasonEx_ClientState", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfReliever", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfRelieverNo", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtReliever", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWFApprover", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfWFApproverNo", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfTSProjectCode", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtWFApprover", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$txtRmks", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$popupControlState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
      .formParam("DXScript", "1_303,1_184,1_297,1_210,1_220,1_187,1_181,1_289,1_287")
      .formParam("DXCss", "0_2312,1_50,1_53,1_51,0_2317,../Content/jquery.jscrollpane.css,../Content/ESS/bootstrap.css,../Content/ESS/NewUIStyle.css,../Content/ESS/ResponsiveSite.css,../Content/generic.light.custom.css,../Content/ESS/font-style.css,https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css,../Content/jquery.orgchart.css,../Content/ESS/style.css,../Content/ESS/component.css,../Content/ESS/alert.css,../Content/ESS/custom/jquery-ui-1.10.3.custom.min.css,../Content/jquery.mmenu.css,../Content/notifications.css,http://unifyhrstc.orisoftsaas.com/Content/ESS/jquery.ui.timepicker.css,/WebResource.axd?d=G7AEkw1asyYfSFk2Li5D0JhwAppflyxkpGSQDQbA3YX7Us59q1SeSvJlGoBadgH42WWogzokgjSTil628NjzJ-ho-6akTSnjNL_1W4rKMdV6J4E7SFdllL-EXlbUGTEk-wfRgTKBSFluXwws9OgQSz64mOsqxEoa9Z9MfmluHcdALHev8eL9dk6DjmuJdzHl0&t=637486420730234278")
      .check(regex("""<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="(.+?)" />""").saveAs("viewStateLogout"))
    )
      .pause(134.milliseconds)
      .exec(http("request_90")
        .get("/WebResource.axd?d=G7AEkw1asyYfSFk2Li5D0JhwAppflyxkpGSQDQbA3YX7Us59q1SeSvJlGoBadgH42WWogzokgjSTil628NjzJ-ho-6akTSnjNL_1W4rKMdV6J4E7SFdllL-EXlbUGTEk-wfRgTKBSFluXwws9OgQSz64mOsqxEoa9Z9MfmluHcdALHev8eL9dk6DjmuJdzHl0&t=637486420730234278")
      )
      .exec(http("request_91")
        .get(uri4 + "?family=Open+Sans:300,400,600,700"))
      .exec(http("request_92")
        .get(uri4 + "?family=Roboto:400,300,500,700"))
      .exec(http("request_93")
        .get("/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZOYXOnLy43dRx8HCf3vqtm7Uk9Dd5QTT0bKPZkChPJpkGd7et7925jgqVFYijtH4BlZm86YPMFKavMb3jiNdHO_DkODjc9ASxqTpYjlOyMlE0&t=637454356754849868")
      )
      .exec(http("request_94")
        .get("/ScriptResource.axd?d=nv7asgRUU0tRmHNR2D6t1HncJC0uSlzSoOMFzQL9KDgdtj1yUByaaYlMWCLR1tfb0zRr2KS8GU92MXS6P0lOX_vkDPQOiW6UvV384GibJ__q8DVUhGPtg7X0IEAXecIS6jMaZIGfhYY2bHennMwScvTacu4aYi7pwkjCfDx4XDhghn49oiHENcEjRtCYLFUt0&t=ffffffffe191061b")
      )
      .exec(http("request_95")
        .get("/ScriptResource.axd?d=x6wALODbMJK5e0eRC_p1LTFBEqAduy6yzdGuAMP1dHrya3_IF2A8CsbaRF-ARwHq6m-SGT1rW_kEfDOVxpLiOwBwjQzZMYd6yIJvZ9ubgIyIzxTTWWPxLOJ6h2brQiXEeYW7vHWkdtbfdWvIHio91FSsDXmcUmI7kjdMETOH_XE1&t=51e37521")
      )
      .exec(http("request_96")
        .get("/DXR.axd?r=1_303,1_184,1_297,1_210,1_220,1_187,1_181,1_289,1_287-Ubfgm"))
      .exec(http("request_97")
        .get("/DXR.axd?r=1_58-Ubfgm"))
      .exec(http("request_98")
        .get("/ScriptResource.axd?d=P5lTttoqSeZXoYRLQMIScIf12FcrWAiNVtlJxQA9qnTW6iJpMmht7uXNg23QNwOPVke9qF6NTd062q-kq39p4MmkxhZ1ti3ckmNVSJHDik9HIeiTEBJ8AeazBYyjXlRbQWV2Q8-MBT7ldJqGwC6gtX5XcIt2Wd4nEFDQxuD-poI1&t=51e37521")
      )
      .exec(http("request_99")
        .get("/ScriptResource.axd?d=XGoPW3Unw0ILT0eb9sSUayB1PCvz0eeMXm23ajXUnLKSVWvpEIM7qNdgqQtwIk3oGSO-umSPRJr1BQNhALudg4-gDqI9ltlNkOQMrPf4fNHBEAhja6GHf4He4_YSEbkQ4L1Bsn1aV_AF11ks4fQlTNxlg6tYk_UGpXjfNcFSD6D49VS2gjNTnElk4fHlLsM90&t=51e37521")
      )
      .exec(http("request_100")
        .get("/ScriptResource.axd?d=uvA9ANM76Fbpm1FfUlagnYp2obqkhmwI_C-NoQ89dB6TwrO7THFVAk1nHl1QRi68J_pozjXYUJHgZb6l02O3dvVqjaOzdIW44mTvv4FyAQ5MvnVeKZmB7OtG9BNkATLGOGWXvK2djBpsGpZ_x3Mi2KdwGSD0SZeW5VvD940G1Y8Cml0nm6ok2UFWSXa6k4SQ0&t=51e37521")
      )
      .pause(374.milliseconds)
      .exec(http("request_101")
        .post("/verify_access.ashx")
      )
      .exec(http("request_102")
        .get("/request/leave_form.aspx?_TSM_CombinedScripts_=True&v=ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1&_TSM_Bundles_=&cdn=False")
      )
      .exec(http("request_103")
        .get("/Content/ESS/fonts/icomoon.ttf?5vru0d")
      )
      .pause(911.milliseconds)
      .exec(http("request_104")
        .get("/Notifications/GetNotificationCounts")
      )
      .exec(http("request_105")
        .get("/Account/VerifyAccess")
      )
      .exec(http("request_106")
        .get("/Notifications/ViewNotifications?type=CNMXtPgKIVa6YnFuKlskEfeFBaVNW7XdoPfPLtvxNNkNhnuv18EyjcRBUi3X5Yzbak3PoJJwq5jKJtZhTpIg9aPfkDOBB+ZNQ9uybIYEexiRMhwFZ4TsIBwg7OaeSlatcTrt/O20ealykONsNlAGLk1BMvvfeZTHIxJmZ+sDBEQ=")
      )
      .pause(433.milliseconds)
      .exec(http("request_107")
        .post("/request/get_leave_days.ashx")

        .formParam("StoreAsHr", "N")
        .formParam("EmployeeID", "943")
        .formParam("EmployeeNo", "11013")
        .formParam("ReferID", "")
        .formParam("LeaveCode", "AL")
        .formParam("LeaveType", "F")
        .formParam("StartDate", "19/05/2021 00:00")
        .formParam("EndDate", "19/05/2021 00:00"))
      .exec(http("request_108")
        .post("/request/get_leave_reason.ashx")

        .formParam("LeaveType", "A")
        .formParam("EmployeeID", "")
        .formParam("EmploymentID", "")
        .formParam("EmployeeNo", "")
        .formParam("LeaveCode", "AL")
        .formParam("StartDate", "19/05/2021 00:00")
        .formParam("EndDate", "19/05/2021 00:00")
        .formParam("LocationID", ""))
      .pause(103.milliseconds)
      .exec(http("request_109")
        .get("/Account/VerifyAccess")
      )
      .exec(http("request_110")
        .get("/Notifications/GetNotificationsList?row=8")
      )
      .pause(1)
      .exec(http("Redirect To Workflow")
        .get("/works/request_lst.aspx")
      )
  }
}
