package computerdatabase.Module.Leave

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._
import scala.util.matching.Regex

object ESSSUPMyTeamViewLeaveEntitlement {

  val uri1 = "https://maps.googleapis.com/maps/api/js"
  val uri2 = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2"
  val uri4 = "https://fonts.googleapis.com/css"

  def loadLeaveEntitlement = {
    exec(http("Load Leave Entitlement")
      .get("/profile/leave_ent.aspx?Mode=S")
      .check(status.is(200))
      .check(bodyString.saveAs("TableLeave"))
      .check(regex("""<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="(|.+?)" />""").saveAs("viewStateTable"))
    )
      .exec(http("request_54")
        .get("/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZOYXOnLy43dRx8HCf3vqtm7Uk9Dd5QTT0bKPZkChPJpkGd7et7925jgqVFYijtH4BlZm86YPMFKavMb3jiNdHO_DkODjc9ASxqTpYjlOyMlE0&t=637454358340000000"))
      .exec(http("request_55")
        .get("/ScriptResource.axd?d=x6wALODbMJK5e0eRC_p1LTFBEqAduy6yzdGuAMP1dHrya3_IF2A8CsbaRF-ARwHq6m-SGT1rW_kEfDOVxpLiOwBwjQzZMYd6yIJvZ9ubgIyIzxTTWWPxLOJ6h2brQiXEeYW7vHWkdtbfdWvIHio91FSsDXmcUmI7kjdMETOH_XE1&t=51e37521"))
      .exec(http("request_56")
        .get("/ScriptResource.axd?d=P5lTttoqSeZXoYRLQMIScIf12FcrWAiNVtlJxQA9qnTW6iJpMmht7uXNg23QNwOPVke9qF6NTd062q-kq39p4MmkxhZ1ti3ckmNVSJHDik9HIeiTEBJ8AeazBYyjXlRbQWV2Q8-MBT7ldJqGwC6gtX5XcIt2Wd4nEFDQxuD-poI1&t=51e37521"))
      .exec(http("request_57")
        .get("/ScriptResource.axd?d=XGoPW3Unw0ILT0eb9sSUayB1PCvz0eeMXm23ajXUnLKSVWvpEIM7qNdgqQtwIk3oGSO-umSPRJr1BQNhALudg4-gDqI9ltlNkOQMrPf4fNHBEAhja6GHf4He4_YSEbkQ4L1Bsn1aV_AF11ks4fQlTNxlg6tYk_UGpXjfNcFSD6D49VS2gjNTnElk4fHlLsM90&t=51e37521"))
      .exec(http("request_58")
        .get("/ScriptResource.axd?d=uvA9ANM76Fbpm1FfUlagnYp2obqkhmwI_C-NoQ89dB6TwrO7THFVAk1nHl1QRi68J_pozjXYUJHgZb6l02O3dvVqjaOzdIW44mTvv4FyAQ5MvnVeKZmB7OtG9BNkATLGOGWXvK2djBpsGpZ_x3Mi2KdwGSD0SZeW5VvD940G1Y8Cml0nm6ok2UFWSXa6k4SQ0&t=51e37521"))
      .exec(http("request_59")
        .get(uri4 + "?family=Open+Sans:300,400,600,700"))
      .exec(http("request_60")
        .get(uri4 + "?family=Roboto:400,300,500,700"))
      .exec(http("request_61")
        .post("/verify_access.ashx")
      )
      .exec(http("request_62")
        .get("/profile/leave_ent.aspx?_TSM_CombinedScripts_=True&v=ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1&_TSM_Bundles_=&cdn=False")
      )
      .pause(159.milliseconds)
      .exec(http("request_63")
        .get("/Content/ESS/fonts/icomoon.ttf?5vru0d")
      )
      .exec(http("request_64")
        .get("/Notifications/GetNotificationCounts")
      )
      .exec(http("request_65")
        .get("/Account/VerifyAccess")
      )
      .exec(http("request_66")
        .get("/Notifications/ViewNotifications?type=ezKxwFfxMr5unVG65EuNODgVELkYDSvpO0hXrVMZdVcWtxMJu5W2F7LJtI8lfi5Bz4zxCPSK0FhtgKedRWk+c7BNB4lEruAvVt74iR1kAU4ae9hkzyWldpNDRf34Io5VurrwEjdIg/4Te/CAmnP420HBn9dHyihWl4jyWawPs40=")
      )
      .pause(201.milliseconds)
      .exec(http("request_67")
        .get("/Account/VerifyAccess")
      )
      .exec(http("request_68")
        .get("/Notifications/GetNotificationsList?row=8")
      )
  }
  def clickLeaveEntitlement = {
    exec(http("Click Request Id")
      .post("/profile/leave_ent.aspx?Mode=S")
      .formParam("__EVENTTARGET", "ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$btnViewDtl")
      .formParam("__EVENTARGUMENT", "")
      .formParam("_TSM_HiddenField_", "ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1")
      .formParam("__LASTFOCUS", "")
      .formParam("__VIEWSTATE", "${viewStateTable}")
      .formParam("__VIEWSTATEGENERATOR", "D9B199BA")
      .formParam("ctl00$ctl00$ctl00$selCultureName", "")
      .formParam("ctl00$ctl00$ctl00$selCountry", "1")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfViewBy", "S")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfStoreAsHr", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfLeaveStartDate", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfLeaveEndDate", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtYear", "2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfSubordinate", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfSubordinateNo", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfSubordinateEmploymentID", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtSubordinate", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$selLeaveType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$chkActive", "on")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$chkDirect", "on")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$gvSearch$ctl53$gpCustomPager$txtPageSize", "50")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfIndex", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfOriYear", "2021")
      .check(bodyString.saveAs("ViewBalance"))
      .check(regex("""<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="(|.+?)" />""").saveAs("ViewBalanceDetail"))
    )
      .exec(http("request_70")
        .get("/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZOYXOnLy43dRx8HCf3vqtm7Uk9Dd5QTT0bKPZkChPJpkGd7et7925jgqVFYijtH4BlZm86YPMFKavMb3jiNdHO_DkODjc9ASxqTpYjlOyMlE0&t=637454358340000000"))
      .exec(http("request_71")
        .get("/ScriptResource.axd?d=x6wALODbMJK5e0eRC_p1LTFBEqAduy6yzdGuAMP1dHrya3_IF2A8CsbaRF-ARwHq6m-SGT1rW_kEfDOVxpLiOwBwjQzZMYd6yIJvZ9ubgIyIzxTTWWPxLOJ6h2brQiXEeYW7vHWkdtbfdWvIHio91FSsDXmcUmI7kjdMETOH_XE1&t=51e37521"))
      .exec(http("request_72")
        .get("/ScriptResource.axd?d=P5lTttoqSeZXoYRLQMIScIf12FcrWAiNVtlJxQA9qnTW6iJpMmht7uXNg23QNwOPVke9qF6NTd062q-kq39p4MmkxhZ1ti3ckmNVSJHDik9HIeiTEBJ8AeazBYyjXlRbQWV2Q8-MBT7ldJqGwC6gtX5XcIt2Wd4nEFDQxuD-poI1&t=51e37521"))
      .exec(http("request_73")
        .get("/ScriptResource.axd?d=XGoPW3Unw0ILT0eb9sSUayB1PCvz0eeMXm23ajXUnLKSVWvpEIM7qNdgqQtwIk3oGSO-umSPRJr1BQNhALudg4-gDqI9ltlNkOQMrPf4fNHBEAhja6GHf4He4_YSEbkQ4L1Bsn1aV_AF11ks4fQlTNxlg6tYk_UGpXjfNcFSD6D49VS2gjNTnElk4fHlLsM90&t=51e37521"))
      .exec(http("request_74")
        .get("/ScriptResource.axd?d=uvA9ANM76Fbpm1FfUlagnYp2obqkhmwI_C-NoQ89dB6TwrO7THFVAk1nHl1QRi68J_pozjXYUJHgZb6l02O3dvVqjaOzdIW44mTvv4FyAQ5MvnVeKZmB7OtG9BNkATLGOGWXvK2djBpsGpZ_x3Mi2KdwGSD0SZeW5VvD940G1Y8Cml0nm6ok2UFWSXa6k4SQ0&t=51e37521"))
      .exec(http("request_75")
        .get(uri4 + "?family=Open+Sans:300,400,600,700"))
      .exec(http("request_76")
        .get(uri4 + "?family=Roboto:400,300,500,700"))
      .exec(http("request_77")
        .post("/verify_access.ashx")
      )
      .exec(http("request_78")
        .get("/Content/ESS/fonts/icomoon.ttf?5vru0d")
      )
      .exec(http("request_79")
        .get("/profile/leave_ent.aspx?_TSM_CombinedScripts_=True&v=ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1&_TSM_Bundles_=&cdn=False")
      )
      .pause(157.milliseconds)
      .exec(http("request_80")
        .get("/Notifications/GetNotificationCounts")
      )
      .exec(http("request_81")
        .get("/Account/VerifyAccess")
      )
      .exec(http("request_82")
        .get("/Notifications/ViewNotifications?type=h4j0dckiSlJKhq3cm5Jb+272gX14DPJOC8jF4xp2JCkNi/R0nNiopDHRmXPpCdKSkr0xE7KhxOwCrPhEWsnO4IdvN7KSxPZGTiMd9VdrAtgpSlP73yVkEuNFD2+F5RQw3sOs81K0+MTgrP0chLgHE7ghiRg6zpZ3zGR5M0z7Ki8=")
      )
      .pause(100.milliseconds)
      .exec(http("request_83")
        .get("/Account/VerifyAccess")
      )
      .exec(http("request_84")
        .get(uri2 + "?v=4.7.0")
      )
      .exec(http("request_85")
        .get("/Notifications/GetNotificationsList?row=8")
      )
  }
  def logout = {
    exec(http("Logout")
      .post("/profile/leave_ent.aspx?Mode=S")
      .formParam("__EVENTTARGET", "ctl00$ctl00$ctl00$lbLogout")
      .formParam("__EVENTARGUMENT", "")
      .formParam("_TSM_HiddenField_", "ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1")
      .formParam("__VIEWSTATE", "${ViewBalanceDetail}")
      .formParam("__VIEWSTATEGENERATOR", "D9B199BA")
      .formParam("ctl00$ctl00$ctl00$selCultureName", "")
      .formParam("ctl00$ctl00$ctl00$selCountry", "1")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfIndex", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrContent$hfOriYear", "2021")
      .check(status.is(302)))
      .exec(http("request_87")
        .get("/Account/Login")
      )
      .exec(http("request_88")
        .get("/DXR.axd?r=1_17,0_2214,1_50,1_53,1_51,1_16,0_2219,0_2312,0_2317-P3Vxm"))
      .exec(http("request_89")
        .get("/Content/css?v=w9USDPGryprQSMA62T1giyRXrtqAIG-BphxyQY0Qw_w1"))
      .exec(http("request_90")
        .get("/bundles/jquery?v=w1vknpWt6KqlZcHeJQvaK6VbvvXt1Go8HcGH_DqKzzo1"))
      .exec(http("request_91")
        .get("/DXR.axd?r=1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_208,1_216,1_212,1_189,1_222,17_42,1_297,1_215,1_207,1_289,1_205,17_7,1_287,1_211,17_23,1_197,17_1-P3Vxm"))
      .exec(http("request_92")
        .get("/DXR.axd?r=1_58-P3Vxm"))
      .exec(http("request_93")
        .get("/Content/Images/bg-login.jpg?V=03"))
      .exec(http("request_94")
        .get("/Content/fonts/icomoon.ttf?5vru0d")
      )
  }
}
