package computerdatabase.Module.Leave
import io.gatling.core.Predef._
import io.gatling.http.Predef._
import scala.concurrent.duration._
import scala.util.matching.Regex
object ESSSUPMyTeamViewLeaveApplication {

    val uri1 = "https://maps.googleapis.com/maps/api/js"
    val uri2 = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2"
    val uri4 = "https://fonts.googleapis.com/css"
    val uri3 = "https://fonts.googleapis.com/css"

    def loadLeaveApplication = {
        exec(http("Load Application Page")
          .get("/profile/leave_lst.aspx?Mode=S")
          .check(status.is(200))
          .check(bodyString.saveAs("TableLeave"))
          .check(regex("""<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="(|.+?)" />""").saveAs("viewApplication"))
        )
          .pause(137.milliseconds)
          .exec(http("request_55")
            .get("/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZOYXOnLy43dRx8HCf3vqtm7Uk9Dd5QTT0bKPZkChPJpkGd7et7925jgqVFYijtH4BlZm86YPMFKavMb3jiNdHO_DkODjc9ASxqTpYjlOyMlE0&t=637454358340000000")
          )
          .exec(http("request_56")
            .get("/ScriptResource.axd?d=XGoPW3Unw0ILT0eb9sSUayB1PCvz0eeMXm23ajXUnLKSVWvpEIM7qNdgqQtwIk3oGSO-umSPRJr1BQNhALudg4-gDqI9ltlNkOQMrPf4fNHBEAhja6GHf4He4_YSEbkQ4L1Bsn1aV_AF11ks4fQlTNxlg6tYk_UGpXjfNcFSD6D49VS2gjNTnElk4fHlLsM90&t=51e37521")
          )
          .exec(http("request_57")
            .get("/ScriptResource.axd?d=x6wALODbMJK5e0eRC_p1LTFBEqAduy6yzdGuAMP1dHrya3_IF2A8CsbaRF-ARwHq6m-SGT1rW_kEfDOVxpLiOwBwjQzZMYd6yIJvZ9ubgIyIzxTTWWPxLOJ6h2brQiXEeYW7vHWkdtbfdWvIHio91FSsDXmcUmI7kjdMETOH_XE1&t=51e37521")
          )
          .exec(http("request_58")
            .get("/ScriptResource.axd?d=P5lTttoqSeZXoYRLQMIScIf12FcrWAiNVtlJxQA9qnTW6iJpMmht7uXNg23QNwOPVke9qF6NTd062q-kq39p4MmkxhZ1ti3ckmNVSJHDik9HIeiTEBJ8AeazBYyjXlRbQWV2Q8-MBT7ldJqGwC6gtX5XcIt2Wd4nEFDQxuD-poI1&t=51e37521")
          )
          .exec(http("request_59")
            .get("/ScriptResource.axd?d=uvA9ANM76Fbpm1FfUlagnYp2obqkhmwI_C-NoQ89dB6TwrO7THFVAk1nHl1QRi68J_pozjXYUJHgZb6l02O3dvVqjaOzdIW44mTvv4FyAQ5MvnVeKZmB7OtG9BNkATLGOGWXvK2djBpsGpZ_x3Mi2KdwGSD0SZeW5VvD940G1Y8Cml0nm6ok2UFWSXa6k4SQ0&t=51e37521")
          )
          .exec(http("request_60")
            .get(uri4 + "?family=Open+Sans:300,400,600,700")
          )
          .exec(http("request_61")
            .get(uri4 + "?family=Roboto:400,300,500,700")
          )
          .exec(http("request_62")
            .post("/verify_access.ashx")
          )
          .exec(http("request_63")
            .get("/profile/leave_lst.aspx?_TSM_CombinedScripts_=True&v=ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1&_TSM_Bundles_=&cdn=False")
          )
          .pause(187.milliseconds)
          .exec(http("request_64")
            .get("/Content/ESS/fonts/icomoon.ttf?5vru0d")
          )
          .exec(http("request_65")
            .get("/Notifications/GetNotificationCounts")
          )
          .exec(http("request_66")
            .get("/Account/VerifyAccess")
          )
          .exec(http("request_67")
            .get("/Notifications/ViewNotifications?type=PGZs92uBQyh38pxrUYW+izXxj8W3q/yQ2EjZM1B3CrfASYxfHL2WywdP3fwtYyY5U/R4UfgPNHaIB9drYRIxSayL6xdLr8WSHau2wxUoREPs3N4YSRLzi7EPOfF46O63O46cC0zSdsq0ejS1jvCh7Imx9bzYi9ZfeVSKPwcS9P4=")
          )
          .pause(115.milliseconds)
          .exec(http("request_68")
            .get("/Account/VerifyAccess")
          )
          .exec(http("request_69")
            .get("/Notifications/GetNotificationsList?row=8")
          )
    }

    def searchLeave = {
        exec(http("Search Filter")
          .post("/profile/leave_lst.aspx?Mode=S")
          .formParam("__EVENTTARGET", "ctl00$ctl00$ctl00$cntPlcHldrContent$btnSearch")
          .formParam("__EVENTARGUMENT", "")
          .formParam("_TSM_HiddenField_", "ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1")
          .formParam("__LASTFOCUS", "")
          .formParam("__VIEWSTATE", "${viewApplication}")
          .formParam("__VIEWSTATEGENERATOR", "6F1287B2")
          .formParam("ctl00$ctl00$ctl00$selCultureName", "")
          .formParam("ctl00$ctl00$ctl00$selCountry", "1")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfViewBy", "S")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfStoreAsHr", "0")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtDateFrom", "29/03/2020")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtDateTo", "28/04/2021")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfSubordinate", "")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfSubordinateNo", "")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtSubordinate", "")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$selLeaveType", "")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtStatus", "Pending; Approved")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$cbStatus$0", "P")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$cbStatus$1", "A")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$chkActive", "on")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$chkDirect", "on")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$gvSearch$ctl18$gpCustomPager$txtPageSize", "50")
          .check(bodyString.saveAs("ViewBodySearch"))
          .check(regex("""<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="(|.+?)" />""").saveAs("viewSearch"))
        )

          .exec(http("request_71")
            .get("/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZOYXOnLy43dRx8HCf3vqtm7Uk9Dd5QTT0bKPZkChPJpkGd7et7925jgqVFYijtH4BlZm86YPMFKavMb3jiNdHO_DkODjc9ASxqTpYjlOyMlE0&t=637454358340000000")
          )
          .exec(http("request_72")
            .get("/ScriptResource.axd?d=x6wALODbMJK5e0eRC_p1LTFBEqAduy6yzdGuAMP1dHrya3_IF2A8CsbaRF-ARwHq6m-SGT1rW_kEfDOVxpLiOwBwjQzZMYd6yIJvZ9ubgIyIzxTTWWPxLOJ6h2brQiXEeYW7vHWkdtbfdWvIHio91FSsDXmcUmI7kjdMETOH_XE1&t=51e37521")
          )
          .exec(http("request_73")
            .get("/ScriptResource.axd?d=P5lTttoqSeZXoYRLQMIScIf12FcrWAiNVtlJxQA9qnTW6iJpMmht7uXNg23QNwOPVke9qF6NTd062q-kq39p4MmkxhZ1ti3ckmNVSJHDik9HIeiTEBJ8AeazBYyjXlRbQWV2Q8-MBT7ldJqGwC6gtX5XcIt2Wd4nEFDQxuD-poI1&t=51e37521")
          )
          .exec(http("request_74")
            .get("/ScriptResource.axd?d=XGoPW3Unw0ILT0eb9sSUayB1PCvz0eeMXm23ajXUnLKSVWvpEIM7qNdgqQtwIk3oGSO-umSPRJr1BQNhALudg4-gDqI9ltlNkOQMrPf4fNHBEAhja6GHf4He4_YSEbkQ4L1Bsn1aV_AF11ks4fQlTNxlg6tYk_UGpXjfNcFSD6D49VS2gjNTnElk4fHlLsM90&t=51e37521")
          )
          .exec(http("request_75")
            .get("/ScriptResource.axd?d=uvA9ANM76Fbpm1FfUlagnYp2obqkhmwI_C-NoQ89dB6TwrO7THFVAk1nHl1QRi68J_pozjXYUJHgZb6l02O3dvVqjaOzdIW44mTvv4FyAQ5MvnVeKZmB7OtG9BNkATLGOGWXvK2djBpsGpZ_x3Mi2KdwGSD0SZeW5VvD940G1Y8Cml0nm6ok2UFWSXa6k4SQ0&t=51e37521")
          )
          .exec(http("request_76")
            .get(uri4 + "?family=Open+Sans:300,400,600,700")
          )
          .exec(http("request_77")
            .get(uri4 + "?family=Roboto:400,300,500,700")
          )
          .exec(http("request_78")
            .post("/verify_access.ashx")
          )
          .exec(http("request_79")
            .get("/Content/ESS/fonts/icomoon.ttf?5vru0d")
          )
          .exec(http("request_80")
            .get("/profile/leave_lst.aspx?_TSM_CombinedScripts_=True&v=ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1&_TSM_Bundles_=&cdn=False")
          )
          .pause(149.milliseconds)
          .exec(http("request_81")
            .get("/Notifications/GetNotificationCounts")
          )
          .exec(http("request_82")
            .get("/Account/VerifyAccess")
          )
          .exec(http("request_83")
            .get("/Notifications/ViewNotifications?type=rvyS1uXZ1fniRou536g0P+KycbSukp2519PSZumxm7AyNc4JTK9gKIwXrWLgtI1lF3rGyuTrbLZftZoG4qBrwz372/r1tGtAnEFkH19vroLfsNVq+HsTRbXMebXZfYUpWvZxK0qGkIarSpWKPZA0ojfSobEML4xtP5uRTBGXyeo=")
          )
          .exec(http("request_84")
            .get(uri2 + "?v=4.7.0")
          )
    }

  def clickRequestId = {
    exec(http("Click Request Id")
      .post("/profile/leave_lst.aspx?Mode=S")
      .formParam("__EVENTTARGET", "ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$gvSearch$ctl02$ctl00")
      .formParam("__EVENTARGUMENT", "")
      .formParam("_TSM_HiddenField_", "ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1")
      .formParam("__LASTFOCUS", "")
      .formParam("__VIEWSTATE", "${viewSearch}")
      .formParam("__VIEWSTATEGENERATOR", "6F1287B2")
      .formParam("ctl00$ctl00$ctl00$selCultureName", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfViewBy", "S")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfStoreAsHr", "0")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtDateFrom", "20/04/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtDateTo", "20/05/2021")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfSubordinate", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfSubordinateNo", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtSubordinate", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$selLeaveType", "")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtStatus", "Pending; Approved")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$cbStatus$0", "P")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$cbStatus$1", "A")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$chkActive", "on")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$chkDirect", "on")
      .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$gvSearch$ctl53$gpCustomPager$txtPageSize", "50")
      .check(status.is(302))
      .check(header("Location").saveAs("url"))
    )
      .exec(http("Redirect Url")
        .get("${url}")
        .check(bodyString.saveAs("Leave Detail"))
      )
      .exec(http("request_2")
        .get("/DXR.axd?r=0_2312,1_50,1_53,1_51,0_2317-O3Vxm"))
      .exec(http("request_3")
        .get(uri3 + "?family=Open+Sans:300,400,600,700"))
      .exec(http("request_4")
        .get(uri3 + "?family=Roboto:400,300,500,700"))
      .exec(http("request_5")
        .get("/WebResource.axd?d=G7AEkw1asyYfSFk2Li5D0JhwAppflyxkpGSQDQbA3YX7Us59q1SeSvJlGoBadgH42WWogzokgjSTil628NjzJ-ho-6akTSnjNL_1W4rKMdV6J4E7SFdllL-EXlbUGTEk-wfRgTKBSFluXwws9OgQSz64mOsqxEoa9Z9MfmluHcdALHev8eL9dk6DjmuJdzHl0&t=637529727625595181"))
      .exec(http("request_6")
        .get("/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZOYXOnLy43dRx8HCf3vqtm7Uk9Dd5QTT0bKPZkChPJpkGd7et7925jgqVFYijtH4BlZm86YPMFKavMb3jiNdHO_DkODjc9ASxqTpYjlOyMlE0&t=637505973787431984"))
      .exec(http("request_7")
        .get("/ScriptResource.axd?d=x6wALODbMJK5e0eRC_p1LTFBEqAduy6yzdGuAMP1dHrya3_IF2A8CsbaRF-ARwHq6m-SGT1rW_kEfDOVxpLiOwBwjQzZMYd6yIJvZ9ubgIyIzxTTWWPxLOJ6h2brQiXEeYW7vHWkdtbfdWvIHio91FSsDXmcUmI7kjdMETOH_XE1&t=51e37521"))
      .exec(http("request_8")
        .get("/ScriptResource.axd?d=P5lTttoqSeZXoYRLQMIScIf12FcrWAiNVtlJxQA9qnTW6iJpMmht7uXNg23QNwOPVke9qF6NTd062q-kq39p4MmkxhZ1ti3ckmNVSJHDik9HIeiTEBJ8AeazBYyjXlRbQWV2Q8-MBT7ldJqGwC6gtX5XcIt2Wd4nEFDQxuD-poI1&t=51e37521"))
      .exec(http("request_9")
        .get("/ScriptResource.axd?d=XGoPW3Unw0ILT0eb9sSUayB1PCvz0eeMXm23ajXUnLKSVWvpEIM7qNdgqQtwIk3oGSO-umSPRJr1BQNhALudg4-gDqI9ltlNkOQMrPf4fNHBEAhja6GHf4He4_YSEbkQ4L1Bsn1aV_AF11ks4fQlTNxlg6tYk_UGpXjfNcFSD6D49VS2gjNTnElk4fHlLsM90&t=51e37521"))
      .exec(http("request_10")
        .get("/ScriptResource.axd?d=uvA9ANM76Fbpm1FfUlagnYp2obqkhmwI_C-NoQ89dB6TwrO7THFVAk1nHl1QRi68J_pozjXYUJHgZb6l02O3dvVqjaOzdIW44mTvv4FyAQ5MvnVeKZmB7OtG9BNkATLGOGWXvK2djBpsGpZ_x3Mi2KdwGSD0SZeW5VvD940G1Y8Cml0nm6ok2UFWSXa6k4SQ0&t=51e37521"))
      .exec(http("request_11")
        .get("/ScriptResource.axd?d=nv7asgRUU0tRmHNR2D6t1HncJC0uSlzSoOMFzQL9KDgdtj1yUByaaYlMWCLR1tfb0zRr2KS8GU92MXS6P0lOX_vkDPQOiW6UvV384GibJ__q8DVUhGPtg7X0IEAXecIS6jMaZIGfhYY2bHennMwScvTacu4aYi7pwkjCfDx4XDhghn49oiHENcEjRtCYLFUt0&t=fffffffff6474071"))
      .exec(http("request_12")
        .post("/verify_access.ashx")
      )
      .exec(http("request_13")
        .get("/DXR.axd?r=1_58-N3Vxm"))
      .exec(http("request_14")
        .get("/Content/ESS/fonts/icomoon.ttf?5vru0d")
      )
      .exec(http("request_15")
        .get(uri2 + "?v=4.7.0")
      )
      .exec(http("request_16")
        .get("/request/leave_form.aspx?_TSM_CombinedScripts_=True&v=ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1&_TSM_Bundles_=&cdn=False"))
      .exec(http("request_17")
        .get("/DXR.axd?r=1_303,1_184,1_297,1_210,1_220,1_187,1_181,1_289,1_287-N3Vxm"))
      .pause(332.milliseconds)
      .exec(http("request_18")
        .get("/Notifications/GetNotificationCounts")
      )
      .exec(http("request_19")
        .get("/Notifications/ViewNotifications?type=Jqypgf+PDAHgnLTZmoA0p7tfoqk6rOUfpLoIkmDSD3uk2Y65JWrE+Rvds/vI83pycd3XBJbOTOR9AJxfxLB4vUX1Plj5QOAEI+TGDO8Gx5NB4k2cXsklXpYPWfdgrNrndDp3niqM9F2zJexUUclIWCfzNE6zgfJoDeRQfT/yEJA=")
      )
      .exec(http("request_20")
        .get("/Notifications/GetNotificationsList?row=8")
      )
      .exec(http("request_21")
        .post("/request/get_leave_reason.ashx")

        .formParam("LeaveType", "A")
        .formParam("EmployeeID", "")
        .formParam("EmploymentID", "5311")
        .formParam("EmployeeNo", "")
        .formParam("StartDate", "undefined 00:00")
        .formParam("EndDate", "undefined 00:00")
        .formParam("LocationID", "9"))

      .exec(session => {

        val bodyLeave = session("Leave Detail").as[String]
        println("URL : ${url}")
        println(s"Body : $bodyLeave")

        session
      })
  }


    def logout = {
        exec(http("Logout Bosskur")
          .post("/profile/leave_lst.aspx?Mode=S")
          .formParam("__EVENTTARGET", "ctl00$ctl00$ctl00$lbLogout")
          .formParam("__EVENTARGUMENT", "")
          .formParam("_TSM_HiddenField_", "ZaMfZ6yYhPPHZ1NeEf8j6-t902-6pHpn2MehV0eep-I1")
          .formParam("__LASTFOCUS", "")
          .formParam("__VIEWSTATE", "${viewSearch}")
          .formParam("__VIEWSTATEGENERATOR", "6F1287B2")
          .formParam("ctl00$ctl00$ctl00$selCultureName", "")
          .formParam("ctl00$ctl00$ctl00$selCountry", "1")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfViewBy", "S")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfStoreAsHr", "0")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtDateFrom", "29/03/2021")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtDateTo", "28/04/2021")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfSubordinate", "")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$hfSubordinateNo", "")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtSubordinate", "")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$selLeaveType", "")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$txtStatus", "Pending")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$cbStatus$0", "P")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$chkActive", "on")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$cntPlcHldrCriteria$chkDirect", "on")
          .formParam("ctl00$ctl00$ctl00$cntPlcHldrContent$cntPlcHldrContent$gvSearch$ctl06$gpCustomPager$txtPageSize", "50")
          .check(status.is(302)))
          .exec(http("request_88")
            .get("/Account/Login")
          )
          .exec(http("request_89")
            .get("/DXR.axd?r=1_17,0_2214,1_50,1_53,1_51,1_16,0_2219,0_2312,0_2317-P3Vxm")
          )
          .exec(http("request_90")
            .get("/Content/css?v=w9USDPGryprQSMA62T1giyRXrtqAIG-BphxyQY0Qw_w1")
          )
          .exec(http("request_91")
            .get("/bundles/jquery?v=w1vknpWt6KqlZcHeJQvaK6VbvvXt1Go8HcGH_DqKzzo1")
          )
          .exec(http("request_92")
            .get("/DXR.axd?r=1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_208,1_216,1_212,1_189,1_222,17_42,1_297,1_215,1_207,1_289,1_205,17_7,1_287,1_211,17_23,1_197,17_1-P3Vxm")
          )
          .exec(http("request_93")
            .get("/DXR.axd?r=1_58-P3Vxm")
          )
          .exec(http("request_94")
            .get("/Content/Images/bg-login.jpg?V=03")
          )
          .exec(http("request_95")
            .get("/Content/fonts/icomoon.ttf?5vru0d")
          )
    }
}
